### ISSUE TITLE
Webserver: can't enter @ in config screen

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#1]
E.g. in password and other fields @ is silently ignored.
Probably a problem with the keyboard normalization/conversion to St keys.

**Comment by tin-nl** [comment]
Definitely the key conversion. CEs config console takes IKBD keycodes, not chars. Without knowing the actual Key layout of the ST (or the TOS lang version for that matter), it's somewhat hard to convert to the right keys. I somewhat dodged that one on the remote by adding the ST keyboard you can click at.
However: any idea to probe the STs key layout without CE_DD having to be loaded or even ACSI/SCSI being connected? Otherwise special chars only would work correctly with CE_DD loaded, and that might be irritating.
Any ideas?

**Comment by atarijookie** [comment]
Are we talking about accessing the CE config console through web? I'm bit lost about what we are talking about (sorry)...

**Comment by tin-nl** [comment]
Yes, via web. The internal console in ce_main takes ST scancodes (through sendCmd or sth like that). For special chars like @, umlauts etc. the browser key has to be converted to the matching IKBD scancode. This is somewhat difficult without knowing the STs keyboard layout...

**Comment by atarijookie** [comment]
OK, I'm totally not getting what is wrong ;) If I press the '@' on my keyboard in ce_config through linux console in Config -> Network -> WPA SSID edit line, I see it's being added there. When I do the same in ce_config through Chrome and web interface, I still see the '@' sign added there. The '@' sign (ascii 64, or 0x40) is in the log file:

```
00551147    00000000    (2016-04-19 07:49:30)   ConfigResource::dispatch
00551148    00000001    (2016-04-19 07:49:30)   /config/terminal POST
00551148    00000000    (2016-04-19 07:49:30)   json:{"key":64}
00551206    00000058    (2016-04-19 07:49:30)   confStream - through FIFO: 01 01 40 (ires = 3)
00551207    00000001    (2016-04-19 07:49:30)   handleConfigStream -- CFG_CMD_KEYDOWN -- 40 bytes
```

Sooo, what's wrong here? I understand that if I would have the german 'U umlat' in my WPA SSID or WPA PSK, then it could be difficult to send it to the console, as I'm not sure how the ce_main_app would store it, and showing it on ST would be also difficult, because then we would have to match the right character for the right ST TOS language. But it doesn't seem to apply for the '@' sign, so what am I missing? (and sorry for being retarded ;) ).

**Comment by tin-nl** [comment]
Hm, let me retest that with @, that's probably me being retarded :)

Regarding Umlauts: many people use those in their passwords - maybe we should at least show on the screen what can be entered and what can't. Or simply show the password fields in plain text.
 As you said - matching the IKBD codes to the right TOS language is difficult. At least I don't know an automatic way without using ce_dd to prob TOS language.
We should probaly make the keyboard layout configurable (some people have different Keyboard than TOS language).

**Comment by atarijookie** [comment]
> many people use those in their passwords - maybe we should at least show on the screen what can be entered and what can't.

I could understand that in shared drive password, but I don't use that in Wifi stuff - I can't enter special slovak / german characters even on my cell phone, so even when using my wifi through my (android) cell phone, I would fail. So I don't use that in passwords, but I can imagine some people could. Maybe a test could be added to the config screen saving, which would probe for not allowed chars in the text fields, and warn users, or don't even let them save that (it would be fine with '@', would scream when some umlaut was used). 

> We should probaly make the keyboard layout configurable

For the usage of USB keyboard - I agree, this might behave in a weird way with some weird layout. The whole keyboard keys combination / special characters / special keyboard layout / IKDB handling thing could take few weeks of work to improve stuff... 

...although I'm not sure if that's what the majority wants - they still keep asking for new features ;) It feels like they like more and new features even if they are broken, than few but perfect features instead.

**Comment by tuxie01** [comment]
Be careful with post / get transaction, you can get a lot of problem with the encoding, sometimes you get Problems with a bom (byte order mark) problem. The only simple way is using utf8 as transaction in web (transaction over web interface to the PI).. i see the webinterface self is set to utf8 and is the code inside the pi also set to utf8 ?

**Comment by tin-nl** [comment]
@atarijookie: do you use an english keyboard by any chance? @ with english keyboard (Shift+2) works, @ with German keyboard (AltGr+Q) doesn't. Probably a problem in term.js. I'll have alook.
@tuxie01: we post integer key codes via json, so no UTF8 problems on the PI side :) And BOM is a file marker, so it wouldn't interfere in a POST request anyways.

**Comment by tin-nl** [comment]
It is indeed a bug in term.js - it tries to derive a char from e.keyCode instead of using the char in e.key directly. But I won't fix that for now as it a) involves adding a hack to term.js and doesn't b) fix the other instances. I set this to wontfix for now, there are bigger fish to fry indeed.
Here's the diff for future reference:

```
 ce_main_app/webroot/js/term.js | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/ce_main_app/webroot/js/term.js b/ce_main_app/webroot/js/term.js
index 17a1cae..eae7a9f 100644
--- a/ce_main_app/webroot/js/term.js
+++ b/ce_main_app/webroot/js/term.js
@@ -2596,7 +2596,7 @@ Terminal.prototype.keyDown = function(ev) {
             }
             return;
           }
-          key = String.fromCharCode(ev.keyCode - 64);
+          key = ev.key; //String.fromCharCode(ev.keyCode - 64);
         } else if (ev.keyCode === 32) {
           // NUL
           key = String.fromCharCode(0);

```

**Comment by atarijookie** [comment]
@tin-nl : yes, I'm using the english keyboard. In Slovakia it's almost like non-written rule (or at least people near me have it), that you have two keyboard layouts / settings under Windows - one is english for computer stuff (writing e-mail with that @ sign, programming, ...), and one is slovak for documents writing (with national / umlaut characters) which I don't use most of the time. 

OK, I'm fine with leaving this so (for now, or forever ;) ), because as mentioned - I can't use special chars on my android phone and therefore I don't use anything else than letters and digits in my usernames and passwords, and I hope that most of the people are like that ;) , so they won't hit the issue.

**Comment by atarijookie** [comment]
Closing now - a wontfix_now thing is now probably wontfix_never.
