### ISSUE TITLE
CE_DD fails on nested Fsfirst() / Fsnext() sometimes, randomly

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#10]
Run TST_FSYS.PRG, see if nested Fsfirst() / Fsnext() test result (test: 0x310). It might succeed for the 1st time. 
Then run it again, and possibly again, and the test will fail - it will find less files than it should. 

This is a problem of either CE_DD or CE main app (or both).

**Comment by miniupnp** [comment]
On my STE the test always takes more than 5sec to complete. I increased the timeout to 15 secs and added a message
please confirm it fixes the problem :)

**Comment by atarijookie** [comment]
I have run the test on my STFM 3x in a row, all succeeded, so I guess it's fine. Thanks for finding out that it was just a bad test timeout :)
