### ISSUE TITLE
Mouse is enabled in config program

### ISSUE THREAD

**Issue by miniupnp** [atarijookie/ce-atari#103]
That is a minor bug, but mouse is enable in config program
![mouse320x200](https://cloud.githubusercontent.com/assets/1070377/21012513/b2c11e30-bd56-11e6-90e4-bb6472595207.png)

I see two possible fixes :  have the program renamed as .TOS
or manually call the Line-A function to disable mouse.

**Comment by atarijookie** [comment]
You're right, I saw that one a week ago, thought that it should be fixed, but was too lazy to do it then :) I've done it now, using lineaa() and linea9() calls, pushed in master. Needs to be verified before closing this.

**Comment by mikrosk** [comment]
While on the topic, I have a reverse bug report -- sometimes it happens that I exit the app with F10 and I see the blinking cursor. I think renaming to .TOS is the right solution here, esp. if we want to support running it in console emulators like TosWin2 one day.

**Comment by miniupnp** [comment]
@atarijookie is there a reason to name the programs .prg and not .tos ?

**Comment by atarijookie** [comment]
Errr, it looks nicer? :) (no, there isn't)

**Comment by mikrosk** [comment]
Don't forget to remove the enable/disable mouse calls (again -- console emulators wouldn't be very happy about that).

**Comment by miniupnp** [comment]
@mikrosk: are you sure about that ? can you test theses console emulators ?
(I guess they wont work on my TOS 1.06 STE :)

**Comment by mikrosk** [comment]
As I say, this is for "one day" :) So if you have a console window running in a multitasking AES (or as an accessory), you certainly don't want your .TOS/.TTP program disabling mouse and whatnot. :)

**Comment by atarijookie** [comment]
All right, @mikrosk and @miniupnp , 
I've added those disaling / enabling mouse calls few days ago....
Today I have removed them...
...and now it seems that I should keep them there... So what should it be in the next release?
A) disable + enable mouse? or...
B) don't do anything with the mouse?

I don't want any hypothetical answers about the future, just a plain vote: A or B?

**Comment by miniupnp** [comment]
It looks like the "clean" way to do it is : have VT52 progs be named .TOS / do not call Line-A to enable/disable mouse.
One exception is for drivers that have to be named .PRG to be able to be loaded in AUTO folder.
so my vote is B for tools like CE_CONF and A for drivers/TSR (which will not be run in TosWin2 anyway)

**Comment by mikrosk** [comment]
@miniupnp I think you've exchanged the As and Bs :-P

In a nutshell:

- remove all disable/enable mouse calls
- rename all "UI" apps to .TOS (or .TTP if there are some taking params) -- CE_CONF, the tests, ...
- keep the drivers like CE_STING or CE_DD as a PRG but here you don't need any mouse so no dilemma with enabling/disabling

**Comment by atarijookie** [comment]
I've made a release now, CE_CONF is now CE_CONF.TOS, it doesn't do anything with mouse cursor (like when we started this), so if you're happy with the current state, we can close this one...

**Comment by mikrosk** [comment]
@atarijookie what about the tests? Those are started from the desktop and the user can move the mouse eventually...

**Comment by atarijookie** [comment]
Yes, test could be renamed, too... I didn't test the ce_conf after renaming
to .TOS, but if you did or you are confident that it helped, I can rename
the rest...
On 13 Dec 2016 23:21, "Miro Kropacek" <notifications@github.com> wrote:

@atarijookie <https://github.com/atarijookie> what about the tests? Those
are started from the desktop and the user can move the mouse eventually...

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/atarijookie/ce-atari/issues/103#issuecomment-266880865>,
or mute the thread

**Comment by atarijookie** [comment]
Test renamed to .TOS, closing issue.

**Comment by mikrosk** [comment]
OK, after a while I'm back to the CE, too. :) I've noticed that some other apps are .PRGs even if they don't need to be -- CE_FDD.PRG and CE_MOUNT.PRG (they do seem to hide mouse but then again, it's unnecessary, they should be .TOS).

Also, CE_FDD.PRG and CE_FDD.TTP are totally reduntant -- CE_FDD should be a .TTP to which if you don't  supply any arguments would run the "UI", otherwise mount.

**Comment by miniupnp** [comment]
> Also, CE_FDD.PRG and CE_FDD.TTP are totally reduntant -- CE_FDD should be a .TTP to which if you don't supply any arguments would run the "UI", otherwise mount.

I don't agree fully. The average user would be confused when asked for arguments after double clicking on the .TTP, so having the .PRG for UI and .TTP for command line only is better in my opinion

**Comment by mikrosk** [comment]
@miniupnp: well, that's a matter of personal taste. for instance, I, as an Atari veteran, know that .TTP can run also without parameters (as many unix tools do), at least as the last resort I'd always try to run it to see what parameters it accepts. :) But I'm not saying everyone shares this attitude, sure. I just didn't like two binaries for the same task.

**Comment by mikrosk** [comment]
OK guys, what about this one? Who's for merging CE_FDD.PRG and CE_FDD.TTP into one binary (CE_FDD.TTP) which would act as an "UI" app when without params and as a mount tool when with a parameter.

**Comment by atarijookie** [comment]
I don't care if it's two apps, or MiKRO's proposed merged app. I'll leave it to others to decide :)

But I'm a supporter of creating a simple GUI (GEM / just drawing things on screen) for the floppy slot upload / select / swap part of CE_FDD.PRG, as mentioned in #46 - This console UI for floppy selection is ugly :)

**Comment by mikrosk** [comment]
There's no argument from my side, a GEM app would be awesome to have. Perhaps you could create a thread on AF with request like that? There's a few GEM programmers out there.

**Comment by miniupnp** [comment]
@mikrosk is that possible to pass argument to GEM program with TOS 1.x ?

**Comment by mikrosk** [comment]
I'm not sure now, do you think there's a reason to think that .GTP is supported only from higher TOS versions?

**Comment by miniupnp** [comment]
http://www.atari-wiki.com/?title=History_of_Atari_TOS
GTP appeared in TOS 2.X

**Comment by atarijookie** [comment]
TTP version now has a feature that if you don't supply anything, it will find and insert first image in the same directory (used by AdamK in a similar way)
PRG version is now under development to become GEM version (#46)

They could get merged to one like this:
- no argument (just press enter) - open GEM GUI (#46)
- '*' as argument - find first image in directory, load it and select slot
- path to image as argument - load it, select slot

So we would get rid of one extra app (the separate TTP version), but we would annoy the users with extra button press on opening GUI.

**Comment by atarijookie** [comment]
...or another option would be - merge the code for PRG and TTP, so we will have one source that does it all, but copy it twice to the config drive - once with PRG extension, once with TTP extension - that way the  code would be united, needs to be compiled only once, plus we would not annoy people with extra Enter / click on the start?

**Comment by mikrosk** [comment]
Although I'm no fan of two binaries, it does seem like the most plausible approach.

**Comment by atarijookie** [comment]
Now the silly question - how do I tell if the app was runned as TTP or as PRG? I was hoping for good old argv[0] having name of executable in it, but this isn't the case on atari - there seems to be only the arguments passed to the executable... 

The dumb way now I'm going it is the one which I've mentioned above - no arg means GUI, single char means find first, longer string means filename, and with binary named as PRG there should be always the no arg for that one (until someone drag-and-drops something on it)...

**Comment by mikrosk** [comment]
Since you are going to compile two apps anyway you can cheat and `#ifdef` the code accordingly. :)

Nice discussion about the topic is here: http://www.atari-forum.com/viewtopic.php?t=33702

**Comment by atarijookie** [comment]
Hmm, I wanted to compile only one app and just copy and rename it after compilation ;) but since I really can't figure out other method for determining PRG / TTP, this might be just it...

**Comment by atarijookie** [comment]
Mouse in ce_conf.prg is not enabled anymore (for a long time). Sources of CE_FDD.PRG and CE_FDD.TTP were merged, now they need to be compiled with different flag in makefile into two separate apps. I guess this task / issue is done, so closing.
