### ISSUE TITLE
have all test programs on config drive

### ISSUE THREAD

**Issue by miniupnp** [atarijookie/ce-atari#106]
I was thinking that we could/should put a directory TESTS (or TESTPRGS ?) on config drive with all test programs.
I do have the test the programs on O: but at the root :)
That would be easier to understand for users ? 

that may be a stupid proposal, feel free to comment ;)

**Comment by atarijookie** [comment]
No, it's a good proposal, I thought of something similar some time ago, also with the drivers (CE_DD, CE_STING, CE_SCREENCAST) having their own DRIVERS directory, but as I could screw up the loading of CE_DD (by not changing to new path), I didn't do this... Feel free to do this. Things to keep in mind:

- check if after change they are correctly all copied from /ce/app/configdrive to /tmp/configdrive, where the DESKTOP.INF and NEWDESK.INF are generated
- check if the CE TOOLS floppy image is correctly generated for all these items located now in subdirs - little bit related with #108

**Comment by atarijookie** [comment]
Sooo.... Should I put the files in TESTS, DRIVERS and rest in root in the next release? :)

**Comment by tin-nl** [comment]
Good proposal! So: yes :) I'd like to add that a readme.txt would be swell to add :) I'll post a short text for this in a moment.

**Comment by tin-nl** [comment]
_Sth like this?_

Welcome to the CosmosEx config drive! 
Here you'll find all the tools you need to use the advanced features of your CosmosEx (meaning: features besides basic HDD functionality).
Please make sure you have read the manuals (http://joo.kie.sk/?page_id=415). For a Quickstart guide, see http://joo.kie.sk/?page_id=704. Find more in-depth info in DrCoolZics docs at http://joo.kie.sk/cosmosex/download/CosmosEx_Users_Guide.pdf. 
Also please visit your CosmosEx Webinterface on it's configured network address (see your DHCP server for that or configure a static IP for that) for more confortable configuration and more infos.

This drive contains the following tools:

General:

ce_conf.prg  - Configure your CosmosEx 

ce_fdd.prg   - Download and mount ST files (Floppy Disk Images) 

ce_fdd.ttp   - Install this application for MSA or ST extensions (Floppy Disk Images) on your ST to automaticly mount these into your Floppy Disk Emulation.

ce_hdimg.ttp - Mount Hard Disk Image Files with this tool - e.g. backups from your old harddisks 

Folder DRIVERS\ (only needed for advance CosmosEx functionality, NOT for basic HDD usage):

ce_dd.prg    - This driver is only needed if you want to use translated drives (e.g. windows thumb drives emulated as TOS drives or network drives), screenshots and current date. This is only needed if you don't boot from CE_DD ACSI, then it loads automaticly (see manual). 

ce_sting.prg - Highly experimental STiNG replacement for networking. Not needed for mounting networked drives (see CE_DD.PRG for that).

ce_cast.prg  - Screencast your STs desktop to your web browser and remote control it

Folder TESTS\ (Test tools for debugging issues that may arise):

ce_tsthd.prg - Tests ACSI/SCSI communication with several tests (Stresstests, R/W checksums etc.)

ce_tstfd.prg - Tests Floppy Disk Emulation 

tst_fsys.prg - Tests File System (mainly Translated Drives)

**Comment by tin-nl** [comment]
Hm, "layout" is missing, here in a more ST friendly form:
```
Welcome to the CosmosEx config drive!
Here you'll find all the tools you need to use the advanced features of your CosmosEx (meaning: features besides basic HDD functionality).
Please make sure you have read the manuals (http://joo.kie.sk/?page_id=415). For a Quickstart guide, see http://joo.kie.sk/?page_id=704. Find more in-depth info in DrCoolZics docs at http://joo.kie.sk/cosmosex/download/CosmosEx_Users_Guide.pdf.
Also please visit your CosmosEx Webinterface on it's configured network address (see your DHCP server for that or configure a static IP for that) for more confortable configuration and more infos.

This drive contains the following tools:


General:
------------
ce_conf.prg  - Configure your CosmosEx

ce_fdd.prg   - Download and mount ST files (Floppy Disk Images)

ce_fdd.ttp   - Install this application for MSA or ST extensions (Floppy Disk Images) on your ST to automaticly mount these into your Floppy Disk Emulation.

ce_hdimg.ttp - Mount Hard Disk Image Files with this tool - e.g. backups from your old harddisks


Folder DRIVERS\ (only needed for advance CosmosEx functionality, NOT for basic HDD usage):
------------
ce_dd.prg    - This driver is only needed if you want to use translated drives (e.g. windows thumb drives emulated as TOS drives or network drives), screenshots and current date. This is only needed if you don't boot from CE_DD ACSI, then it loads automaticly (see manual).

ce_sting.prg - Highly experimental STiNG replacement for networking. Not needed for mounting networked drives (see CE_DD.PRG for that).

ce_cast.prg  - Screencast your STs desktop to your web browser and remote control it


Folder TESTS\ (Test tools for debugging issues that may arise):
------------
ce_tsthd.prg - Tests ACSI/SCSI communication with several tests (Stresstests, R/W checksums etc.)

ce_tstfd.prg - Tests Floppy Disk Emulation

tst_fsys.prg - Tests File System (mainly Translated Drives)
```

**Comment by miniupnp** [comment]
to be friendly with ST, no line should be longer than 40 chars ;)

**Comment by tin-nl** [comment]
@miniupnp: ah, now your getting plain mean ;-) But of course you are right at that - fix on the way :)

**Comment by tin-nl** [comment]
I sincerely apologize for my ASCII art, but here is the 40c version:
```
Welcome to the CosmosEx config drive!

Here you'll find all the tools you need 
to use the advanced features of your 
CosmosEx (meaning: features besides 
basic HDD functionality).

Please make sure you have read the 
manual (http://joo.kie.sk/?page_id=415). 

For a Quickstart guide, see 
http://joo.kie.sk/?page_id=704. 

Find more in-depth info in DrCoolZics 
docs at 
http://joo.kie.sk/cosmosex/download/
CosmosEx_Users_Guide.pdf

Also please visit your CosmosEx Web-
interface on it's configured network 
address (see your DHCP server for that 
or configure a static IP) for more 
confortable configuration and more 
infos.

This drive contains the following tools:


General
-------
ce_conf.prg  - Configure your CosmosEx

ce_fdd.prg   - Download and mount ST 
               files (Floppy Disk 
               Images)

ce_fdd.ttp   - Install this application
               for MSA or ST extensions 
               (Floppy Disk Images) on 
               your ST to automaticly 
               mount these into your 
               Floppy Disk Emulation.

ce_hdimg.ttp - Mount Hard Disk Image 
               Files with this tool - 
               e.g. backups from your 
               old harddisks


Folder DRIVERS\
---------------
(only needed for advanced CosmosEx 
 functionality, NOT for basic HDD usage)

ce_dd.prg    - This driver is only 
               needed if you want to use
               translated drives (e.g. 
               windows thumb drives 
               emulated as TOS drives or 
               network drives), 
               screenshots and current 
               date. This is only needed
               if you don't boot from 
               CE_DD ACSI, then it loads 
               automaticly (see manual).

ce_sting.prg - Highly experimental STiNG
               replacement for net-
               working. Not needed for 
               mounting networked drives
               (see CE_DD.PRG for that).

ce_cast.prg  - Screencast your STs desk-
               top to your web browser 
               and remote control it


Folder TESTS\ 
-------------
(Test tools for debugging issues that 
 may arise)

ce_tsthd.prg - Tests ACSI/SCSI communi-
               cation with several tests
               (Stresstests, R/W checks-
               ums etc.)

ce_tstfd.prg - Tests Floppy Disk Emu-
               lation

tst_fsys.prg - Tests File System (mainly
               Translated Drives)
```

**Comment by atarijookie** [comment]
Silly question - I thought it would be good to put the General stuff in the TOOLS directory, I've already changed that 3 hours ago (didn't push it yet), so the question is:
- should the general tools be in root, or
- should they go in the TOOLS subdir?

**Comment by miniupnp** [comment]
I think the .TTP should be in root dir to keep the DESKTOP.INF/NEWDESK.INF as small as possible :)
I would put other general tools in root too

**Comment by tin-nl** [comment]
I vote for general tools in root, too. I first thought a TOOLS dir would be a good idea, too, for consistency reasons etc. But especially ce_conf, ce_fdd etc. is used very often, we might not want to hide them.

**Comment by atarijookie** [comment]
I've made a release, didn't test it as I'm not at my ST (seems to work fine without ST, though). 
- things moved to DRIVERS, TEST and root (as you voted)
- added tin's readme.txt
- ce_conf is now ce_conf.tos
- made many changes to first start - not creating floppy images, ZIPs, just extracting them, see #108 

If anyone is fine with it, we can close this one.

**Comment by mikrosk** [comment]
`This driver is only needed if you want to use translated drives (e.g. windows thumb drives emulated as TOS drives or network drives), screenshots and current date. This is only needed if you don't boot from CE_DD ACSI, then it loads automaticly (see manual).`

I know I'm late to the party but in a next version I'd suggest to make this clearer because for me, whos knowledge about the CE is limited at least, this isn't 100% explanatory. What about something as:

`This is only needed if you don't boot from the CosmosEx device directly (which is set by default), for instance from your own hard disk. Otherwise you don't need to touch it. Its purpose is the same as the built-in one's -- accessing USB thumb and network drives as TOS drives, making screenshots and having current date.`

**Comment by tin-nl** [comment]
If only you told us so back then ;) 
Sure, this could be more clear. But I'm not 100% sold on your version - purpose of my sentence is countering exactly, what your version is implying: you _don't_ need ce_dd at all for basic HDD use. There seems to be an astonishing amount of people thinking ce_dd somehow is needed for the CE to use the SD card (aka act as Ultrasatan). Also, it is needed if you boot from SD card.

How about:
`
You only need this in your AUTO folder if you boot from another harddrive or the CosmosEx SD card. By default CosmosEx boots a builtin version of this -  so normally you don't need to touch it. CE_DD (builtin and standalone) handles the more advanced features of your CosmosEx like accessing thumb drives, making screenshots and keeping the current date - it's kind of a supercharger for TOS. Neither  version is needed for basic HDD functionality on SD cards.
`

Maybe this gets both our points across?

**Comment by tin-nl** [comment]
Edit: made the text even more awesome.

**Comment by mikrosk** [comment]
My point was that I, a stupid CE user, have no clue about this at all when I first power on the device. So what do I see? Booting CE. Where the boot stuff comes from? Some kind of *disk*. I open O: and I see this *driver*. Maybe it's an update? Maybe I have to copy it somewhere? 

For instance, to this day I haven't managed to format and use an SD card, even though I'd bought one the day the CE had arrived -- there was reason for doing this, not a single one. I imagine majority of users doing exactly the same as me -- take an USB drive, put files there, play. Later on, maybe you get network working but still no use for the SD card.

So I would remove the last sentence, don't mention any "basic hdd usage" because for me, "basic hdd usage" means exactly this -- having the CE up and running, perhaps with an USB drive. Apart from that, I'm sold on your version. ;)

**Comment by tin-nl** [comment]
How about:
`Neither version is needed if you only want to use the ATARI formatted SD card and none of the other features.`
then? For orientation (also for more tech-savvy people) it should be clear what it's really needed for and when it's not.

**Comment by atarijookie** [comment]
readme.txt modified, closing. Thank you for help and the readme.txt :+1:
