### ISSUE TITLE
CE_DD doesn't support Fseek() on write operations well

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#11]
CE_DD wasn't tested on Fseek() when doing WRITE to files, so it will be most probably wrong. There are no tests in it in TST_FSYS.PRG

It will most probably fail for files doing READ/WRITE operations over the single file, too.

The Fseek() for READ operations has been fixed just recently, and there are also tests for that in TST_FSYS.PRG

**Comment by miniupnp** [comment]
should the test be included in test_filesystem/test05.c test058x() ?

I think I can write a test that : 
write a file (like n bytes) then Fseek / Fwrite / Fseek / Fwrite / Fseek / Fread / etc.
then close the file, open it again and verify everything is a expected.

**Comment by atarijookie** [comment]
I would create another test and not add it to READ+SEEK test :) 

_(Don't take the following as I'm telling you what to do, I'm writing it here so I would remember it + to note the possible test cases, you might drop doing this if it's too much work or something.)_

We need many simple tests for that (not a single huge one), so the tests should be like:
- open file for Writing, write bytes, seek to START of file (using SEEK_SET, SEEK_CUR, SEEK_END) and check error code, write different bytes, close file, check file size and content by reading = 3 test cases
- open file for Writing, write bytes, seek to MIDDLE of file (using SEEK_SET, SEEK_CUR, SEEK_END) and check error code, write bytes, close file, check file size and content by reading = 3 test cases
- open file for Writing, write bytes, seek to END (using SEEK_SET, SEEK_CUR, SEEK_END) and check error code, write bytes, close file, check file size and content by reading = 3 test cases
- add a similar test, which would seek to MIDDLE of file, write LESS bytes than there were originally in the file, and see if the file beyond that got truncated or what
- do a test, which would combine seek to START, MIDDLE, END, a couple of times
- do the same, when the file is open for reading and writing (another 11 test cases), but add also some reading of the file while it is open...

**Comment by miniupnp** [comment]
I added a small test.
It pass without problem in hatari and on a real STE with the Floppy (100% sure the floppy has the right TOS behaviour :)
but it fails right away on a translated USB stick. It looks like Fseek(0, f, SEEK_CUR) is not even returning the proper position after a write

**Comment by miniupnp** [comment]
My test is pretty basic, we can enrich it later.
However, I'm checking the return of each function
and at the end the whole content of the file.

**Comment by miniupnp** [comment]
For some reason the CE receive 2 Fseek commands... it rewind to the begin of file...

```
TranslatedDisk::createFullAtariPath - inPartialAtariPath: TESTB00F
TranslatedDisk::createFullAtariPath - without drive letter, relative path -- TESTB00F
TranslatedDisk::createFullAtariPath - outFullAtariPath is: /TESTB00F
DirTranslator::getShortenerForPath - shortener for /mnt/sda found
DirTranslator::shortToLongPath - shortToLongFileName() failed for short name: TESTB00F
TranslatedDisk::createFullHostPath - dirTranslator.shortToLongPath -- root: /mnt/sda, inFullAtariPath: /TESTB00F -> part

TranslatedDisk::replaceHostPathWithZipDirPath_internal -- no ZIP file in hostPath: /mnt/sda/TESTB00F
TranslatedDisk::createFullHostPath - replaceHostPathWithZipDirPath -- new outFullHostPath: /mnt/sda/TESTB00F , waitingForMount: 0, zipDirNestingLevel: 0
TranslatedDisk::isDriveIndexReadOnly -- drive index: 8 -> not READ ONLY 
TranslatedDisk::onFcreate -- TODO: setting attributes needs to be implemented!
TranslatedDisk::onFcreate - /mnt/sda/TESTB00F - success, index is: 0

handleAcsiCommand: 5f a0 43 45 03 40 00 00 00 20 01 12 00 00
handleAcsiCommand isIcd
handleAcsiCommand - CE specific command - module: 03
TranslatedDisk function - GEMDOS_Fwrite (40)
TranslatedDisk::onFwrite - all 32 bytes were written

handleAcsiCommand: 5f a0 43 45 03 42 00 00 00 00 00 00 00 00
handleAcsiCommand isIcd
handleAcsiCommand - CE specific command - module: 03
TranslatedDisk function - GEMDOS_Fseek (42)
TranslatedDisk::onFseek - atariHandle: 0, offset: 0, seekMode: 0
TranslatedDisk::onFseek - ok, current position is 0, and we got 32 bytes to end of file

handleAcsiCommand: 5f a0 43 45 03 42 00 00 00 00 00 01 00 00
handleAcsiCommand isIcd
handleAcsiCommand - CE specific command - module: 03
TranslatedDisk function - GEMDOS_Fseek (42)
TranslatedDisk::onFseek - atariHandle: 0, offset: 0, seekMode: 1
TranslatedDisk::onFseek - ok, current position is 0, and we got 32 bytes to end of file

```

**Comment by miniupnp** [comment]
SEEK_CUR is 1, SEEK_SET is 0. The firt Fseek should not happen

**Comment by miniupnp** [comment]
ok the problem is coming from ce_dd.prg, some weird stuff is going on in fseek_cur

**Comment by atarijookie** [comment]
There was the same / similar issue with Fseek() when doing **read** operations:
1) first it was implemented on a bad idea,
2) then the bug was reported 
3) the issue was fixed by reimplementing it on a new idea

It was copied and pasted on write operations in step 1), that's why the write is still broken, and there hasn't been any 2) and 3) yet. 

So I suggest looking at Fseek() on read operations, and doing it very similarly - reusing it, or combining it...

**Comment by miniupnp** [comment]
I had a look at how it works. I guess I will indeed reimplement the Fseek/Fread/Fwrite

**Comment by miniupnp** [comment]
anyway, any feedback on how I implemented the test is welcome. I'm not sure I named the function or called the log properly

**Comment by miniupnp** [comment]
The issue was simpler that I though... the pointer was just not updated after Fwrite !
we could add a few Fseek() in the other existing tests, just to check that theorical position matches the position returned by Fseek()
