### ISSUE TITLE
CE Update / Version Info screen missing from config dump file

### ISSUE THREAD

**Issue by tin-nl** [atarijookie/ce-atari#110]
@atarijookie: now that the update screen carries some vital information about the CE version, wether it's jumpered for SCSI or ACSI etc. it's probably best to add this screen to the overall config dump too.

Was there any reason back in the day to not include it that I don't know of and that prevents it to be added now? 
If not, I took the liberty to do the tremendous amount of work to add it ;-) See https://github.com/atarijookie/ce-atari/tree/configdump_update

**Comment by atarijookie** [comment]
Wow, nice little feature / improvement, I'm fine with it, thanks ;)

**Comment by tin-nl** [comment]
Well, it was basicly done by yourself, so thanks must go to you :) I'll merge it then.
