### ISSUE TITLE
Make locating the HDD images easier in config

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#117]
tIn wrote on atari-forum:

``
For a translated thumb drive (aka thumb drive windows formatted) you'll enter /mnt/sda1/[add path on thumb drive to image file here]. Use forward slashes only, especially for the last part of your path.
If you have several thumb drives it's "sdb1" instead of "sda1" for the next one etc. It does not work on RAW drives.
But - and that's where it gets interesting - it works on network drives, too! For network drive, enter /mnt/shared/[add path on network drive to image file here].
``

To simplify this, I suggest the following:
A) for shared drive path one could enter 'shared/path_on_shared_drive, the keyword **shared** on start would be replaced to /mnt/shared
B) for USB drives the path would be: usb/path_on_usb_drive, and they keyword **usb** would be replaced with the current USB drive path, e.g. it would see if the 1st usb drive (/dev/sda1) has that image file, and if not, then it would see if the 2nd usb drive has the image file - this would help users to not care which partition on which sd* device got mounted when he inserted that USB drive
C) when the 'shared/' or 'usb/' is already written on the path line, some enter or tab key could trigger looking for the larger files, or having the incomplete path there could trigger completion like in command line, e.g. entering 'usb/myima[tab]' could result in finding myimage.img file and finishing the line -> 'usb/myimage.img' 
D) added wildcard option for the lazy ones :) e.g. allowing to have path 'usb/*.img' which would result in attaching the first found .img file on attached USB drive

A) and B) are easy to do, D) could be also easy, C) could be harder. 

You can discuss here if it's needed, if it's not too complicated, if you would do it in other way, or if you want to do it ;) If no one will play with it until start of january, I might do it in january - once I return to that place where I have some spare time for this ;)

**Comment by miniupnp** [comment]
some work ;)
Anyway we should advice user to use the mount tool

**Comment by atarijookie** [comment]
I'll do that some work when I'm back at my regular job after holidays. 

Adding the advice to use the mount tool to the config screen is also a good idea... :+1:

**Comment by miniupnp** [comment]
@atarijookie I think you forgot to include ce_hdimg.ttp in latest update. it looks like you are not using the "make update " ;)

**Comment by atarijookie** [comment]
No, I didn't get to that, as the last release was still from home, but now I'm at work, so possibly next release (when you and MiKRO agree on the IKDB changes, which seems like you already did) will be probably from work, using that...

**Comment by miniupnp** [comment]
@atarijookie well if the CE_CONF advise user to use the CD_HDIMG.TTP tool, it has to be included :)
