### ISSUE TITLE
Some keys in linux ce_conf act like Esc when they shouldn't

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#119]
This shouldn't happen on CE_CONF.TOS and also doesn't happen on CE_CONF through web console. Happens under linux when using /ce/ce_conf.sh, and to reproduce it, you can do the following:
- go to some edit line, e.g. shared -> username
- delete chars using delete key
- press '0' (to write zero) and instead of writing 0 it jumps back to main menu. 

This is due to retarded way of reading and decoding the keys under linux ce_conf - so either fix this reading / decocing, or use something else than getchar() in getKey() function.

**Comment by mikrosk** [comment]
This is not reproducible on my setup at all. Can you still reproduce?

BTW I'm asking also because I'm redoing the retarded way in a slightly less retarded way so I'm wondering whether you will be able to confirm it is an improvement in general, not only for #73.

**Comment by mikrosk** [comment]
IMO a candidate for close.
