### ISSUE TITLE
Status report shows SD card ID as 'Translated boot Image'

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#120]
I got CE_DD as ACSI 1, SD as ACSI 2. 

The status report (through web interface) shows:
ID 1	Translated boot Image : TRANSLATED BOOT MEDIA (READ-ONLY)
ID 2	Translated boot Image : TRANSLATED BOOT MEDIA (READ-ONLY)

The ID 2 should be 'SD Card' instead. Is this related to attaching of media to IDs? @miniupnp ?

**Comment by miniupnp** [comment]
hum I should have a look.

**Comment by miniupnp** [comment]
I had the same issue, but if I kill prog and relaunch, it works...

**Comment by miniupnp** [comment]
the patch 354171c fixes it for me. Is that OK for you ?

**Comment by miniupnp** [comment]
@atarijookie could you test my patch so I can merge it and close the issue ? (if that works ok, of course :)

**Comment by atarijookie** [comment]
@miniupnp OK, I'll test it during this night or tomorrow's night and let you know...

**Comment by atarijookie** [comment]
@miniupnp I didn't have a chance to test this at home, as both of my kids got fever, but I've tested it on QEMU at work, and it did the job... 

I did manually c&p the changes, I don't know what branch or whatever that patch was in, but it works, sooo thanks for the fix :+1:  You can merge it in...
