### ISSUE TITLE
Hans not updating

### ISSUE THREAD

**Issue by miniupnp** [atarijookie/ce-atari#124]
I've tried to update several times, both from web interface or from ce_conf.tos, but Hans is still "2016-01-08"

![hans_not_updated](https://cloud.githubusercontent.com/assets/1070377/21503790/1990289c-cc5a-11e6-8658-e8a81f54bb6f.png)

how to update hans manually ?

**Comment by atarijookie** [comment]
Rewrite everythin, even which is up to date:
/ce/ce_updatr.sh

Update only hans:
cd /tmp
wget http://joo.kie.sk/cosmosex/update/ce_update.zip
/ce/update/update_hans.sh

**Comment by miniupnp** [comment]
```
root@raspberrypi:/ce/update# ./update_hans.sh 
----------------------------------
 
>>> Updating Hans - START
Archive:  /tmp/ce_update.zip
  inflating: updatelist.csv
  inflating: app.zip
  inflating: hans.hex
  inflating: xilinx.xsvf
  inflating: xlnx2a.xsvf
  inflating: xlnx2s.xsvf
  inflating: franz.hex
Will use serial port:  /dev/ttyAMA0

stm32flash - http://stm32flash.googlecode.com/
           - with the fix for DS1818

>>> Will flash HANS <<<

Using Parser : Intel HEX
Serial Config: 57600 8E1
Version      : 0x22
Option 1     : 0x00
Option 2     : 0x00
Device ID    : 0x0410 (Medium-density)
RAM          : 20KiB  (512b reserved by bootloader)
Flash        : 128KiB (sector size: 4x1024)
Option RAM   : 15b
System RAM   : 2KiB

**Wrote address 0x08000400 (4.26%) Error sending command 0x31 to device
Failed to write memory at address 0x08000400**

 
>>> Updating Hans - END
```

**Comment by atarijookie** [comment]
Silly question: did you press the update button? Because that main app
version shouldn't let you do the update through web and show warning
instead...

**Comment by atarijookie** [comment]
> Wrote address 0x08000400 (4.26%) Error sending command 0x31 to device

Now that looks bad... More questions:
- can you verify that the cosmosex app is terminated before running the update_hans.sh ? There was an error few days ago that caused that cosmosex app wasn't killed when the /ce/ce_stop.sh was called on Yocto.
- you can retry the same by modifying the update_hans.sh to specify lower baud rate than 57600 when writing the firmware using flash_stm32 
- you could also try doing:
/ce/app/cosmosex reset 
before executing update_hans.sh to see if it makes any difference

**Comment by miniupnp** [comment]
On 12/27/16 18:27, Miroslav Nohaj wrote:
> Silly question: did you press the update button? Because that main app
> version shouldn't let you do the update through web and show warning
> instead...

well indeed I tried with the web interface with no success, so I tried
from CE_CONF.TOS
it did upgrade the main app, passed some time for Hans but...


I've tried to run a couple of time /ce/update/update_hans.sh
it fails at various stages :


Wrote address 0x08002c00 (46.89%) Error sending command 0x31 to device
Failed to write memory at address 0x08002c00


Wrote address 0x08003200 (53.28%) Error sending command 0x31 to device
Failed to write memory at address 0x08003200


Error sending command 0x01 to device
Wrote address 0x08001300 (20.25%) Error sending command 0x31 to device
Failed to write memory at address 0x08001300

**Comment by miniupnp** [comment]
> can you verify that the cosmosex app is terminated before running the update_hans.sh ? There was an error few days ago that caused that cosmosex app wasn't killed when the /ce/ce_stop.sh was called on Yocto.

that was the issue. I killed cosmosex it is ok now :)
just checking it is really updated

**Comment by miniupnp** [comment]
It's ok now.
But we don't know why it didn't worked in the first place

**Comment by atarijookie** [comment]
Because coSmosex was blocking gpio and uart when it was running during the
flash update? :)

**Comment by miniupnp** [comment]
so that's a bug, because I thought ce main app should stop during update of hans.

**Comment by atarijookie** [comment]
Well, yes, I wrote that a while ago:
- the ce_stop.sh script on yocto badly detected that the cosmosex wasn't
running even if it was running - I had there:
grep -v cosmosex
Instead of:
grep -v grep

- now it's fixed and your newer ce_stop.sh should have it - in case you
installed the latest main app through normal update, which extracts the new
scripts to /ce/app/shellscripts and then copies them if needed; but if you
just did your own build, then you might have older script (with bug)
there... or i screwed up the latest update also, i have to check that...

**Comment by miniupnp** [comment]
OK should have been something like that.
