### ISSUE TITLE
On TT SCSI either boots CE_DD or HDDRIVER

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#126]
1. Switch to SCSI interface
2. configure SCSI 1 as CE_DD, SCSI 2 as SD
3. reset TT, and you see either CE_DD loading and not HDDRIVER, or...
4. reset TT, hold alt to skip CE_DD, you see HDDRIVER loading

When doing random tests using CE_TSTHD, I saw once a '_' from SD - the first test, then rest was fine.

**Comment by tin-nl** [comment]
I saw sth similar with ACSI last month IIRC. I debugged the Bootsector in Hatari (with a simple ce_dd ACSI image and a normal one) but it seemed to be correct. Couldn't reproduce it on real HW, so I dropped it.
Can have a look on TT if I can reproduce your findings in the next days.

**Comment by atarijookie** [comment]
The behavior is the same on TT and ACSI, so it's probably a feature of TOS not to load more drivers once there is at least one loaded, closing for now as there is no user complaining about this, and it's also work-aroundable by placing CE_DD.PRG in AUTO of SD card.
