### ISSUE TITLE
Doing squash merges instead of merge commits

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#127]
Not really an issue, just curious -- how everybody feels about this? Because I've finally found some time to catch up and boom, I see 150 commits behind my master. Looking into log I see it's because every PR had quite a lot of commits (which is fine, of course) but master should IMHO contain only one single squash merge so I see all right, this and this has been merged. I don't need to see that Thomas changed tabs for spaces in some of his files. ;)

(if you don't know what I'm talking about: you can decide, also via Github UI, how to merge PRs -- either just "join" two branches or take all the commits from the PR, make it one and commit as one).

**Comment by miniupnp** [comment]
I personally prefer "rebase & merge" ;)

**Comment by atarijookie** [comment]
I don't care much about this, I use the big green button 'Merge pull request' on github web...

**Comment by miniupnp** [comment]
@atarijookie there is small drop down option with 3 styles of "Merge pull requests"
it matters for how the git history is

**Comment by atarijookie** [comment]
Sooo, do we want to switch it to the other style, or we just leave it as is? I don't care about this merge style, so the vote should be between miniupnp, mikro and tin (who is probably on some vacation as he isn't responding for a longer time :) )

**Comment by miniupnp** [comment]
So @mikrosk  votes for squash merges, @miniupnp for rebase, @tin-nl has the preponderant vote ;)

**Comment by mikrosk** [comment]
Yeah, I'd say unless @tin-nl returns, democracy isn't going to help us here. ;) It's not a big issue -- I just like more compact, feature based, logs, that's all.

**Comment by tin-nl** [comment]
Do we have a (managable) way to not lose history due to squash merging? I mean, it probably won't hurt to squash bigger feature branches, but it is information loss after all.

**Comment by mikrosk** [comment]
Unless you keep your own feature branch then no, it's not possible. If we don't count the automatic list of commits which github puts into default commit message.

**Comment by tin-nl** [comment]
Yeah, that's why I normally advise teams to merge, not squash. _But_ that also means that I don't have a lot of real-world experience with squash (and mostly bad ones with information loss).

How would we handle e.g. this simple branch with some different refactor attempts: https://github.com/atarijookie/ce-atari/commits/screencast_res

Sorry to complicate this, I'm just curious.

**Comment by mikrosk** [comment]
You mean like re-doing the same merge operation from a branch which contains some additional changes? This shouldn't be a problem as git would try to apply each change again, realising that it's already there and only applying the new stuff.

**Comment by tin-nl** [comment]
@mikrosk: No, just meant as an example of several features/refactors that would become just one commit. I simply would miss the "train of thought" or the path the developer walked w/o having those commits. Didn't you ever miss this information in your experience? I know it's a sensitive topic per se (aka tabs vs spaces), just curious.

@all: Regarding the decision: oh, the pressure :) I think we could try squash if (and only if) all of us are OK with trying it albeit there can be some (probably minor) information loss.

**Comment by mikrosk** [comment]
@tin-nl: honestly, not really. Of course my dev branch(es) are mess, a lot of amends, even history rewrites but as soon as I settle on some final state and send patch to a mailing list (or make a PR), I rarely need to fully understand what steps I took.

I've been thinking that maybe we could actually do this by ourselves -- if I feel this PR's history is complete rubbish, I indicate I'd recommend to squash it, if you feel your PR is actually worthy with its history, indicate just a merge. #73 is an example where I would ironically requested a merge as I have a few separate things going on there.

**Comment by miniupnp** [comment]
I'll go into rebasing/squashing my branches before merging ;)

**Comment by atarijookie** [comment]
Sooo, can we close this? :)

**Comment by tin-nl** [comment]
Yup, @mikrosk proposal to request either merge or squash in the pull request depending on how much the history is "worth" is the way to go, I think.
