### ISSUE TITLE
IKBD isn't initialised correctly by default

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#129]
While trying to solve the strange problem in #73 (fire button doesn't work when implemented true ST keycode handling) I finally found it -- IKBD isn't set in good initial state -- joy1 ignores fire events while joy0 seems to be set in some kind of mouse mode (i.e. when I move joy0, I see mouse cursor moving). If I initialise the IKBD with:

```
while (!(*((volatile uint8_t*)0xfffffc00) & 0x02));
*((volatile uint8_t*)0xfffffc02) = 0x14;
```

i.e. setting joysticks in event reporting mode, my code started miraculously working. Event reporting mode should be set by default (i.e. games have no need to set it, therefore do not work) so I'm wondering where to look for the bug? I don't see any access to IKBD registers except `test_ikbd`.

**Comment by mikrosk** [comment]
Oh s**t, this will be something subtler -- I see there's `resetInternalIkbdVars` which set correct mode and everything and yet it doesn't work.

**Comment by atarijookie** [comment]
This will be in raspberry pi code - ce_main_app/ikbd - there is no ST side of this IKBD emulation.
We should finish the IKBD test on real ST (to fully describe the good behavior), then fix the CosmosEx IKBD emulation. If you find my IKBD code overcomplicated, you could at least help me with finishing that IKBD test, as you're much better in ST programming than me, might be easier for you, and I - on the other hand - know the CE IKDB code better ;)

**Comment by mikrosk** [comment]
Well, at least in this case it seems CE code working, that's the problem. It seems ikbd state is somehow different frpm its initial state found in the st after reset.

**Comment by mikrosk** [comment]
OK, I've got it. All I needed to do was to actually read the log. ;) When booting the ST:

```
00099587        00000072         Ikbd::processStCommands -- got command 80, len: 0, cb contains 2 bytes
00099589        00000002         Ikbd::processStCommands -- not GET cmd, and we don't know what to do
00099591        00000002         Ikbd::processStCommands -- got command 01, len: 0, cb contains 1 bytes
00099592        00000001         Ikbd::processStCommands -- not GET cmd, and we don't know what to do
```

This is a reset command, sir! So CE just stares into the wall, minding its own business instead of sending reset to the IKBD!

**Comment by mikrosk** [comment]
Also, another bug (?): I don't understand how the condition

`ceIkbdMode != CE_IKBDMODE_SOLO`

can return false during the first (sometimes even second) boot but then all the further restarts (resets) returns true. This leads to another bug and that is that we don't send "0xF0" as an OK but see above, I don't think we should send it at all, it's a real mystery to me why the IKBD doesn't answer with 0xF0 by itself.

**Comment by atarijookie** [comment]
You know, those IKBD tests would help us to detect these issues - in injection mode, and in solo mode ;)

**Comment by mikrosk** [comment]
Right now I'd really just want to see my code working. ;) So is it a bug? Should `ceIkbdMode` be `CE_IKBDMODE_INJECT` all the time? If so, we need to fix the test as `CE_IKBDMODE_INJECT` is set only if we receive something from the injector. Isn't possible to detect this programatically somehow?

**Comment by mikrosk** [comment]
(removed previous, misleading, comments)

OK, I'm an idiot. Obviously, I've relied on the docs too much, not realising that the TOS does some changes by itself -- so while the powerup (default) state might be with joystick event reporting on, after setting relative mouse reporting this is no longer the case.

Btw it's interesting that IKBD returns 0xf**1** after the reset/powerup instead of 0xf**0** as mentioned in the docs, meaning "version 1".

However, this issue wasn't a complete waste, there _were_ some subtle bugs in the CE code handling the reset, so I'm going to make it part of #73.

**Comment by mikrosk** [comment]
Just for the record, the IKBD defaults to:
- a mouse position reporting with threshold of 1 unit in either axis
- the Y=0 origin at the top of the screen
- joystick event reporting mode for joystick 1, with both buttons being logically assigned to the mouse
- after any joystick command, the ikbd assumes that joysticks are connected to both Joystick0 and Joystick1
- any mouse command (except MOUSE DISABLE) then causes port 0 to again be scanned as if it were a mouse, and both buttons are logically connected to it.
- if a mouse disable command is received while port 0 is presumed to be a mouse, the button is logically assigned to Joystick1 (until the mouse is reenabled by another mouse command)
