### ISSUE TITLE
CE_DD screenshot functionality causes crashed / weird behavior

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#13]
When the screenshots functionality is enabled in CE_DD, the TOS and currently running app might misbehave - they might either crash, or not react to keyboard, or receive fake key down after each communication with CE in VBL. 

One issue is that it shares the hddIf structure with the rest of CE_DD, this needs some external semaphore / mutex. 

The other issue is that it either corrupts stack, or doesn't return registers correctly, or something. Good ST assembler knowledge is needed for this one. The same as with CE STiNG.

**Comment by tin-nl** [comment]
Shouldn't this be true for screencast too, then?

**Comment by atarijookie** [comment]
Yes, might be true even for screencast... But the screencast was made by you, and I copied parts of it into STiNG and screenshots in CE_DD, so I might have had screwed up a bit ;)

**Comment by tin-nl** [comment]
Added the mutex, fine so far. Have yet to test it with STiNG.
Screencast should be fine, that uses flock as mutex against Harddisk-Drivers, CE_DD etc.

**Comment by tin-nl** [comment]
Tested with ce_sting and litchi, taking several screenshots while downloading ftp://ftp.funet.fi/pub/atari/demo/ :

![screenshot-000 1](https://cloud.githubusercontent.com/assets/18448788/14796564/53345fd4-0b2e-11e6-95a4-0ab8c35c7b3c.png)
![screenshot-001](https://cloud.githubusercontent.com/assets/18448788/14796569/590bc546-0b2e-11e6-9df2-d120add9b1e7.png)
![screenshot-002](https://cloud.githubusercontent.com/assets/18448788/14796571/5cdc22ba-0b2e-11e6-99f6-5f47a2121f29.png)

Looks good to me. Any more tests needed?

**Comment by atarijookie** [comment]
Now that looks nice ;) I'm not sure whether you're asking if the CE_DD + screenshots + mutex is OK this way, or the CE sting is OK this way, but I would say it's an improvement if it seems to work fine. Good job, tIn. Will you merge the ce_dd mutex branch now? :)

**Comment by atarijookie** [comment]
Btw., how did the ce_sting thing go? Any weird behavior? How about the transfer speed? (I guess the transfer speed could be low as the ST apps use too small buffers, and it would be much better if they just used larger ones).

**Comment by tin-nl** [comment]
I do have to test ce_sting thoroughly, yet. I just was so excited that Litchi worked, that I simply had to do some screenshots for proof ;-) 
Well, and there was the not-crashing of said screenshots while ce_sting was doing things, too.

**Comment by miniupnp** [comment]
@tin-nl which version of Litchi are you using ?
