### ISSUE TITLE
Make IKBD TX line pass trough before CE is fully operational

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#132]
I think we've discussed it in some thread but can't find it between issues -- the symptoms are easy to spot, you boot CE and can't even press CTRL+ALT+DEL until you press the reset button for 2nd boot.

**Comment by atarijookie** [comment]
I have this in TODO, but it won't work on older CE without HW modification - you will have to replace one resistor with DS1818 chip to get this functionality. The new CE HW will have this minor tweak done.

**Comment by mikrosk** [comment]
Wouldn't be possible to solve this, at least partially, by running an executable very soon during the boot process? You know, statically linked, just forwarding the packets before any systemd crap is handled. As soon `cosmosex` is about to execute, we kill the binary and start CE.

**Comment by atarijookie** [comment]
tIn had such idea and started to experiment with something similar for the hard drive functionality.
It's a cut down version of ce_main_app, currently handles only Hans, Franz would have to be added from the ce_main_app, but it's a good start :)
[https://github.com/atarijookie/ce-atari/tree/master/ce_preinit](https://github.com/atarijookie/ce-atari/tree/master/ce_preinit)

Btw., how long does it take you to have it working from moment of turning on? On Yocto and old RPi1 it was 15 to 20 seconds, on RPi3 and Raspbian it's like 10 seconds. 

Also - there could be special bootsector for this, which would be stored directly in flash of Hans, so it would boot immediately into some 'Please wait while RPi booting' screen and could do the automatic reset of ST...

**Comment by mikrosk** [comment]
That sounds pretty amazing! For me the boot takes more or less 15 seconds.

**Comment by atarijookie** [comment]
Got code for IKBD pass through in branch, have to test it... If it will work (or gets fixed and then will work), you will have 2 options:
- either replace single resistor to a small 3 pin chip, this will turn on Franz immediately after power on and allow pass through, or...
- work on that pre-init thing, and put it in the linux init process as soon as possible... 

I will test the code for IKBD pass through soon.

**Comment by mikrosk** [comment]
I like the first option more because even if you f**k up everything, you still get a working mouse/keyboard.

Of course, having a fast pre-init in the software as an additional option can't offend anyone.

**Comment by atarijookie** [comment]
Tested on STFM.
- before linux main app start it works immediatelly (if Franz is running)
- after terminating linux main app it takes around 3 seconds to resume pass through again (might annoy people when doing update, but it's still better than before)

So there will be a Franz firmware release soon(ish). Then you need the HW mod or SW preinit.

**Comment by atarijookie** [comment]
> Could you post an example what the pre-init linux app must do to enable Franz?

The only thing to change now is that you don't call the  Utils::franzToResetState() on line 51:
https://github.com/atarijookie/ce-atari/blob/master/ce_preinit/ccorethread.cpp#L51

That would have Franz in running (not reset) state. It still could happen that Franz refuses to start (due to some chip start up issue), and you might need to to reset of Franz after a while, but if you're lucky, then Franz will start on the 1st time... That improvement of reseting Franz if it didn't start could be added later...

**Comment by atarijookie** [comment]
Btw., if I'll add that check-if-Franz-alive-and-reset-if-no thing to pre-init, are you willing to extend the current start up on Yocto and Raspbian by adding this pre-init app? 

That would be:
- adding it to init script, as soon as possible, as this might not need anything at all - no linux partition access, no network access
- adding killing of pre-init app to script, when ce_main_app starts

Later we could extend it by having a ACSI / SCSI boot sector, which would make the ST / TT / Falcon wait for full app to start with some nice message... 

This is not a difficult task, just little bit annoying... Although it might be more annoying to wait for the keyboard / mouse to start working while listening to the hells bells :-D

**Comment by mikrosk** [comment]
> Later we could extend it by having a ACSI / SCSI boot sector, which would make the ST / TT / Falcon wait for full app to start with some nice message...

Wait where exactly? Because if we wait, then we don't need the keyboard, do we. :) Or you mean something like "CE is still booting, don't be surprised that there are no translated drives. Press any key do continue." ?

I'm working on different stuff these days but I'll be back in ~2 weeks at most.

**Comment by atarijookie** [comment]
> Wait where exactly? Because if we wait, then we don't need the keyboard, do we. :)

Yeah, but until it boots (until you wait for it), you aren't able to do much with it anyway, so it's worth waiting. And while you're waiting you won't get the hells bells, and you can do Ctrl+Alt+Del if needed.

> Or you mean something like "CE is still booting, don't be surprised that there are no translated drives. Press any key do continue." ?

Yes, exactly...
