### ISSUE TITLE
IKBD : handle key auto-repeat

### ISSUE THREAD

**Issue by miniupnp** [atarijookie/ce-atari#136]
I noticed that USB keyboard device have autorepeat enable and that  auto-repeat event are forwarded to ST...
I don't know if ST keyboard handle autorepeat...

If autorepeat in ST is handled only by TOS, we could completely skip the autorepeat events.
If ST IKBD does handle autorepeat, I guess it is needed to emulate its configuration
see EVIOCGREP / EVIOCSREP ioctl()

**Comment by mikrosk** [comment]
This is fixed in #73, closing. ;)

**Comment by miniupnp** [comment]
still not merged ?

**Comment by mikrosk** [comment]
No :-/ All in all it's all fixed and pushed but not merge, there's one remaining issue left and that is a burden I've given to myself with no good reason. ;) It's the "swap joy0 and joy1" checkbox, right now it works only for USB joysticks. I want to have it working for keyboard joysticks as well as classic (IKBD) ones. Switchable during any game with,  you guessed it, another key combo.

Right now only the switching itself needs to be done (I mean for IKBD and keys), not much work but a lot of testing needed.
