### ISSUE TITLE
CE_STING routine from VBL causes crashes / misbehaviour

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#14]
When CE STiNG is loaded and there is an open connection (socket) and / or ICMP handler registered, the TOS and currently running app might misbehave - they might either crash, or not react to keyboard, or receive fake key down after each communication with CE in VBL. 

This issue might be harder to spot as when no network app is running, the CE STiNG doesn't do communication with CE in VBL, but this can be turned off in code to make the issue more visible. 

The other issue is that it either corrupts stack, or doesn't return registers correctly, or something. Good ST assembler knowledge is needed for this one. The same as with CE_DD screenshots.

**Comment by atarijookie** [comment]
AFTP - had a crash from time to time, but after one connection to FTP there's this keyboard input issue
Litchi - GXALLOC errory - out of ram - on some directories
IRC.TOS - chat.freenode.net, default port (6667?), ##Atari, seems to work fine
CAB 1.5 - can't open anything, it just opens local dir listing
CE STiNG test PRG - if there is the VBL routine running, the keyboard input issue is frequent

**Comment by tin-nl** [comment]
Hello Jookie,

tried to do some STINg tests with screencast/screenshot yesterday, so your report comes at the right time :)

I hit a small problem though - I can't get network connections to work. It's probably because I stopped using Ataris for day to day work before this thing called "Internet" came along...
Do you have any tips? How do I configure ce_sting? The CPX of the original Sting won't show any dialog boxes - nothing happens, when I open them.
I tried AFTP, AIRC and CAB. Have to try Litchi.
Anything I missed to enable networking?

Cheers,
 tIn.

**Comment by atarijookie** [comment]
>  I can't get network connections to work. How do I configure ce_sting?

There is no configuration. If there will be some, it will be through ce config menu, but no standard config through CPX, ini files and so on is needed.

I guess your problems might be caused by:
- not using yocto / using raspbian - there are some changes when it comes to what can be done without additional permissions (at least for ICMP packets, but maybe for more)
- not using eth0 but using wlan0 instead - there might be some routing issues (on linux level), or there might be something bad in the ce code - like not opening port on both interfaces, but only on one, or something like that

And on what machine are you running? ST, TT, Falcon? AtarIRC (from Lonny Pursell) will not work on ST correctly, as it needs newer AES (part of the TOS), so for IRC I got recommended IRC.TOS client.

What you can do is to run ce main app with log level 3 (ll3), then load ce_sting, try to go something with some network app (ftp, irc) and see what it says in log. You can paste it then here if you won't be able to see the problem directly. 

Jookie

**Comment by atarijookie** [comment]
AFTP crashed on me with VBL enabled (2 bombs), then the keyboard misbehaved. When turned off the VBL, it didn't happen. Maybe I should c&p tIn's mutex from CE_DD and try it with that...

**Comment by atarijookie** [comment]
AFTP: VBL caused crash + keyboard misbehaving, then VBL turned off, download speed: 6.2 kB/s
Litchi: doesn't list the dir content

**Comment by atarijookie** [comment]
Sqward writes in a PM on atari-forum:

> As I suspected, in:
> https://github.com/atarijookie/ce-atari ... ting/vbl.s
> 
> you set SR to $2700 which blocks all the interrupts. This prevents ACIA interrupts from being fired > which causes data overruns (ACIA has no buffer). So you can't do that.

**Comment by atarijookie** [comment]
Sqward writes some more:

> Well, do you have any reason to block other interrupts? I wouldn't block anything at all. Just leave SR unchanged.
> 
> As for the crashes, then it all depends on how robust the ACIA routine in TOS is. When an overrun happens then basically new data arriving from the keyboard replace unread data in ACIA data port. This means that TOS routine could see data that it's not expecting (this is causing your ghost key presses, probably caused by mouse packets). It shouldn't crash, but who knows. Check if that interrupt blocking helps and we'll go from there :)

**Comment by sqward** [comment]
As discussed in PM messages. Your handler shouldn't block any interrupts. ACIA has no FIFO so this is causing keyboard acting weird.

**Comment by atarijookie** [comment]
@tin-nl - do we have a reason for blocking those other interrupts while we're handling VBL?

**Comment by tin-nl** [comment]
AFAIR we did this to have an atomic transfer in case flock isn't considered (unfortunately old Hddriver doesn't check flock and other drivers have this problem, too). We had so many issues with the transfers back then, that this surely was one of those "just in case" things we threw at those problems. Have to check the IRQ priority to see if this is necessary. Interestingly screencast has a quite long transfer (32kB) and doesn't show IKBD problems at all. Have to have a closer look what I did there.

If flock poses a problem, I don't see why ce_sting shouldn't require newer HDD drivers and refuse to start if known offenders are resident.

**Comment by miniupnp** [comment]
@sqward : commit 6ff6614 is removing the interrupt masking

**Comment by tin-nl** [comment]
Double checked all the usual drivers - none of them uses MFP vectors, so removing the sr mask is probably safe. 

I still don't know why this doesn't produce problems with the screencast.
@atarijookie: Does sting remain in VBL longer than screncast does? E.g. has more transfers there?

**Comment by atarijookie** [comment]
> Does sting remain in VBL longer than screncast does? E.g. has more transfers there?

Well, it's hard to say and just compare without real numbers:
- screencast transfers more data - 32 kB + 0.5 kB
- ce_sting reads only 0.5 kB, but then processes the data in that VBL - puts it in the structs, possibly calls ICMP handlers if there are any registered (most of the time there aren't any).
