### ISSUE TITLE
remove unecessary files from git repository

### ISSUE THREAD

**Issue by miniupnp** [atarijookie/ce-atari#145]
ce_main_app/webroot/css/combined.css.gz
ce_main_app/webroot/js/jquery-combined.js.gz
ce_main_app/webroot/js/zepto-combined.js.gz

files are built by makefile. is there a reason to keep them in git repository ?

**Comment by mikrosk** [comment]
yeah, I'd like to know that, too. My very first commit attempt assumed that they are somehow depend on the code I wrote, too so I made them part of my patch. :)

**Comment by miniupnp** [comment]
also what is ce_main_app/webroot/js/log.js.gz ?

**Comment by atarijookie** [comment]
This is a good question on @tin-nl , as web interface is his contribution. My guess is that the generated ones can be deleted, as when doing release, I copy the whole webroot dir to the release, and the generated files are there...

**Comment by tin-nl** [comment]
> files are built by makefile. is there a reason to keep them in git repository ?

Don't think so, probably sth from way back when it wasn't build via makefile. Have to check.

>also what is ce_main_app/webroot/js/log.js.gz ?
 
A JS exception logger.
