### ISSUE TITLE
improve detection of other instances

### ISSUE THREAD

**Issue by miniupnp** [atarijookie/ce-atari#147]
relying on ps has issues
the right way to do it seems to be .pid file +flock
http://stackoverflow.com/questions/25267451/how-to-avoid-to-running-program-twice

**Comment by miniupnp** [comment]
@atarijookie : I think I have found the right way to do it. and very simple :)
I just do not rely on the existence of /var/run/cosmosex.pid but check for the process binary being the same

**Comment by miniupnp** [comment]
@atarijookie do you think I can merge b1dd101e249a2d77c1f5af4b28bf9bf30337ae2c ?

If you still experience problems, we will fix this code (instead of rewritting everything again :)

**Comment by atarijookie** [comment]
Yes, I'm fine with it :)
