### ISSUE TITLE
Add simple SD card driver for noobs

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#149]
Target audience: total noobs, who only can insert a PC formated SD card

This could be added as enhancement to CE_DD, which automatically boots on new devices, the existing state is pre-prepared for this:
- we already have code for accessing ACSI peripherals
- we already hook to Rwabs(), Mediach() and GetBPB() (for Pexec() stuff)
- we don't need to install the SD card driver on the SD card, because it will be part of CE_DD, so PC will get less confused with some binary data on card

More info:
- when ST asks for boot sector, instead of reading the boot sector and passing it to ST (which could fail due to different stucture / bytes  on PC formated SD card), we should fake the boot sector
- it could be turned on by some enable checkbox in CE_CONF, or auto-enable of this driver, when no Atari driver (PPDRIVER, ICD Pro, HDDRIVER) is found on the SD card, to allow automatic access of the card
- there could be some automatic partitioning tool, which doesn't let user specify anything - it would read the TOS version, determine maximum partition size, create a single TOS/DOS compatible partition (which PC would understand)

What I would like to achieve:
- 1st best option - user formats SD card on Windows, doesn't configure anything on CE, the SD is magically usable on ST - could fail, due to large cards now being formatted to FAT32, with one large partition which ST might not be able to handle
- 2nd best option - user inserts blank SD card, turns ST on, it loads CE_DD. User runs MAGIC_SD.TOS from config drive, that detects TOS version, largest possible partition, makes this partition, enables this simple driver for this SD card and partition, and on next ST reset user is able to see that SD card in TOS. Only question which will be displayed: "This will auto-partition the SD card, and you will loose existing data. Are you sure?" The rest will be automatic.

Anyone is free to comment on this one. This is doable, not that difficult, target audience might be small, but might help in the cases of total noobs.

**Comment by miniupnp** [comment]
I would advise total noobs to only use USB Sticks / translated :)

Anyway your idea is great, but that's a lot of work.
The issue is that TOS cannot handle FAT32 anyway, and the PC formated card will be FAT32 (except 1GB or below)

**Comment by atarijookie** [comment]
> I would advise total noobs to only use USB Sticks / translated :)

Yeah, me too, but for some reason people trust / use the SD card more. Plus some software (Notator or something similar) might not like CE_DD, but might work just fine with HDDRIVER. 

> The issue is that TOS cannot handle FAT32 anyway, and the PC formated card will be FAT32 (except 1GB or below)

You're right... So then there's only 2nd best option available, and I can forget about the 1st best option... It's still and option ;) and I agree, although it looks like it's simple, it would be a lot of work. Let's see what I can do in my spare time - I might drop it along the line if it would lead to nowhere or would be too complicated to finish.

**Comment by atarijookie** [comment]
Some notes to MAGIC_SD.TOS / NOOB_SD.TOS (I might repeat something which I already wrote):

1. do INQUIRY scan of ACSI / SCSI bus, detect existing IDs
2. using some special command read the boot sector (without enabling the SD card on ACSI bus)
3. check if the card already contains HDDRIVER / ICD Pro / Ppera boot sector, if so, show extra warning
4. detect if HDDRIVER, ICD Pro or Ppera driver are in RAM, if so, show extra warning
5. detect TOS version, assume maximum partition size, show it to user, with message that this is the easy approach and he should use manual partitioning with better driver to use more space 
6. Let user type 'I will loose data' to accept partitioning of the card :-D
7. if user did enter the magical approval / acceptance phrase, then enable the SD card on ACSI bus - check if SD card is enabled on ACSI / SCSI bus, and if not, assign one of the free IDs to it, and let that SD card ID be higher than CE_DD ID, because CE_DD will be needed for running the SD card
8. turn on the NOOB option of CE_DD, write the TOS/DOS compatible partition
9. do a RESET, let the new partition be used with CE_DD

**Comment by atarijookie** [comment]
HDDRIVER + HDDRUTIL show these limits on partition size:
TOS 1.00 - 1.02 - 256 MB
TOS 1.04 - 3.0x - 512 MB
TOS 4.0x - 1 GB

Tested 250 MB partition with HDDRIVER and TOS 1.02, it worked fine (first it failed as I've set the partition compatibility to TOS 1.04 but was running on TOS 1.02). 

**Another idea:** automatically create AUTO folder on that SD card, install FOLDR100.PRG if TOS version needs it (and possibly other fixes?) 

- as an automatic SD NOOB detection / flag, so it maybe shouldn't be set in CE_CONF, could be 'SD NOOB' string stored in boot sector (master boot record), or on the last sector of the card (if the bs / mbr would be corrupted / altered)
- Hans could also read the BS / MBR on card init. and then if it's SD NOOB even forward reading of bootsector to RPi (to load CE_DD) instead of returning the PC compatible BS to ST
- 'SD NOOB' identifier string would be written to that SD card when this card was initialized using SD_NOOB.PRG
- SD_NOOB.PRG could also detect FAT32 partition type or very large partition, which TOS couldn't handle, and could report that to user, that now it's not usable on ST, so needs repartitioning
- CE_DD on start, when enabling SD NOOB driver, should check for partition size of the SD card, and verify if that size is usable on that TOS version - if not, then show message that the SD NOOB driver won't be used -- to avoid data corruption when using one card between new and old TOS versions (swaping cards between machines)

**Comment by atarijookie** [comment]
FAT32, 3.69 GB (default format of SD):
![fat32_4gb_druhe](https://cloud.githubusercontent.com/assets/18427437/22371508/caa1e904-e497-11e6-9e4b-148811103541.png)

BGM, 250 MB, HDDRIVER, TOS 1.02
![hddriver_bgm_250mb_tos_102](https://cloud.githubusercontent.com/assets/18427437/22365289/e7d4825a-e476-11e6-8516-fff346f55898.png)

For PC there's a Partition entry no. 1 at 0x1BE, 16 bytes length:
https://en.wikipedia.org/wiki/Master_boot_record#PTE

For Atari there's a Partition Header no. 2, at no. 0 and no. 1 are overlapped by PC Partition entry no. 1.

Data found on sector 63 (0x3f) (looks like another boot sector), sector 64 (0x40) (contains bootable code with HDDRIVER string).

1st FAT starts on sector 80 (0x50), 2nd FAT starts on sector 144 (0x90).
Rootdir is on sector 208 (0xd0). First file data is on sector 240 (0xf0). 

PC partition entry says: starting at sector 0x3f, size is 0x77181
Atari partition header says: starting at sector 0x40, size 0x77180

**Comment by atarijookie** [comment]
Getting CE HDIF pointer works (thus storing and retrieving from cookie jar), using it works. 
Fails to get info about SD card...

**Comment by atarijookie** [comment]
- Fix for not sending non-SD card commands to RPi. 
- Fix for not sending correct CS command to CE/CS. PRG renamed to TOS for SD NOOB.

TODO:
- The current version breaks CE_DD Pexec() functionality, as there's some error on sector access code after extending it with SD NOOB. 
- report to RPi, that we got the SD card, so it can generate the SD NOOB partition icon

**Comment by atarijookie** [comment]
SD card read, the status and sense after removing card and reinserting the card.

```
                success  status   SK  SC  ASCQ
good                 01      00
removed              01      02   02  3A  00
inserted, 1st read   01      02   06  28  00
          2nd read   01      00       
```

**Comment by atarijookie** [comment]
TODO: 
- ST freezes or bombs on SD partition access
- make tool to test partition sectors access? (fill sectors with physical sector number, access logical 100th, 1000th, last sector and verify the right physical sector number, also sector read size in rwabs()).
- write many files, verify files
- add FAT read cache

DONE:
- CE_DD do request sense when starting - (can't load MBR after card inserted)
- add request sense / media change to CE_DD SD NOOB
- CE_SDNOB.TOS fails to detect SD NOOB in boot sector (Boot sector content: PC partition)

**Comment by atarijookie** [comment]
```
CE_DD.PRG start
readWriteSector 03 01 00000000 00000001 0001D7B8  E_OK
readWriteSector 03 01 0000003B 00000001 0001D7B8  E_OK
gotSDnoobCard - BPB:
  recsiz: 2000
  clsiz : 0002
  clsizb: 4000
  rdlen : 0002
  fsiz  : 0004
  fatrec: 0005
  datrec: 000B
  numcl : 3FBA
  bflags: 0001

  drive : C
  size  : 00FF MB



CE_DD.PRG end
custom_getbpb SD NOOB
SDnoobRwabs 1 0 0 0 FEreadWriteSector 03 01 000000CB 00000010 00007BC4  E_OK
 E_OK
custom_mediach requestSense 0000
reqSense->MED_NOCHANGE
custom_mediach requestSense 0000
reqSense->MED_NOCHANGE
custom_mediach MED_NOCHANGE
custom_mediach requestSense 0000
reqSense->MED_NOCHANGE
SDnoobRwabs 1 0 0 0 FEreadWriteSector 03 01 000000CB 00000010 000079C4  E_OK
 E_OK
custom_mediach requestSense 0000
reqSense->MED_NOCHANGE
SDnoobRwabs 0 0 0 0 FEreadWriteSector 03 00 000000CB 00000010 000079C4  E_OK
 E_OK
custom_mediach MED_NOCHANGE
custom_mediach MED_NOCHANGE
SDnoobRwabs 0 0 0 0 FEreadWriteSector 03 00 000000CB 00000010 000079C4  E_OK
 E_OK
custom_mediach MED_NOCHANGE
SDnoobRwabs 1 0 0 0 FEreadWriteSector 03 01 0000008B 00000010 000077C4  E_OK
 E_OK
custom_mediach MED_NOCHANGE
SDnoobRwabs 0 0 0 0 FEreadWriteSector 03 00 000000EB 00000010 000r<00>
[ST now shows bombs]
```

Fixed sector count from 1 to variable, now it freezes like this:
```
CE_DD.PRG start
readWriteSector 3 1 00000000 01 0001D7F0  E_OK
readWriteSector 3 1 0000003B 01 0001D7F0  E_OK
gotSDnoobCard - BPB:
  recsiz: 2000
  clsiz : 0002
  clsizb: 4000
  rdlen : 0002
  fsiz  : 0004
  fatrec: 0005
  datrec: 000B
  numcl : 3FBA
  bflags: 0001

  drive : C
  size  : 00FF MB



CE_DD.PRG end
custom_getbpb SD NOOB
SDnoobRwabs 1 0 0 0
readWriteSeÿ
```

**Comment by atarijookie** [comment]
```
Reference on TOS 1.02:

Mapping used sectors image.
Used sector:    0 (0000): 00 00 00 00 00 00 00 00 00 00
Used sector:    1 (0001): 00 00 00 a5 00 00 00 00 00 00
Used sector:   58 (003a): eb 3c 90 4d 53 44 4f 53 35 2e
Used sector:   59 (003b): eb 3c 90 4d 53 44 4f 53 35 2e
Used sector:   75 (004b): f8 ff ff ff 00 00 00 00 00 00
Used sector:  139 (008b): f8 ff ff ff 00 00 00 00 00 00
Used sector:  532479 (81fff): 00 00 00 52 4f 4f 54 30 00 00
Sectors used: 7
Sectors free: 532473

Analyzing boot sector...
PC Partition Entry #1:
status       : 00
1st  C       : 000
1st  H       : 01
1st  S       : 01
part type    : 06
last C       : 3b9
last H       : 08
last S       : 3a
LBA 1st sect : 0000003a
LBA sect cnt : 0007990a sectors (243 MB)

Atari Partition Header #2:
flags        : 01
part type    : BGM
part start   : 0000003b
part size    : 00079909 sectors (243 MB)

PC partition sector 0 (physical sector 0000003a):
jump instruct: eb3c90
oemId        : MSDOS5.0
bytes/sector : 512
sectors/clust: 16
reservedSects: 9
num Of FATs  : 2
root entries : 512
small sectors: 0000
media descr  : f8
sectors/FAT  : 0040
sectors/track: 003a
# of heads   : 0009
hidden sects : 0000003a
large  sects : 00079909
phys driveNo : 80
reserved     : 00
extBootSign  : 29
serial #     : 4a5b7bce
volume label : NO NAME    
filesys type : FAT16   

Atari partition sector 0 (physical sector 0000003b):
bytes/sector : 8192
sects/cluster: 2
reserved sect: 1
n of FATs    : 2
root entries : 512
n of sectors : 31120 (00007990)
media descr  : f8
sectors/FAT  : 4
sectors/track: 58
sides        : 9
hidden sects : 59
```

```
SD NOOB:
Mapping used sectors image.
Used sector:    0 (0000): 00 00 00 53 44 4e 4f 4f 00 00
Used sector:   58 (003a): eb 3c 90 4d 53 44 4f 53 35 2e
Used sector:   59 (003b): 00 00 00 53 44 4e 4f 4f 6c 1f
Sectors used: 3
Sectors free: 532477

Analyzing boot sector...
PC Partition Entry #1:
status       : 00
1st  C       : 000
1st  H       : 01
1st  S       : 01
part type    : 06
last C       : 000
last H       : 00
last S       : 00
LBA 1st sect : 0000003a
LBA sect cnt : 0007f801 sectors (255 MB)

Atari Partition Header #2:
flags        : 01
part type    : BGM
part start   : 0000003b
part size    : 0007f800 sectors (255 MB)

PC partition sector 0 (physical sector 0000003a):
jump instruct: eb3c90
oemId        : MSDOS5.0
bytes/sector : 512
sectors/clust: 16
reservedSects: 9
num Of FATs  : 2
root entries : 512
small sectors: 0000
media descr  : f8
sectors/FAT  : 0040
sectors/track: 003a
# of heads   : 0009
hidden sects : 0000003a
large  sects : 0007f800
phys driveNo : 53
reserved     : 44
extBootSign  : 20
serial #     : 424f4f4e
volume label :     
filesys type : FAT16   

Atari partition sector 0 (physical sector 0000003b):
bytes/sector : 8192
sects/cluster: 2
reserved sect: 1
n of FATs    : 2
root entries : 512
n of sectors : 32640 (00007f80)
media descr  : f8
sectors/FAT  : 4
sectors/track: 58
sides        : 9
hidden sects : 59
```

```
Reference on TOS 1.04:
Analyzing boot sector...
PC Partition Entry #1:
status       : 00
1st  C       : 000
1st  H       : 01
1st  S       : 01
part type    : 06
last C       : 3b9
last H       : 08
last S       : 3a
LBA 1st sect : 0000003a
LBA sect cnt : 0007990a sectors (243 MB)

Atari Partition Header #2:
flags        : 01
part type    : BGM
part start   : 0000003b
part size    : 00079909 sectors (243 MB)

PC partition sector 0 (physical sector 0000003a):
jump instruct: eb3c90
oemId        : MSDOS5.0
bytes/sector : 512
sectors/clust: 16
reservedSects: 9
num Of FATs  : 2
root entries : 512
small sectors: 0000
media descr  : f8
sectors/FAT  : 0080
sectors/track: 003a
# of heads   : 0009
hidden sects : 0000003a
large  sects : 00079909
phys driveNo : 80
reserved     : 00
extBootSign  : 29
serial #     : 4a5c584a
volume label : NO NAME    
filesys type : FAT16   

Atari partition sector 0 (physical sector 0000003b):
bytes/sector : 4096
sects/cluster: 2
reserved sect: 1
n of FATs    : 2
root entries : 512
n of sectors : 62241 (0000f321)
media descr  : f8
sectors/FAT  : 16
sectors/track: 58
sides        : 9
hidden sects : 59
```

```
Reference on TOS 1.06:
Analyzing boot sector...
PC Partition Entry #1:
status       : 00
1st  C       : 000
1st  H       : 01
1st  S       : 01
part type    : 06
last C       : 3b9
last H       : 08
last S       : 3a
LBA 1st sect : 0000003a
LBA sect cnt : 0007990a sectors (243 MB)

Atari Partition Header #2:
flags        : 01
part type    : BGM
part start   : 0000003b
part size    : 00079909 sectors (243 MB)

PC partition sector 0 (physical sector 0000003a):
jump instruct: eb3c90
oemId        : MSDOS5.0
bytes/sector : 512
sectors/clust: 16
reservedSects: 9
num Of FATs  : 2
root entries : 512
small sectors: 0000
media descr  : f8
sectors/FAT  : 0080
sectors/track: 003a
# of heads   : 0009
hidden sects : 0000003a
large  sects : 00079909
phys driveNo : 80
reserved     : 00
extBootSign  : 29
serial #     : 4a5c6306
volume label : NO NAME    
filesys type : FAT16   

Atari partition sector 0 (physical sector 0000003b):
bytes/sector : 4096
sects/cluster: 2
reserved sect: 1
n of FATs    : 2
root entries : 512
n of sectors : 62241 (0000f321)
media descr  : f8
sectors/FAT  : 16
sectors/track: 58
sides        : 9
hidden sects : 59
```

```
BPB on TOS 1.02:
  recsiz: 2000
  clsiz : 0002
  clsizb: 4000
  rdlen : 0002
  fsiz  : 0004
  fatrec: 0005
  datrec: 000B
  numcl : 3CC2
  bflags: 0001

BPB on TOS 1.04:
  recsiz: 1000
  clsiz : 0002
  clsizb: 2000
  rdlen : 0004
  fsiz  : 0010
  fatrec: 0011
  datrec: 0025
  numcl : 797E
  bflags: 0001

BPB on TOS 1.06:
  recsiz: 1000
  clsiz : 0002
  clsizb: 2000
  rdlen : 0004
  fsiz  : 0010
  fatrec: 0011
  datrec: 0025
  numcl : 797E
  bflags: 0001
```


- the params look the same on TOS 1.04 and 1.06
- what is sector 1?
- fix last CHS value

**Comment by atarijookie** [comment]
OSFMount:
- when mounting whole image, Win7 doesn't recognize anything... 
- when mounting just parition, Win7 seems to play nice with it


Reference + 250 MB partition + TOS 1.02:
- writes and reads good on ST
- shows as 127 MB on Win7, doesn't show files :(
- 120 MB partition is shown as 64 MB partition on Win7, still empty
- when TOS 1.02 is trying to access TOS 1.04 partition, it fails to do so (store on which TOS version this SD NOOB was created?)


Reference + 250 MB partition + TOS 1.04:
- write, read, verify good under TOS
- shows good size on Win 7, data copied to PC drive, rewritten with other data, copied back, verified good under TOS

**Comment by atarijookie** [comment]
```
Formated under Win7, as removable hdd:
Mapping used sectors image.
Used sector:    0 (0000): eb 3c 90 4d 53 44 4f 53 35 2e
Used sector:    4 (0004): f8 ff ff ff 00 00 00 00 00 00
Used sector:  254 (00fe): f8 ff ff ff 00 00 00 00 00 00
Used sector:  504 (01f8): 4d 53 44 4f 53 46 41 54 20 20
Sectors used: 4
Sectors free: 511996
Done.

analyze super floppy (single partition, no MBR)
PC partition sector 0 (physical sector 00000000):
jump instruct: eb3c90
oemId        : MSDOS5.0
bytes/sector : 512
sectors/clust: 8
reservedSects: 4
num Of FATs  : 2
root entries : 512
small sectors: 0000
media descr  : f8
sectors/FAT  : 00fa
sectors/track: 003f
# of heads   : 0080
hidden sects : 00000001
large  sects : 0007d000
phys driveNo : 80
reserved     : 00
extBootSign  : 29
serial #     : e2cdfd60
volume label : NO NAME    
filesys type : FAT16   
```

**Comment by atarijookie** [comment]
- partition with SD NOOB, use under Win
- partition with SD NOOB, use under TOS
- compare if they write FAT and dir entries to same sectors (and fix)
- test data transfer between them
- if nothing goes well, there could be a test with fixed values (e.g. physical & logical sector size 512 B), see if it works....

Partition should be created fine. 
Configuration and BPB in CE_DD is probably wrong. 

- add some marker for which TOS version it was done, so it won't be used on older TOS to avoid data corruption / crashes

**Comment by atarijookie** [comment]
```
CE_DD.PRG start
readWriteSector 3 1 00000000 01 0001D9E0  E_OK
gotSDnoobCard() - part sector start: 0000, count: 0007F800
gotSDnoobCard - BPB:
  recsiz: 2000
  clsiz : 0002
  clsizb: 4000
  rdlen : 0002
  fsiz  : 0004
  fatrec: 0005
  datrec: 000B
  numcl : 3FBA
  bflags: 0001

  drive : C
  size  : 00FF MB

CE_DD.PRG end
custom_getbpb SD NOOB
SDnoobRwabs r/w:1 noRet:0 noTra:0 logStart:0009 logCount:0001 midBuf:0
part start: 00000000, ps/as: 00000010
phy start : 00000090, count: 00000010
readWriteSector 3 1 00000090 10 00007BC4  E_OK
SDnoobRwabs - E_OK
```

on TOS 1.02:
- when physical sectors / atari sector is 16, the 1st RW operation freezes the ST
- creating dir goes like this:
SDnoobRwabs r/w:0 noRet:0 noTra:0 logStart:0009 logCount:0001 midBuf:0 (root dir)
SDnoobRwabs r/w:1 noRet:0 noTra:0 logStart:0005 logCount:0001 midBuf:0 (fat 2?)
SDnoobRwabs r/w:1 noRet:0 noTra:0 logStart:000C logCount:0001 midBuf:0 (dir entry?)
...and crashes with 4 bombs...

TODO:
- do simple RAM disk, let TOS work with it under different BPB settings, dump it and reverse engineer it
- look at BIOS (p. 51) / TOS sources for what's happening there

**Comment by atarijookie** [comment]
I thought that only SD NOOB has issue with writing more than 2MB to file, but the reference driver also fails with that on TOS 2.06

**Comment by atarijookie** [comment]
Closing, when someone will work on this later, he can reopen it :)
