### ISSUE TITLE
USB drive doesn't get attached on Raspbian

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#153]
Steps to reproduce: 
1. use Raspbian (might happen on Yocto, but not tested)
2. set some ACSI ID to RAW (might happen in translated mode, but not tested)
3. plug in USB drive
4. do bus scan in HDDRIVER, the RAW drive doesn't appear

Happens with latest git revision. 
4ec3dce26f01e271f19cdbbe41de02a18c0f570d -- last commit before 'Less polling' commit - works OK
release_2017-01-03 -- works OK

So I guess this was introduced with the 'less polling' commit, or later. The problem is either in devFinder or in periodicThread, I guess it is related to last refactoring of the sources... @miniupnp ? :)

**Comment by atarijookie** [comment]
notes:

- devFinder() doesn't get called when USB drive is removed and reinserted

- the new DISK_LINKS_PATH doesn't contain the USB drive:

```
// previous DISK_LINKS_PATH, now commented out
raspDevl # ls -l /dev/disk/by-id
total 0
lrwxrwxrwx 1 root root 13 Jan 24 05:17 mmc-00000_0x125bc7e5 -> ../../mmcblk0
lrwxrwxrwx 1 root root 15 Jan 24 05:17 mmc-00000_0x125bc7e5-part1 -> ../../mmcblk0p1
lrwxrwxrwx 1 root root 15 Jan 24 05:17 mmc-00000_0x125bc7e5-part2 -> ../../mmcblk0p2
lrwxrwxrwx 1 root root  9 Jan 26 03:23 usb-Corsair_Flash_Voyager_A198000000000230-0:0 -> ../../sda

// current DISK_LINKS_PATH
raspDevl # ls -l /dev/disk/by-uuid
total 0
lrwxrwxrwx 1 root root 15 Jan 24 05:17 202638e1-4ce4-45df-9a00-ad725c2537bb -> ../../mmcblk0p2
lrwxrwxrwx 1 root root 15 Jan 24 05:17 22E0-C711 -> ../../mmcblk0p1
raspDevl #
```

**Comment by miniupnp** [comment]
OK I think I understand the issue. I had the Translated disk in mind when rewriting this.
I will update to make sure "unformatted" (from Linux point of view) disks are inserted

**Comment by miniupnp** [comment]
@atarijookie : does my issue_153 branch fixes it ?

**Comment by atarijookie** [comment]
Yes, it seems that now it's able to find the RAW device and attach it :+1:  The remaining thing now is:
// TODO : update wd when configuration is changed

**Comment by miniupnp** [comment]
yes, I need to make a better  wait for conf to notify the relevant threads that something is changed

**Comment by atarijookie** [comment]
Thank you for your fix :+1:  :)
