### ISSUE TITLE
Move the manual to the wiki

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#154]
We have a [pretty sweet wiki](https://github.com/atarijookie/ce-atari/wiki) here and some things are even there already. I think it's a good idea to move every document there and not to keep it on joo.kie.sk -- in this way users would be free to edit / contribute with fixes, clarifications etc (you don't need to know a thing about git, just press the pencil edit button and you're set).

**Comment by atarijookie** [comment]
Sure, you can c&p the documentation here from my page... 

Most people don't know that this github space exists for this project, so I would have to (re)direct them here in case of need.

**Comment by mikrosk** [comment]
If your website says: for all documentation click here, everybody will be aware. ;)

**Comment by atarijookie** [comment]
Closing, when someone will work on this later, he can reopen it :)
