### ISSUE TITLE
Regresson regarding vdevs

### ISSUE THREAD

**Issue by tin-nl** [atarijookie/ce-atari#158]
Just noticed that there seems to be a newly introduced problem that breaks the vdevs used by the webserver. The remote control doesn't work anymore, 

ikbdlog sais:
```
00895343        00000001         ikbdThreadCode will enter loop...
00895344        00000001         Got device (/tmp/vdev/mouse): /tmp/vdev/mouse
00895345        00000001         Ikbd::grabExclusiveAccess() ioctl failed :
00895345        00000000         Got device (/tmp/vdev/keyboard): /tmp/vdev/kbd
00895346        00000001         Ikbd::grabExclusiveAccess() ioctl failed :

```

A build from 24.01. works as expected.

**Comment by atarijookie** [comment]
This is probably due to the less polling refactoring...

**Comment by miniupnp** [comment]
> A build from 24.01. works as expected.

that is strange because the "less polling" refactoring took place before... ( Mon Jan 23 09:38:34 2017 +0100)
Which commit does work as expected ?

**Comment by miniupnp** [comment]
grabExclusiveAccess() should not be called on vdev's but that shouldn't cause any issue...

**Comment by miniupnp** [comment]
@tin-nl can you try again with full log enabled ?
As the IKBD injector is not installed on my ST, I cannot test properly 
But I see some stuff : 
```
2400017 00000088 (2017-01-30 21:33:29.216648)  Webserver dispatch ApiV1Router
02400017 00000000 (2017-01-30 21:33:29.217146)  write mouse X
02400018 00000001 (2017-01-30 21:33:29.217482)  write mouse X done
02400018 00000000 (2017-01-30 21:33:29.217734)  write mouse Y
02400018 00000000 (2017-01-30 21:33:29.217980)  write mouse Y done
```

**Comment by miniupnp** [comment]
I think I have spotted a problem. the write are not checked in virtualmouseservice.cpp
```
03962159 00000001 (2017-01-30 21:59:44.597737)  Webserver dispatch ApiV1Router mouse
03962160 00000001 (2017-01-30 21:59:44.598440)  write mouse X
03962160 00000000 (2017-01-30 21:59:44.599120)  write mouse X done res=16
03962162 00000002 (2017-01-30 21:59:44.600641)  write mouse Y
03962162 00000000 (2017-01-30 21:59:44.601151)  write mouse Y done res=16
03962163 00000001 (2017-01-30 21:59:44.601579)  ikbdThreadCode() read(10) returned 0 (EOF) closing 4
```

**Comment by miniupnp** [comment]
OK, it is because the fifo are continiously open/close in virtualmouseservice.cpp
so linux send EOF to the ikbd code...

**Comment by miniupnp** [comment]
the solution is to keep the fifo open
