### ISSUE TITLE
Support for MIDI softsynth

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#159]
Just an idea: https://www.facebook.com/groups/133161394213/permalink/10155096700679214/

Basically you can play the cool music from Sierra (and others: http://www.atarimania.com/list_games_atari-st-midi_midi_1_S_G.html) games via MIDI, using a cheap USB->MIDI adaptor. Of course, you'd need to connect RPI's AUDIO OUT to speakers.

**Comment by miniupnp** [comment]
you need something like this https://www.thomann.de/fr/thomann_midi_usb_1x1.htm right ?

**Comment by mikrosk** [comment]
Exactly.

**Comment by miniupnp** [comment]
I don't see that as a base CosmosEx feature, more an additional feature because it needs additional Hardware.
In my opinion, that should be a wikipage / how to setup this and jookie could then advertise this "optional feature" :)

**Comment by mikrosk** [comment]
Of course it's not something vital to CE as such but it would certainly help to boost sales. Just an idea.

**Comment by miniupnp** [comment]
so who's able to write that "how to" on the wiki ? ;)

**Comment by mikrosk** [comment]
As soon as I force myself to try it out on the RPi I will. :) Right now I have it working only on my desktop but there was literally zero work needed, just installing the right apps/libs.

**Comment by atarijookie** [comment]
Closing, when someone will work on this later, he can reopen it :)
