### ISSUE TITLE
CE main app IKBD emulation needs some fixing

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#16]
There have been a report on USB keyboard / USB mouse misbehaving in some game, I can't find the topic on atari-forum right now. 

It would help with the fixing to:
1) create a 'unit' test for IKDB mouse / joy / keyboard (like with TST_FSYS.PRG and TST_STNG.PRG) to learn, describe and automatically validate behavior of IKDB commands
2) fix everything with CE using that test

The filesystem test and Sting test showed that many issues can be easily found if the tests are present, and the result will be closer to emulating original behavior than what it was (is) when I just code blindly according to my understanding of the documentation. There will be surely many issues with IKBD.

**Comment by tin-nl** [comment]
As you mentioned in #7, this would be usefull to find edge cases and/or questionable hardware. How would you go about this? At some point this integration test needs to inject Keycodes via ST keyboard. The only way I can think of doing this w/o CEs involvement (which is under test after all) and aside from user pressing keys would be an 6800 IKBD programm. We do only have 128 bytes there, but it might be enough for sending and echoing test codes. Again, this is 25 years since I last dabbled with IKBD programs on IKBD itself, but AFAIR this should be possible.

**Comment by atarijookie** [comment]
> How would you go about this?

Depends on what we would test:
- tests like reset, get mouse position, and so on can be handled without anything other from ST code directly
- tests for mouse, joystick, keyboard would require the user to type / move stuff, and I would be fine with that, as this doesn't need to be fool proof test for anyone, just for fixing stuff - e.g. it would configure absolute mouse reporting, show on screen message 'Move the mouse to upper left corner and press enter' and then wait for the key and read the data from IKDB
- any other test cases? I don't know which, but some might arise. 

I wouldn't screw around with programming the IKDB itself.

**Comment by tin-nl** [comment]
I'm not sure if we get enough edge cases w/o an IKBD client program. But you are right, for a first, basic tests the above would be the easiest to implement. I see if I can cough up a little console-based framework where w can more tests easily.

**Comment by atarijookie** [comment]
>  I see if I can cough up a little console-based framework where w can more tests easily.

That would help me a lot, as I remember last time I did something with IKBD it required some asm, in which I'm not good ;) With a minimal framework, which would hook itself to IKBD stuff and forward everything to some C function, which would then handle the rest, I could easily fill the test cases...

**Comment by atarijookie** [comment]
@tin-nl , did you start making that IKBD test app? Because if not, I could start that today - I just want to avoid doing something which you already did or already started.

**Comment by tin-nl** [comment]
I did, just didn't came around pushing it yesterday.

**Comment by atarijookie** [comment]
Holy cow, that's awesome ;) Let me add some tests there ;)

**Comment by tin-nl** [comment]
Finally came around to push this.
A) a test lives in /tests and consists of the usual init/run/teardown functions
B) tests have to be added to main.c
C) I've only added simple examples, didn't have time to add the mouse example (hence this test failed as it's not implemented)
D) I've included alle the ACSI/SCSI stuff, we might need this to check back with the PI for some tests

Hope this is somewhere in the ballpark of helpfull.

**Comment by atarijookie** [comment]
Holy cow, this is much more code than I thought! :) Great job, tIn, thanks.
I will check it out in detail and extend it during the work days, as my time during weekend is limited. Then I'll report on the progress.

**Comment by tin-nl** [comment]
It's not that much code as it seems - many things are copyied from acsi test (I guess we need most of it) :) I'll happily clean up unused parts later, so you can just focus on the tests.

Btw: at some point i the future we should move this boilerplate code that we copy/pasted around either into a lib or at least in a directory where the PRG makefiles can pick what they need...

**Comment by atarijookie** [comment]
> I'll happily clean up unused parts later, so you can just focus on the tests.

Naah, screw it, I'll figure it out and maybe even clean it myself later :)

> we should move this boilerplate code that we copy/pasted around either into a lib or at least in a directory

Aaah, that merging, reusing, then branching because the lib / merged version can't do something and we don't want to break the rest :-D At least the ACSI / SCSI part could be later done through the (future) CE_DD API, I'm not sure about the rest - if it's so reusable.

**Comment by tin-nl** [comment]
> At least the ACSI / SCSI part 

 that's the idea, only things like device discovery, ACSI/SCSI transfers, Cookie, XBRA, the real standard stuff.

> could be later done through the (future) CE_DD API, I'm not sure about the rest - if it's so reusable.

 I don't think that we should set CE_DD as a requirement for the test or the screencast, sting etc. It's better if those can be used indepently. I guess that those routines don't take much memory after all.

**Comment by mikrosk** [comment]
Are you aware of some IKBD bugs? If not, I propose close.

**Comment by atarijookie** [comment]
No, not at this moment, not that you didn't fix ;) So le'ts close this one, and we'll open a new one if something arises.
