### ISSUE TITLE
Merge in the BeePi project

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#164]
Just when you though I can't come up with dumber idea than #159, I present you another one: merging the cool looking ARAnyM/FreeMiNT based distro: https://sites.google.com/site/emaappsarch/news/beekeyandbeepibeta9areavailable with Raspbian. That way you would have two Ataris -- one ST/E/Falcon and one Aranym-based TOS clone in super resolution etc. Both sharing Atari keyboard, mouse, partitions, usb devices, network etc.

This kind of stuff could upgrade the CE to something completely else and I personally like it much more than "let's make a video decoder for the ST with decoding done on the Pi".

**Comment by mikrosk** [comment]
Obvious problems are video output (Atari vs. native RPi) and (de)activating the distro as soon as you start working in TOS. Funny thing is that the BeePi uses Hatari for games/demos, imagine the option to make it running on the real ST instead. :)

**Comment by mikrosk** [comment]
Btw, imagine the long awaited #46, executed from environment like this -- cool colours, resolution, desktop and still an Atari app! :)

**Comment by atarijookie** [comment]
Closing, when someone will work on this later, he can reopen it :)
