### ISSUE TITLE
Get rid of the update app

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#165]
We have the debian package manager so why on earth are we not using it? Jookie could easily setup a repository and the CE_MAIN would just call... apt-get update && apt-get upgrade.

Not to mention you can roll back and all sorts of crazy stuff.

**Comment by mikrosk** [comment]
Of course, this somehow renders my "zero tweaking" idea obsolete: https://github.com/atarijookie/ce-atari/issues/65#issuecomment-231578820

**Comment by atarijookie** [comment]
apt-get, dpkg don't work on Yocto, so for backward compatibility we still need to keep the current way of doing it, at least for Yocto.

**Comment by mikrosk** [comment]
"Forget Yocto, now we have Raspbian for development, focus on that" are more or less your words. :) So Yocto can have its old unreliable update process but no reason why Raspbian has to follow it.

**Comment by atarijookie** [comment]
Yeah, that was about being limited with Yocto tools, when doing nice new features, like video player :) 

The other thing is, that the update process also does update chips, which still would have to be added somehow to debian package update.

**Comment by mikrosk** [comment]
`dpkg` is pretty flexible, you can hook building of the kernel on it so updating some chips can't pose a problem. It's even desired, if new firmware screws up something, it's super easy to roll back to previous revision. If there are dependencies between different packages (firmware, ce_main), you can specify that as well.

**Comment by atarijookie** [comment]
Closing, when someone will work on this later, he can reopen it :)
