### ISSUE TITLE
Priority handling for the shared drive via eth0/wlan0 

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#167]
Just today I've noticed that if I have both wlan and ethernet connected, when opening the shared drive wlan0 is also active (transmitting packets, blocking opening...). I guess there should be some mechanism which would prefer wired connections over wireless.

**Comment by miniupnp** [comment]
yes, default route...

**Comment by mikrosk** [comment]
yep, why not, seems like the simplest approach.

**Comment by miniupnp** [comment]
are you using DHCP on both interfaces ?

**Comment by mikrosk** [comment]
Yes, same router.

**Comment by miniupnp** [comment]
so it all depends how the DHCP client set the route and which interface is up first

**Comment by miniupnp** [comment]
@mikrosk I wouldn't label this as "bug". This is standard OS functionning...

**Comment by mikrosk** [comment]
Ftom developer's point of vjew, yes but imagine a poor user who bas no idea what route table means. Certainly CE can help out here, making default routes more user friendly?

**Comment by miniupnp** [comment]
that is an average user point of view : connect any computer to a LAN with both wired and wireless ethernet and you've got no other way of choosing which one to use than disabling one of the interface !
That's exactly the same with CE, I don't know why you would complicate things with a priority handling that only network admin would understand

**Comment by miniupnp** [comment]
In any case, I just can't understand why you've labeled this as a bug.
If that is a feature that you want, that is an enhancement

**Comment by mikrosk** [comment]
Maybe we don't understand each other. On my PC, regardless of Windows or Linux, when I connect Ethernet cable, this connection is used (unless I do some explicit changes). All I'm asking is to do the same in CE.

**Comment by miniupnp** [comment]
@mikrosk you are lucky with your windows, because it is not what all user experience... just google a bit and you'll see...
About linux, il all depend on how the DHCP client sets the interface and the route. So find a way to have this working with raspbian

**Comment by mikrosk** [comment]
Interesting, I'm pretty used to this feature, never really experienced anything else. ;-)

Anyway, I agree, if there's a way to do this via a DHCP settings, let's do it, if it's too hard or hacky, we can leave it as is.

**Comment by atarijookie** [comment]
I won't work on this one and nobody else seems to work on it, too, so closing this for now... Once someone wants to add this feature, he or she can reopen the task, assign it to himself / herself and proceed...
