### ISSUE TITLE
CEPI cookie installed twice

### ISSUE THREAD

**Issue by blind** [atarijookie/ce-atari#168]
Using the latest release version, there is two instances of the CEPI cookie in the cookie jar, both with the same value.

**Comment by miniupnp** [comment]
@blind what's your TOS version ?

**Comment by blind** [comment]
I'm running the Swedish version of TOS 2.06 on a 4MB STe.
I used SysInfo to view the cookie jar and noted that the CEPI cookie existed twice, next to each other.

(I should have added this info from the start, sorry about that)

**Comment by blind** [comment]
I took a look at the code and it's a pretty obvious bug. 

This line:
https://github.com/atarijookie/ce-atari/blob/63da5f06cdfc1332d3e6087b27c45ec27eba231c/ce_dd_prg/main.c#L687

should be inside the scope above.

**Comment by miniupnp** [comment]
youre right :)

**Comment by Biker1bob** [comment]
So I noticed this exact same thing. If I do not load through AUTO and load CE_DD after the fact then I only get it once. Is there a fix for this? I am running the latest version of the comos software, I am also on 2.06 with MegaSTE.

**Comment by atarijookie** [comment]
Closing as this is resolved.

**Comment by Biker1bob** [comment]
You say closed because it was resolved. I have the latest version of the firmwares and it still does this now.

**Comment by atarijookie** [comment]
2018-05-10 on Raspbian Stretch? 
Or you have this version on Raspian Jessie? Don't you have boot issues like other users? :)

**Comment by Biker1bob** [comment]
Does Raspbian get updated by the firmware check? if not I have never updated the Raspian, why would I if it boots and works. I have no issues booting.. just if I dont load the way I describe by loading the CE drivers as an autostart program I get 2 cepi cookies when I look in SYSINFO.

**Comment by atarijookie** [comment]
> if not I have never updated the Raspian

And if you never updated it, you still will see CEPI cookie twice, because it's fixed in the latest version, not the old one which you are running...

**Comment by Biker1bob** [comment]
If I never updated Raspian? how do I do that? All the software that is updated with the firmware check is now up to date.. I noticed there was a new Main program when I checked the other night. Is this what you are refering to? or is there a proceedure to update the raspian on the Cosmos?

**Comment by atarijookie** [comment]
> All the software that is updated with the firmware check is now up to date..

Okay, that should be enough... Are you booting the CE_DD driver from CosmosEx device directly, or did you copy it to floppy / SD card / other hard drive and boot it from there?
