### ISSUE TITLE
K400 keyboard doesn't work with new app

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#170]
User reported:
- has K400 wireless keyboard
- has 2 devices, one with older and one with newest firmware
- the K400 doesn't work with newest FW, works on the older FW
- the touchpad on K400 works on both versions
- the older FW is: MainApp 2016-05-01, Franz: 2016-01-17

**Comment by miniupnp** [comment]
K400 is a Logitech keyboard right ?
I guess we need some more information, like logs...

**Comment by atarijookie** [comment]
It looks like the keyboard part of the wireless keyboard+touchpad doesn't appear in the /dev/input... Maybe it was ok on Yocto and acts like this on Raspbian...

00182628 00000001 (2017-08-15 01:55:51.988535)	ce ikbd thread created
00182632 00000002 (2017-08-15 01:55:51.992397)	Ikbd::processFoundDev(platform-3f980000.usb-usb-0:1.3:1.2-event-mouse, /dev/input/event0)
00182633 00000001 (2017-08-15 01:55:51.993823)	Ikbd::processFoundDev(/tmp/vdev/mouse, /tmp/vdev/mouse)
00182634 00000000 (2017-08-15 01:55:51.994673)	Ikbd::processFoundDev(/tmp/vdev/kbd, /tmp/vdev/kbd)


00182633	00000003	 Got device (mouse): /dev/input/event0
00182634	00000001	 Got device (/tmp/vdev/mouse): /tmp/vdev/mouse
00182634	00000000	 Got device (/tmp/vdev/keyboard): /tmp/vdev/kbd


raspDevl # ls -l /dev/input/by-path/
lrwxrwxrwx 1 root root 9 Jun 13 22:17 platform-3f980000.usb-usb-0:1.3:1.2-event-mouse -> ../event0
lrwxrwxrwx 1 root root 9 Jun 13 22:17 platform-3f980000.usb-usb-0:1.3:1.2-mouse -> ../mouse0

raspDevl # ls -l /dev/input/by-id/
lrwxrwxrwx 1 root root 9 Jun 13 22:17 usb-Logitech_USB_Receiver-if02-event-mouse -> ../event0
lrwxrwxrwx 1 root root 9 Jun 13 22:17 usb-Logitech_USB_Receiver-if02-mouse -> ../mouse0

**Comment by atarijookie** [comment]
The device now appears only as mouse device instead of mouse+keyboard devices. Added a quick fix - if mouse handler doesn't handle the pressed key (not mouse left or right button), then let the keyboard handler handle it.

Nicer fix (for possible future issues solving) would be: extend both keyboard and mouse handler to return true/false when they do handle / don't handle current event, and if they didn't handle it, let the other handler handle it (e.g. if not handled by mouse handler, let keyboard handler handle it, and vice versa).
