### ISSUE TITLE
New distro vs older distros support

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#175]
Hello all, 

maybe you've noticed, but new Raspberry Pi 3 B+ has been announced:
https://hackaday.com/2018/03/14/raspberry-pi-gets-faster-cpu-and-better-networking-in-the-new-model-3-b/

That means that we will possibly need to start using newer (newest) Raspbian, if we want to support that. As previously, I would like to stick to the older RPIs and older distro, but the situation might end up like it did previously - the older RPis might get unavailable, so we might be forced to start using the newer ones (for newer devices) anyway. 

I assume that the binary for our current Raspbian won't just work straight away with the new Raspbian, and I hope the new Raspbian won't have drastic changes like the current Raspbian vs Yocto had (e.g. network config). 

So I'm thinking about doing support / new releases only for the last (newest) Raspbian, so I could forget about recompiling, testing, fixing on Yocto and then on older Raspbian... (== having only 1 distro instead of 3). 

Build could be probably done for all of those 3 with some cross-compiling (I never did this for main app), but still testing and fixing and handling different behavior would be needed... 

What do you think? @miniupnp @mikrosk

**Comment by miniupnp** [comment]
I've ordered a Nano PI a64 http://www.friendlyarm.com/index.php?route=product/product&path=69&product_id=159
When I receive it, I will try to compile on it :) I think it is Ubuntu-core.

Indeed for the end users you should stick to a limited number of linux distributions.
I don't really know which version of raspbian is used on the current CosmosEx devices...
But I think binary compatibility is maintained between raspbian versions. Only if they dumped the glibc version too much we could have issues. For other libs it should be ok
So I guess you can do your build on the latest raspbian, and we'll test the binary on the old one, we have 90% chance it works right away.

**Comment by miniupnp** [comment]
about the cross compilation,I think it is already  done on travis-ci ;)
```
$ sudo apt-get install build-essential g++-arm-linux-gnueabihf
$ wget http://www.airspayce.com/mikem/bcm2835/bcm2835-1.50.tar.gz && tar xzf bcm2835-1.50.tar.gz && cd bcm2835-1.50 && CC=arm-linux-gnueabihf-gcc ./configure --prefix=/usr/arm-linux-gnueabihf --host=arm-linux-gnueabihf && make && sudo make install && cd ..'
$ wget https://curl.haxx.se/download/curl-7.52.1.tar.bz2 && tar xjf curl-7.52.1.tar.bz2 && cd curl-7.52.1 && CC=arm-linux-gnueabihf-gcc ./configure --prefix=/usr/arm-linux-gnueabihf --host=arm-linux-gnueabihf --disable-shared --disable-manual && make && sudo make install && cd .. 
```

then to build : 
`$ make ce_main_app CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ DISTRO=raspbian`
But I think I never tested the resulting binaries ;)

**Comment by atarijookie** [comment]
> But I think binary compatibility is maintained between raspbian versions. Only if they dumped the glibc version too much we could have issues. For other libs it should be ok
So I guess you can do your build on the latest raspbian, and we'll test the binary on the old one, we have 90% chance it works right away.

I've just run Raspbian Stretch (2018) on RPi 3 B+ (2018), while the binary was built Raspbian Jessie (2016), and it started and seemed to work, but I still need to test more things so see if anything was broken, or just working fine... 

@miniupnp Do you have any recommendations what should I try to find out if we have Jessie vs Stretch issues or binary compatibility? E.g. USB hotplug of devices, mounting network drive, ...?

Things I still need to do:
- auto-start of app on Stretch
- test ACSI / SCSI reliability on RPi 3B+ and Stretch (there were issues on RPi 3 and Jessie due to variable RPi 3 core freq)
- test IKDB injection, if linux console or anything is interfering with RPI serial port or not
- xilinx and STM32 burning with current flash_* binaries

**Comment by atarijookie** [comment]
- auto-start - done
- ACSI / SCSI / IKDB reliability - done
- flash_stm32 and flash_xilinx - done...

More to do:
- build and test on yocto
- create update package

**Comment by atarijookie** [comment]
- update containing yocto, raspbian jessie and raspbian stretch created
- new raspbian stretch image uploaded on web
