### ISSUE TITLE
multiple floppy image lists support

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#177]
here's the list of apps:
http://stonish.net/CosmosEx.csv

List is provided & maintained by Bruno Mathieu

**Comment by atarijookie** [comment]
While working on it and moving to multiple image (and apps?) list I originally thought user would have to select between the lists and then search within them, but then I thought that's unnecessary, so maybe just merging lists together would be enough... 

So the device on start should:
- download some list of lists
- check if have all the lists downloaded and if downloaded lists have the latest version
- could be done in bash instead of C++
- download lists to device
- merge those multiple lists into one large single list
- let ce_main_app work with that single list

**Comment by atarijookie** [comment]
The other way of doing this would be on web server, once a day, and there would be no need for change on devices then... So we could modify this file, which gets called by each device on start-up:
https://github.com/atarijookie/ce-atari/blob/master/list_merger/report.php

Changes that need to be done:
**1** Add code in that report.php, which gets last DATE (no need for time, just year-month-day) when this function was run, and if it was called today already, don't execute anything else

**2** If this function (url) was called yesterday or earlier, mark that TODAY as last date this was called and proceed with the rest

**3** Call some async function, which will do the rest of the job, but it should be async, so the original report-"UPDATE OK" will take only short time like when this function is not called

**4** Take this file `http://joo.kie.sk/cosmosex/update/imagelist.csv` and rename it to: 
`automation_exxos.csv`

**5** The async function had a list of files on the input, and the list will contain for starters this:
```
http://joo.kie.sk/cosmosex/update/automation_exxos.csv
http://stonish.net/CosmosEx.csv
```

**6** Each of the files from the list needs to be downloaded to temp folder (or to memory) and it contains the last-date-of-change on the 0th line of the file, e.g. `2016-11-24`, extract all those dates

**7** If all the files have versions we already used last time (nothing has changed), don't do anything else, we're done (this means retrieving those last-date-of-change dates from somewhere, e.g. from database)

**8** Read all the content of files, write them (without the 0th line where the date is) into one huge file, and the 0th line should contain today's date

**9** Store all the dates somewhere (database), so next time we won't have to merge the files when they don't change (like in the **6**)

**10** Output the final merged list into file:
```http://joo.kie.sk/cosmosex/update/imagelist.csv```

**11** Change the date in the line 'imglist' to current today's date:
http://joo.kie.sk/cosmosex/update/updatelist.csv
(read file, when the line contains 'imglist', output different date)

**Comment by sinodko** [comment]
@atarijookie I would like to take this one :)

**Comment by atarijookie** [comment]
I've done the image list automatic merging in php, it will be run by webCron on my hosting once per day, and in a day or two if it will look ok (from the e-mail reports the webCron should send), I will turn it fully on.

**Comment by atarijookie** [comment]
Okay, so the e-mails from webCron don't come, but the script is executed and lists are merged, so closing this task.
