### ISSUE TITLE
Add a hotkey to bypass mounted floppy boot

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#179]
Correct me if I'm wrong but unless I have the web server accessible from outside, there's no way to disable floppy boot other than switching the Atari off?

**Comment by atarijookie** [comment]
What's wrong with pressing front button on the device to choose no_floppy_image (all floppy LEDs off) and then you won't boot any floppy image from CE?

**Comment by mikrosk** [comment]
If nothing else, I failed to find this information in either manual under Floppy section. :-P But you're right, it's sufficient.
