### ISSUE TITLE
Working on NFS-mounted drive leaves strange hidden files behind

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#192]
What I did: put LHarc and JAYMSA18.LZH on the shared drive. Unpacked the archive, it created a folder called JAYMSA18 with files inside it. I tried to delete it afterwards but couldn't - while the files inside the folder were deleted, on the linux side I can see there are strange leftovers in that folder:
```
-rw-r--r-- 1 mikro mikro   1457 máj 18 20:05 .nfs00000000018e179a00000009
-rw-r--r-- 1 mikro mikro    220 máj 18 20:05 .nfs00000000018e179b00000008
-rw-r--r-- 1 mikro mikro  26291 máj 18 20:05 .nfs00000000018e179c00000006
-rw-r--r-- 1 mikro mikro  27534 máj 18 20:05 .nfs00000000018e179d00000007
-rw-r--r-- 1 mikro mikro  18332 máj 18 20:05 .nfs00000000018e179500000001
-rw-r--r-- 1 mikro mikro   1722 máj 18 20:05 .nfs00000000018e179600000005
-rw-r--r-- 1 mikro mikro 118912 máj 18 20:05 .nfs00000000018e179700000004
-rw-r--r-- 1 mikro mikro   6266 máj 18 20:05 .nfs00000000018e179800000003
-rw-r--r-- 1 mikro mikro     93 máj 18 20:05 .nfs00000000018e179900000002
```
Perhaps that is the reason why Atari refused to remove the folder.

**Comment by miniupnp** [comment]
is your shared drive NFS or SMB ?

**Comment by mikrosk** [comment]
As the title says, it's NFS. :)

**Comment by miniupnp** [comment]
This sould be NFS version 2 or version 3
http://nfs.sourceforge.net/#faq_d2

the presence of .nfsxxxxxx files means the files were deleted while still open.

I think my commit e1464ae8dda8eea9c5d023fdde9854b15cd26381 may have fixed it.

**Comment by mikrosk** [comment]
Possible. If you make me a build for #194, I can test this one, too.

**Comment by mikrosk** [comment]
Confirmed, when compiled CE from master, the bug is gone.
