### ISSUE TITLE
Case sensitivity problem on shared drive

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#198]
Funny issue - I had a file named TUBES.BIN on N:\ (shared drive), created by an Atari app.

I didn't want commit it to git in uppercase, so I renamed it in Linux to tubes.bin. Since then it got reported to TOS (and any atari app) as not found. Nothing really helped (i.e. asking for "tubes.bin" or "TUBES.BIN" from Atari side), I had to stop and start the CE again to flush its filename cache.

**Comment by miniupnp** [comment]
well you mean you renamed a file after browsing the directory from Atari ? Indeed there must be a cache problem...

**Comment by mikrosk** [comment]
Yes, exactly.

**Comment by atarijookie** [comment]
> so I renamed it in Linux to tubes.bin

So you created in on Atari, but then renamed it on your PC or on your Raspberry Pi (inside CosmosEx)?

The translation dictionary between Atari 8.3 names and linux filenames is done when you open some directory on your Atari. If you rename it under linux (or windows) then the ce_main_app doesn't know what you renamed it to and it doesn't do a refresh of the dictionary in that case.

What could be done:

1. if file not found by the name stored in the dictionary, do a full directory re-scan to fill the dictionary - might be slow in full directories, and if you got long filenames in that dir, they might get assigned different 8.3 names in the dictionary as there isn't a guarantee that the files in that dir will be returned in the same order than the last time

2. try to find the single file, but with some case-insensitive comparing, so it would work on files renamed like this, but it would fail if you would rename the file to something different - TUBES.BIN -> tubesxxx.bin

3. do something else? (propose)

**Comment by mikrosk** [comment]
Yes, it should be definitely 2). I would even go further - and make the cache case insensitive by default. Two reasons:
1. Windows doesn't allow you to have TUBES.BIN and tubes.bin next to each other anyway
2. Linux does but what do you show on Atari side? So I'd just call this a known limitation.

**Comment by atarijookie** [comment]
Partially fixed for fopen() in this commit:
https://github.com/atarijookie/ce-atari/commit/fd9ca866de0cd3d6032de192ed6561826c4592b6
...by adding hostPathExists_caseInsensitive()

Two more things to do:
- [x] update dir translator with newly found filename
- [x] possibly find in which other functions than fopen() this happens and add it there, too

**Comment by atarijookie** [comment]
Done the update of dir translator, not tested (but compilable).

**Comment by atarijookie** [comment]
Tested, works, closing ;)

1st fopen() in original file - open OK
2nd fopen() after file renamed - found with case insensitive, updated dir translator / filename shortener
3rd fopen() went directly for renamed file because it already used the updated dir translator.
