### ISSUE TITLE
make update on devices per individual files

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#199]
Having one ce_update.zip seems fine for download using single wget, but it gets annoying when you update just one file - you have to rebuild even ce_main_app binaries, as the version of the main app is stored there... 

What I would like to have is something just like 'svn up' or 'git pull' or 'wget whole directory', so when there is fix for single file, we won't need to create whole zip file... 

I guess we could avoid this if the whole release would be automated, but it still would need test it on all the distros, if change would be in the ce_main_app. As there will be another Raspbian soon (or there already is one) because of new RPi 4, there might be need to do that distro, too... So I would slowly start to stop doing tests and features (and re-builds) on Yocto, then Raspbian Jessie, and then keep doing only Raspbian Stretch and possibly the newest Raspbian... 

With the 'per invididual files' update, I could keep fixing or building some files, but keep the others untouched, while not doing the whole collecting-and-zipping-files thing over and over again... 

Any ideas? ;)

**Comment by mikrosk** [comment]
Actually, using `git pull` (or `svn up`) is quite common on web servers -- only people like Xi are uploading their html files via FTP. ;) So I can imagine update process like that, too. (remember, you can do `git pull` even locally, from another folder).

However, this wont provide you other services like restarting something, copying it to some specific location (/etc/config_file for instance) etc. So you will need a custom updater anyway.

And yes, get rid of that Yocto monster for good, it only makes things messy.

**Comment by atarijookie** [comment]
> Actually, using git pull (or svn up) is quite common on web servers

Yes, that's where I got the idea from ;)

> However, this wont provide you other services like restarting something, copying it to some specific location 

Some additional script would be needed for that work, but at least the update could be possibly simpler... Let me think about this one.

**Comment by atarijookie** [comment]
Which one of the two mentioned would be easier to set up? 
- svn can check out only a sub directory if needed (e.g. distro subdirectory)
- git could directly point to github as a free service for that 
- but I remember that git was downloading a lot of objects / stuff when doing first 'git clone'
- maybe something other than svn / git?

**Comment by mikrosk** [comment]
> but I remember that git was downloading a lot of objects / stuff when doing first 'git clone'

`git clone --depth=1 --branch=master` :)

**Comment by atarijookie** [comment]
Hmm, to the 'lot of objects' issue would be solved by depth.
What about not downloading all the unnecessary sources from master? So either having different branch for updates distribution, or having completely separate repo for updates distribution (instead of using ce-atari)...

**Comment by atarijookie** [comment]
Few things come to mind:
- the CosmosEx binary for each distro should have it's own branch, so it won't need a rename from cosmosex_[DISTRO_NAME_HERE] to cosmosex
- firmware binary files should come with a text file next to them, so the update script can figure out the versions of the fiemware files and thus if it needs to flash chips or not
- update script should check for presence of git and if missing, it should install it (apt-get isntall git)

**Comment by atarijookie** [comment]
TODO:
- [ ] change the way the update is shown and checked for in ce_conf
- [x] check for presence of git in linux, if not present, do apt-get install git (will be mostly used after first new update requiring git)
- [x] check if /ce/ is tracked by git - if not then git clone, if yes then git pull
- [x] retrieve current Franz and Hans FW versions from chips, compare to current ones from repo, decide if flashing is needed, flash
- [x] change firmware versioning from 'YYYY-MM-DD' to something simpler, so it can be compared easily in bash (to determine whether we need to flash firmware or not). We could either transform that to single integer (e.g. to seconds from epoch), or something simpler - just leaving out '-' will convert it to YYYYMMDD number - this could also work, as MM has this way higher weight than DD, and YYYY has higher weight than MM
- [x] add some post-install / pre-run script, which will do what is currently in copynewscrips.sh, e.g. setting the fixed core_freq=250
- [x] remove most of the things done in copynewscripts.sh as this will be mostly done by git (compare if file needs to be replaced and copy it)
- [x] fix / change or remove update from USB drive (zip file)
- [x] update on yocto (without git) will be the same path as update from usb, but it will start with wget archive 

Check if update will pull something:
git remote update
git status -uno | grep 'behind' | wc -l

new update flow:
- got git? if not, install git
- check remote status, are we behind head?
- store franz & hans versions
- run ce_update.sh script:
- it will git pull
- will check current vs new versions of FW for F, H, X
- do flash if needed

In ce_update.sh we need options for:
- reboot (after network settings reset)
- download all and force flash (e.g. for first FW write / FW recovery)
- re-flash Xilinx (on FW mismatch after ACSI / SCSI switch)

**Comment by atarijookie** [comment]
TODO:
- [x] add missing /ce/update/hans.version +  /ce/update/franz.version + xilinx.version to releases repo
- [x] add checking for update pending
- [ ] test and fix

**Comment by atarijookie** [comment]
hmmm, so on yocto or without git I still could check if there's a update pending or not - by wget github api to get last commit...

**Comment by atarijookie** [comment]
Anyone - any idea what to place as text for online update? 'Online' looks just like state of device, 'Internet' looks like internet configuration button, 'From web' is technically wrong as it will go mostly from git, 'OnlineUp' is messed up, too ;)

![ce_update](https://user-images.githubusercontent.com/18427437/61185217-06535180-a657-11e9-996c-69373f4a4623.png)

**Comment by atarijookie** [comment]
Added storing and showing checking-for-update-status and if update is available or not...

Now for some final testing and fixing and then we're good.

**Comment by atarijookie** [comment]
Most of the things are now fixed for Jessie. 

TODO:
- [x] test and fix on stretch and yocto
- [x] make and commit new builds for stretch and yocto (current doesn't copy the scripts)
- [x] test and fix update using ce_config.tos
- [x] 'update not neededte' in web config, probably will show on ST, too

**Comment by atarijookie** [comment]
```
Will try to install missing git
/ce/ce_update.sh: line 44: apt-get: command not found
/ce/ce_update.sh: line 45: apt-get: command not found
git is still missing, will use wget
wget: not an http or ftp url: https://github.com/atarijookie/ce-atari-releases/archive/yocto.zip
unzip: can't open /tmp/yocto.zip[.zip]
XILINX firmware writing script.
Detected XC9536 chip, will write firmware
XSVF Player v5.01, Xilinx, Inc.
XSVF file = /ce/update/xilinx.xsvf
ERROR:  Cannot open file /ce/update/xilinx.xsvf
cp: cannot stat '/ce/update/xilinx.version': No such file or directory
----------------------------------

>>> Updating Hans - START
Will use serial port:  /dev/ttyAMA0

stm32flash - http://stm32flash.googlecode.com/
           - with the fix for DS1818

>>> Will flash HANS <<<

Intel HEX ERROR: System Error
/ce/update/hans.hex: No such file or directory

cp: cannot stat '/ce/update/hans.version': No such file or directory
----------------------------------

>>> Updating Franz - START
Will use serial port:  /dev/ttyAMA0

stm32flash - http://stm32flash.googlecode.com/
           - with the fix for DS1818

>>> Will flash FRANZ <<<

Intel HEX ERROR: System Error
/ce/update/franz.hex: No such file or directory


>>> Updating Franz - END
----------------------------------
cp: cannot stat '/ce/update/franz.version': No such file or directory
cat: /boot/config.txt: No such file or directory
cat: /boot/config.txt: No such file or directory
No core_freq in /boot/config.txt, adding it
mv: cannot stat '/boot/config.txt': No such file or directory
cat: /boot/config.old: No such file or directory
ln: failed to create symbolic link '/lib/systemd/system/ctrl-alt-del.target': No such file or directory
ln: failed to create symbolic link '/etc/systemd/system/getty.target.wants/getty@tty1.service': No such file or directory

Update done, you may start the /ce/ce_start.sh now!
```

-- on yocto the wget is compiled without https support

**Comment by atarijookie** [comment]
@mikrosk @miniupnp @ggnkua @tin-nl 
- could any of you try the new update - if it works - on stretch or jessie? When you don't have git on device, update might take around 6 minutes due to git installation. 

- I guess this is the end stop for yocto - wget on yocto doesn't support https (only http), github doesn't support http, and I guess t's not worth spend my time here - let the users upgrade to stretch.

**Comment by mikrosk** [comment]
Uhm, for me the experience hasn't been very good so far. I'm on stretch - I got an update, so I updated it. After reboot I got random freezes and even more interesting - CE_CONF still insisted that there's an update available.

It complained something with git (couldn't read the whole message) so I went ahead to make its life easier and installed it. Rebooted everything, got a message "git is found, good..." (and something after it) but still no positive result. So I manually ran /ce/ce_update.sh, that went well but since then I can't start CE at all ;)

Now when I start CE, I see:

```
root@cosmosex:~# /ce/ce_start.sh 
Terminating cesuper.sh
Terminating cosmosex not needed, no instance is running
Warning: cosmosex.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: cosmosex.service changed on disk. Run 'systemctl daemon-reload' to reload units.
cosmosex is running, terminating start script...
```

Just to clarify, `cosmosex` is among running processes, it's just totally not communicating with atari.

**Comment by mikrosk** [comment]
Starting the exe:

```
No default app arguments.
CosmosEx main app starting on Raspbian...

Log level: DEBUG

Will try to update scripts
Doing sync...
All files should be up to date now.
Starting threads
Entering main loop...
Hans not alive, resetting Hans.
Franz not alive, resetting Franz.
Hans not alive, resetting Hans.
Franz not alive, resetting Franz.
Hans not alive, resetting Hans.
Franz not alive, resetting Franz.
Hans not alive, resetting Hans.
Franz not alive, resetting Franz.
  [ / ]  Hans: DEAD, Franz: DEAD

Exit from main loop
Stoping screecast service
Stoping floppy service
Stoping date service
Stoping virtual keyboard service
Stoping virtual mouse service
Stoping mount thread
Stoping download thread
Stoping ikbd thread
Stoping floppy encoder thread
Stoping periodic thread
Downloader clean up before quit
Terminated
root@cosmosex:/ce/app# 
```
... encouraging :)

**Comment by atarijookie** [comment]
Jeebus Crust, that went terribly bad, I've never seen it go that bad. And even exe not communicating with both of the chips - terrible (but never happened to me).

The 'got 1st update, updated, got 2nd update, updated' thing is due to 1st update being from the web (old way of update), then having the exe which checks for update in the new way, and you find new update on github (or just by missing git), so it tells you to update again. After that it checks only in the new way, so you will see update / no update based on the real status...

Can you write new Slack image from my page and check if it runs fine / better or not?

I'm not sure if I can fix these issues without you or someone's other help - none of the 'not communicating' issues were happening at my place. Plus I'm just terrible with the systemctl deamon things :-/

**Comment by mikrosk** [comment]
It's even worse. I `dd`'ed the new Stretch image from scratch but the initial symptoms remain (freezes). Generally speaking, I can observe the following:
- random freezing for 2-3 seconds (mouse/keyboard, communication timeouts in CE_CONF)
- USB keyboard randomly switching off in the console, I have to re-enable it via LCTRL+ALT+ALTGR+RCTRL 
- Franz FW reports as 0000 despite the fact that update tool says everything is up to date (if it just doesn't timeout...):
![IMG_20190727_101254](https://user-images.githubusercontent.com/3062260/61991924-903beb00-b057-11e9-8a12-14425d827258.jpg)
- ce_update.sh reports everything OK

**Comment by mikrosk** [comment]
I suspect that maybe something went wrong during Franz/Hans update, is there a way to force update / rewrite firmware?

**Comment by mikrosk** [comment]
Tried the old Stretch, update went well:
![IMG_20190727_103416](https://user-images.githubusercontent.com/3062260/61992167-13127500-b05b-11e9-8fa3-e6b623e89466.jpg)

and yet all of the problems persist (incl. Franz version 0000). Now I know how all those poor souls feel when "CE just doesn't work" :) I have an old ce_update.zip on my disk, I'll try to update/downgrade it, if possible.

**Comment by mikrosk** [comment]
What really surprises me that even after a clean rewrite of the SD card, I get versions like this (old Stretch):
![IMG_20190727_111841](https://user-images.githubusercontent.com/3062260/61992576-96829500-b060-11e9-8cad-ec150a364b2f.jpg)
That would imply that there is something like a first time flash when the new card is booting? But if so, I can't understand why Franz stays at 0000?

**Comment by mikrosk** [comment]
OK, the final nail to my unhappy endeavour - 'update from usb' as per http://joo.kie.sk/?page_id=484 doesn't work at all - I get only frozen screen after "from USB" and after a while return to the main menu.

**Comment by mikrosk** [comment]
Hmm, it seems that CE_CONF just doesn't check Franz status at all:

```
No default app arguments.
CosmosEx main app starting on Raspbian...

Log level: DEBUG

Starting threads
Entering main loop...
Franz not alive, resetting Franz.
Franz not alive, resetting Franz.
Franz not alive, resetting Franz.
Franz not alive, resetting Franz.
  [ / ]  Hans: LIVE, Franz: DEAD

Exit from main loop
Stoping screecast service
Stoping floppy service
Stoping date service
Stoping virtual keyboard service
Stoping virtual mouse service
Stoping mount thread
Stoping download thread
Stoping ikbd thread
Stoping floppy encoder thread
Stoping periodic thread
Stopping display thread
Downloader clean up before quit
Terminated
root@cosmosex:/ce/app# 
```
i.e. when RPi boots, it should perhaps halt if Franz is dead, shouldn't it. That would explain that zeroes. Now the question is, how to revive Franz? :-P

**Comment by mikrosk** [comment]
To my big relief, I have managed to get it working again. Basically I had to erase everything from /tmp, unpack my old ce_update.zip (as the USB is totally dead) there, run scripts from /ce/update one by one and got it to this state:
![IMG_20190727_115607](https://user-images.githubusercontent.com/3062260/61993025-27a83a80-b066-11e9-8a46-cf295a273b93.jpg)
As I have some Atari work to do, I'm leaving it as is for now, @atarijookie if you like to stop by sometime during this weekend, we can take a look together but I'm not breaking it again deliberately :D

**Comment by ggnkua** [comment]
Aww look, grandpa is now making excuses instead of testing :P

**Comment by atarijookie** [comment]
Okay, we need to get this working nicely, it's the best option of anyone allowed (you, him and me, and also him) doing minor fixes and releasing them to public, instead of the previously used complicated update system which only I could push out as a release... (this is still cry for any possible help).

If the chips are not written, the /ce/ce_update.sh script checks if the file /tmp/FW_FLASH_ALL exists and if it does, then it flashes the chips, even if the stored versions of chips seems to match with what is in the chips. So for that /ce/ce_flash_force.sh we just need to have inside:
touch /tmp/FW_FLASH_ALL
/ce/ce_update.sh

...and that should resolve the situation when chips are not flashed or are badly flashed.

The whole update process (now vs. the old one) didn't change much - instead of downloading the ZIP file, extracting to tmp and then extracting to /ce/app and flashing chips, it's replaces with git pull and then flashing chips if needed. The checking for versions, generating update script, doing the update was back then done in the ce_main_app, now it's all just in the shell scripts (check_for_update.sh + ce_update.sh), so it should be even much easier to understand and fix than when it was split between C++ app and the shell scripts.

If no one doesn't give me a helping hand, I might visit MiKRO to ask him for help personally (try it at his place), but that will be in 2 weeks - I'm busy this week (family celebration today, packing tomorrow), and then I'll be more than a week on vacation with wife and kids...

**Comment by mikrosk** [comment]
Another strange update report (xilinx version 0000): http://atari-forum.com/viewtopic.php?p=378819#p378819

**Comment by atarijookie** [comment]
The 'xilinx version 000000' issue is due to the fact that:
- the version of xilinx is not read from chip, but from file
- that file name changed because of this update change
- there wasn't a change to read the version from the new file in the ce_main_app, but now there is: https://github.com/atarijookie/ce-atari/commit/29914fb977b81862a97ba8928c414d93c6a61064
- ...but it's not tested as I'm 1200 km from my CosmosEx device, so I will test the fix and possibly improve it when I get home... 

But this is a minor issue - xilinx works no matter the badly displayed version in config.

**Comment by atarijookie** [comment]
Another issue is / was that once you write the new SD card image, you might still have old chips FW, but the ce_main_app is new and requires newer ones. So I've added check for FW chips version to ce_start.sh, hopefully it will detect this situation and write new chips FW. I've also added the /ce/ce_force_flash.sh for manually forcing the FW flashing.

I need to test these ones once I get home to real RPi and then, if everything will be good / better, I might update and upload the Stretch SD card image again to my web...

**Comment by ggnkua** [comment]
Ok, I finally got some time to test this on my devices. I'll list them for the record:

a)
```Hardware version  :   v. 2
HDD interface type:   SCSI
Linux distribution:   Raspbian (Jessie)
RPi revision:  0010
Raspberry Pi Model B Plus Rev 1.2
```
b)
```
Hardware version  :   v. 1
HDD interface type:   ACSI
Linux distribution:   Raspbian (Jessie)
RPi revision:  000e
Raspberry Pi Model B Rev 2
```

When I booted (a) the network wasn't working (as mentioned in #189) but the keyboard was running ok, so I got a usb stick and stuck the latest update. That did the trick and now the device is at latest firmware for everything.

(b) had network working so I simply hit update and it upgraded to latest.

Worthy of note is that I did the update twice for each device from linux console (ssh) so that the git mechanism can start working. I saw it on console fetching stuff (on the pi (b) it had to fetch git as the sd card had a fresh jessie image flashed to it).

Also, one hiccup, (a) cannot function using a static IP for ethernet. When I try that, ```ifconfig``` simply displays a ipv6 address but no ipv4, and pinging anything displays network failure. Also, during boot it displays ```Failed to start dhcpcd on all interfaces```. When I enable dhcp for ethernet then it can get a proper IP from the router and it'll work as advertised. The failure message will still get displayed on boot though. Perhaps that GPI reset you perform isn't enough? I'm not sure, just thinking out loud!

**Comment by atarijookie** [comment]
note to self: change the fake update progress in ce_conf to have 6 minute timeout, because it might take that long due to git installation...

**Comment by atarijookie** [comment]
tested the xilinx version reading, seems to work fine...
So things to do:
- [x] that change in ce_conf
- [x] put new image of stretch on web

**Comment by atarijookie** [comment]
After changing ce_conf and submitting it to releases git, I've did the update, and there seems to be one additional problem -- open ce_conf -> check for update -> update found -> do update -> open ce_conf -> check for update -> update found, and so on - it seems that it doesn't update the files now or what :(

**Comment by atarijookie** [comment]
The issue was due to killing cesuper.sh from ce_update.sh, but that killed also ce_update.sh and the app then couldn't start. It seems that I've fixed this now...

**Comment by atarijookie** [comment]
As the statis IP bug has own github issue #205, if people will report that the new update works, this issue will get closed and the static IP issue might get looked into in that other #205 .

**Comment by atarijookie** [comment]
Update seems to work on Stretch, closing.

**Comment by mikrosk** [comment]
Just for the record, I was brave enough to try the update again (from the rescued ~2018 state as mentioned above) and fell into the same trap. It's showing exactly the same symptoms as described above.

I'm going to download the new stretch image, I guess that will do the trick here. Will report later.

**Comment by mikrosk** [comment]
Nope, sorry.

The symptoms are exactly the same - keyboard/mouse freezing, CE_CONF reporting lost connection (and then finding it again), ...

I even did manual flash update of all chips, it succeeded but didn't change anything (including the 0000 version of Franz).

So for me there is no other way than to revert back to 2018 versions with new CE_DD.PRG. @atarijookie I guess you still have to come over and see it for yourself. :)
