### ISSUE TITLE
No special chars in network share password field

### ISSUE THREAD

**Issue by tuxie01** [atarijookie/ce-atari#2]
There is no possibility to use special characters in the network share password field. The special characters are not safed. 

Special Chars like , _- #

**Comment by miniupnp** [comment]
I think I can fix it !

**Comment by miniupnp** [comment]
@tuxie01 : can you test new code ?

**Comment by tuxie01** [comment]
at the weekend i have time to work on the ce, yesterday i prepaired a development environment with a Linux install inside a Virtual Maschine (VirtualBox)

**Comment by tuxie01** [comment]
Sorry clicked the wrong button...

**Comment by miniupnp** [comment]
I still have a problem with ,
Next step is to use credential file

**Comment by tuxie01** [comment]
It is working now :) great
