### ISSUE TITLE
ACSI speed regression

### ISSUE THREAD

**Issue by tin-nl** [atarijookie/ce-atari#201]
I noticed a speed regression from ~1MB/s to 500k/s ACSI transfer rate on V1 (jessie) a while back. This seems to be introduced with the 2018-05-10 release (tested myself) and is still in place in the current https://github.com/atarijookie/ce-atari-releases/commit/5c659756877c75f315033d03f700c2d42533e83a (quickly confirmed by @ggnkua).

- all tests were done with plain ST hw and CE v1
- testing transfer speed with CEs own test reports (regressed) ~500k/s with the 2018 release
- same with previous release reports (the expected) 1Mb/s on same hardware
- FPGA firmware version does not affect this, tested with 2018 and 2017

**Comment by atarijookie** [comment]
Thank you for finding out where the issue started to appear - it will be easier to find the problem...

**Comment by ggnkua** [comment]
Continuing from #189, I flashed a fresh jessie image to my v1 Cosmosex with a raspberry pi 1 model b and the speed test gave ~1mb/sec, if this helps

**Comment by atarijookie** [comment]
After making a fix in #189 I've made a speed test - oldest CE (v1) running oldest RPi 1 (with only 2 USB ports, not 4), with Raspbian Stretch, and I've got 1064 kB/s when tested through CE HD test... 
![speed](https://user-images.githubusercontent.com/18427437/61768127-c58dd200-ade6-11e9-858f-477930c533bb.jpg)

The Stretch image on web isn't updated yet, don't try until I update it as it causes the disabling of USB + eth on start. After I will update the Stretch image today, could somebody do a test for me to see if it's still happening?

**Comment by atarijookie** [comment]
The new Raspbian Stretch image is on my web page, try it and report what speed you got on what device and RPi version.

**Comment by ggnkua** [comment]
Just tested with latest firmware on the offending device and it seems to have gone back to normal speeds. I think we can close this now, well done @atarijookie :)

**Comment by atarijookie** [comment]
Thanks, but I still want to test it on multiple devices (older and newer) to see if something is not slowing it down on some of them :)

**Comment by atarijookie** [comment]
Tested on:
- CE v1 + Stretch
- CE v2 + Jessie
- CE v2 + Stretch
All devices with the current release had 1 MB/s of transfer speed, so I guess we're fine now and we can close this.
