### ISSUE TITLE
TRANS.TBL support

### ISSUE THREAD

**Issue by miniupnp** [atarijookie/ce-atari#32]
As 8.3 filenames are a bit limited, it could be great to support TRANS.TBL in translated drives.
I remember using such files on old CDROMs with MSDOS.
https://en.wikipedia.org/wiki/TRANS.TBL
As they are text files, they can easily be parsed by tools on the atari, or even be displayed to the user

**Comment by atarijookie** [comment]
Now the main question would be - how the Atari users would use that? I would assume more than 50% of them don't use any special software which could handle TRANS.TBL...

The support for long filenames is good in MiNT and MagiC, but that requires much effort (changing  / extending the translated drive features). The support under bare TOS is not present. Could you describe the usage a bit more? Maybe I just need to get the right understanding and then it all will be clear :)

**Comment by miniupnp** [comment]
I just remember how we got around 8.3 limit back in the old days.
on PC I was using 4DOS which displayed additional data with dir. It was stored in a DESCRIPT.ION file if I remember.
I don't know if TOS applications have a usual way to do...

Anyway, don't waste any time on it if there is no user need :)
