### ISSUE TITLE
FileNameShortener in CE main app doesn't refresh when files are added on host

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#40]
1. Open a shared folder on ST and see the files
2. Create a file or folder with long filename on PC in that shared folder
3. Hit ESC on ST to refresh folder content on ST, see if the new folder (created on PC) did appear
4. Try to open the new folder on ST - this fails, if I remember correctly.

In 3. the files / folders are processed with DirTranslator::buildGemdosFindstorageData().
In 4. the files / folders functions go through TranslatedDisk::createFullHostPath(), which then does dirTranslator.shortToLongPath(), and that will eventually fail to find the long version of the filename, as the directory was processed before the folder was created. 

What should be done: 
- add some code, which will do some sort of refresh / reprocessing of that folder, if dirTranslator.shortToLongPath() fails. On the other hand - make sure that it doesn't process the folder way too much times in a row, like when the ST would try to open various non-existing files from that folder (add some sort of DWORD lastTimeThisFolderWasProcessed?)

**Comment by miniupnp** [comment]
I think what should be done is that DirTranslator::buildGemdosFindstorageData() updates the dirTranslator stored data, thats all...

**Comment by miniupnp** [comment]
I do not have the bug anymore. I think it was because 2 shortener were kept for same path (because code used both path with and without trailing slash) which were not in sync.
Test with my latest patches :)

**Comment by atarijookie** [comment]
OK, I will do a test on my Atari once I get to it (this or the next night). I really miss a way of testing things like these without the Atari - either unit tests, or something else...

**Comment by atarijookie** [comment]
I tested it before merging (pulling) your changes to my local git repo and I didn't experience this one, so either I can't reproduce it (am I doing something wrong?), or it was already gone... Closing this issue.
