### ISSUE TITLE
FAT attributes on translated disks

### ISSUE THREAD

**Issue by miniupnp** [atarijookie/ce-atari#44]
as far as I see, the ce_main_app doesn't read FAT attributes on translated disks/sticks.

there are some solutions using ioctls : http://stackoverflow.com/questions/1644416/how-to-read-vfat-attributes-of-files-in-linux-using-c

Also my FAT32 sticks and my network shares are filled with Mac OS X crap (.AppleDouble .DS_Store, etc.) which shows at .APP .DS_ on the ST.
theses dot files are supposed to be hidden. OS X uses both the unix convention (file starting with . are hidden) and sets the FAT HIDDEN attribute when possible

**Comment by Gunstick** [comment]
Would need to know if TOS even respects the attributes. Else there is no need to emulate them. Still, removing the display of . files can be useful. Maybe add an on/off switch in the config, like for the ZIP files.

**Comment by ggnkua** [comment]
According to the compendium (http://www.yardley.cc/atari/compendium/atari-compendium-GEMDOS-Function-Reference.htm)

FA_READONLY 0   Read-only flag
FA_HIDDEN       1   Hidden file flag
FA_SYSTEM       2   System file flag
FA_VOLUME       3   Volume label flag
FA_DIR      4   Subdirectory
FA_ARCHIVE      5   Archive flag
     -      6...    Currently reserved

So at least these should be alright. If needed I can take a look at GEMDOS source code to see if they keep any undocumented ones internally.

**Comment by miniupnp** [comment]
have a look at my branch "attributes" :
https://github.com/miniupnp/ce-atari/tree/attributes
I've not enabled the "ARCHIVE" bit because of this comment : https://github.com/miniupnp/ce-atari/blob/9d5b9c77fe58f48f6c391712211f38ca7f927a51/ce_main_app/translated/dirtranslator.cpp#L292
