### ISSUE TITLE
GEM version of ST apps

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#46]
Some ST apps for CE could really use GEM user interface instead of the text only interface, e.g. the fdd management tool... some people really disliked the text version of that. I don't have experience with GEM programming :)

**Comment by miniupnp** [comment]
that's another point for renaming apps to .TOS. so there could be both .TOS (for VT52) version + .PRG (for GEM)       ;-)

**Comment by mikrosk** [comment]
Trouble with GEM apps is that the CE is evolving quite fast. Right now, we can benefit from Jookie's clever solution with 'streams', so whether it's web UI, native Atari or native Linux, you still get updated all three of them with one single commit. Imagine adding combo boxes, checkboxes, popup menus...

**Comment by atarijookie** [comment]
Currently I think the most important change from TOS to GEM would be only
for the CE_FDD tool - to show more easily which slot contains what, to swap
images and other things with mouse, and also the (now not working) image
download and search. The other tools are fine in console as they are now.

**Comment by miniupnp** [comment]
I do prefer console apps !
About CE_FDD.PRG I just discovered it's already using AES file selectors.
it should definitely evolve to a full GEM app ;)

**Comment by atarijookie** [comment]
In the past and present days I'm working on GEM version of CE_FDD.PRG, most of the GEM code is already there, partially tested under Hatari. Now I need to go and test it on real ST with real data, then fix all those issues that there might be...

**Comment by atarijookie** [comment]
Some things were fixed and improved in CE_FDD.PRG, it was merged into master. I guess other ST apps won't be rebuilt to GEM soon, so closing this as 'done' :)
