### ISSUE TITLE
Pexec issue ? Demos not loading

### ISSUE THREAD

**Issue by miniupnp** [atarijookie/ce-atari#49]
I don't understand exactly why, but some cool demos don't run from a translated drive anymore (release_ce_main_app-2016-05-01)

Fantasia (big .TOS file) is still running fine, but it only requires 1.7MB of free RAM
Sea of colors is going back to desktop directly.
We Were @ is saying it needs a STE with 4MB (which I have :)
DHS / Summer Delights display a GEM error message box complaining there is not enough RAM in the machine (in french on my STE)

All theses demos were working fine a few weeks ago.

**Comment by atarijookie** [comment]
I wonder if it was working fine with release_ce_main_app-2016-04-24:
- if 2016-04-24 would work fine and the 2016-05-01 doesn't work, that could be related to ce_dd_unified_bootsector (improvement by @tin-nl ), which might have had not released all the unnecessary RAM on start... 
- if even 2016-04-24 would cause trouble, then I'm not sure... :)

You could do a simple test - let CE_DD boot directly from ACSI device, see if the demos fail (that's what you say above). Then remove CE_DD from ACSI IDs, reset ST, load CE_DD from floppy or SD card (this avoids using the CE_DD bootsector for loading), and see if the demos run fine or not. This would test if the bootsector vs normal loading has any effect on that.

**Comment by miniupnp** [comment]
It's maybe only my STE which has an issue with the 2nd bank of RAM.
SYSINFO now detects only 2MB :(

**Comment by atarijookie** [comment]
> SYSINFO now detects only 2MB :(

OK, and this is with CE_DD not loaded, right? (just to rule out CE_DD messing up something even for SYSINFO).

**Comment by miniupnp** [comment]
yes I unplugged the CE :(

**Comment by miniupnp** [comment]
bank 1 shows as 0 Kbytes :(
