### ISSUE TITLE
strange problem with sd (uppercase / lowercase)

### ISSUE THREAD

**Issue by aligator** [atarijookie/ce-atari#63]
hi,

I have some programs, wich don't run when they are on the SD-card, but on the Translated-USB, the work.

The first program is "Krabat 0.0a for ATARI ST" (a chess game). It says: "Where are the Picture Files"
But the files are there. And when I copy it over to the translated USB-Stick, I can run the game without any problem.

The second game is "Pacman for GEM v. 0.2.5".
It had a similar problem. It couldn't find a rsc-file. But it provided the Atari File selector, to select the rsc-file.

Now the strange thing:
on the selector was chosen, that it schould only show *.rsc files (lower case) --> none were shown.
As soon, as i changed it to *.RSC (upper case), the files were shown! (note that you can only type uppercase, but the lowercase was already there)

But as far as I know tos is not case-sensitive, so this shouldn't happen.

---> I think some programs try to access files with lowercase, because on TOS it should be case insensitive.
But somehow the PI is reading the sd-card with case-sensitivity --> the files are not found.

I have not tested this with RAW mode on USB-Sticks. Maybe there is the same bug.

(I am surprised that something like this can happen, since I thougt that the ATARI handles the filesystem of the sd-card on its own...)

**Comment by miniupnp** [comment]
SD-card access is not done through the PI.
What Hard disk driver do you use ? 

Translated USB disk => CE_DD driver
SD-Card or RAW USB disk => hard disk driver + TOS

**Comment by aligator** [comment]
I use HDDriver (newest version)

**Comment by tin-nl** [comment]
As @miniupnp said - the CE behaves almost exactly like an ultrasatan for SD card - no involvement of the PI here.

A few questions:
-which TOS version are you using?
-did you check the file system for possible damages (e.g. kobolds check tool)?
-anything unusual in your auto folder?

**Comment by aligator** [comment]
TOS 1.04.
I formated the SD with HDDriver --> Pacman works now. but the chess does not
And I replaced the SD-card with another one. --> same ^
I have only this programs in AUTO:
CE_DD.PRG
MACCEL3.PRG
NVDI.PRG

At the moment the only program that has this problem is the Chess game. And I can play it, when I copy it to the USB-stick. So it's not so important...
But I would be interested in what causes this.
Maybe HDDriver?!?

**Comment by miniupnp** [comment]
I would try without anything in the AUTO folder.
It could be a strange side effect of CE_DD on HDDriver...

**Comment by aligator** [comment]
No, even without anything in AUTO it doesn't work...

Bevor the CE I used a harddisk with the ICD driver. Ihaven't tested it with HDDriver on the harddisk, yet.

**Comment by miniupnp** [comment]
@aligator if there is a bug, it is in the HD Driver used. Please contact HDDriver author about it.

on SD Cards and "Raw" disks, the CosmosEx handles only low level stuff (sector access).
The file system stuff is handled by TOS and Hard disk driver.

On "translated" drives however, CosmosEx handles high level stuff (file system functions)
