### ISSUE TITLE
Using the cross compiler toolchain

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#64]
Hi fellas,

has anybody tried this? http://www.yoctoproject.org/docs/1.8/ref-manual/ref-manual.html#cross-development-toolchain-generation

It's just I'm lazy / not really motivated to use another RPi image with gcc & friends installed, I'm a cross compiler person. ;-) Is there any reason why it shouldn't work?

**Comment by miniupnp** [comment]
I prefer compiling on the real machine (even if it is so sloow :) but I don't see any reason for cross compiling not to work !

**Comment by mikrosk** [comment]
Guys, now I'd give gold strips for having a good cross compiler setup. I have to compile a kernel module and for that I have to download linux source code directly to the device and compile it there. Since I still don't know how to mount my computer's folders to the CE, I had to create another partition just for the linux source tarball. :)

**Comment by ggnkua** [comment]
Hi,

From day one I tinkered with the CosmosEx main app I cross compiled. It did take a few false starts and dead ends but I just found someone who packaged arm-unknown-linux-gnueabi, stuck it in my Cygwin folder, hit make and away it went :).

After that, scp'ing the binary to the pi but beforehand shutting down the main app from the pi itself.

Let me know if you still have problems and I'll try to source you with a link.

**Comment by mikrosk** [comment]
I'm in the middle of compiling/installing a cross compiler (fortunately someone has made a arm-linux-gnueabihf-\* set of packages for Arch Linux) but one thing still puzzles me -- how can I be sure that the linked libc/libstdc++/libm/whatever uses the same ABI? I.e. I cross compile the app, nice, now I copy it into the CE and boom, it can have different library versions / ABI / god knows what.

Of course, I can copy the final source and recompile it on the CE but that defies the purpose of a cross compiler a little, doesn't it...

**Comment by ggnkua** [comment]
When I was looking around for a cross compiler for the rpi under Windows I could only find 2 of them, one was arm-linux-gnueabihf-\* and the other arm-linux-gnueabi-*. When I compiled with the hf toolchain and sent the program to the rpi, it blew up. So I tried the non-hf, compiled, sent to the pi, it required some random lib (can't remember), so I found it and scp'd it to the pi in the /lib folder and boom - it ran.

That's all I can remember really - it wasn't a huge pain, just a moderate one ;).

**Comment by mikrosk** [comment]
That's exactly what I'm talking about. ;-) Your app may work only by chance. For instance, the RPi's CPU has an ARMv6 CPU, i.e. _with_ hard floats. So the other compiler you mention is supposed to work too but I guess it came with "too incompatible" libraries / versions.

**Comment by atarijookie** [comment]
If anyone manages to make the crosscompilation work - for raspbian and / or for yocto, please feel free to add the needed steps to wiki page. For now closing this thing.

**Comment by mikrosk** [comment]
... aaaaaaand done here: https://github.com/atarijookie/ce-atari/wiki/How-to-setup-an-RPi-cross-compiler (tested and working, at least as far as `ce_main_app` is concerned)

**Comment by miniupnp** [comment]
@mikrosk thanks !
That is for both Rapsbian and Yocto ? :)

**Comment by miniupnp** [comment]
@mikrosk  if you make a .tar.gz with the result for ubuntu trusty, we can test the cross compilation with travis-ci. I'll have to update the Makefile :)

**Comment by mikrosk** [comment]
@miniupnp basically yes, you might want to change some versions in the config file (gcc+support libs, glibc, maybe curl/openssl?) but I have no means to test on Yocto

about travis-ci, as I mentioned somewhere else, it's not really needed. For FreeMiNT & friends I've decided to let it rot with old m68k-atari-mint-gcc as well, there's no point of doing anything as long as compilation works. This is different from deployment of the binaries.
