### ISSUE TITLE
date/time not preserved when copying from Atari to PC

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#67]
reported by dhedberg, through PM on atari-forum:

I noticed that when copying a file from the Atari (Falcon) to the shared drive on my Windows machine (NTFS) the date/time of the file is not preserved even if you specify this in the (TOS v4.04) copy file dialog box. The created date/time is set to the current date/time while the modified and accessed date are set to Jan 1, 1970 / 00:59:59. It would be nice if created/modified/accessed would be set to the date of the original file instead. Is there any limitations that prevents this?

If I choose not to preserve the date in the (TOS v4.04) copy file dialog box, created/modified/accessed are all set to the current date/time as expected.

The other way around works though (shared drive -> Atari drive).

**Comment by atarijookie** [comment]
user comment:
I looked at the code and made some tests and the problem is most likely in the setNotGet==true branch of TranslatedDisk::onFdatime(BYTE *cmd) or possibly custom_fdatime( void *sp ) on the Atari side. The uTimBuf.actime and uTimBuf.modtime is set to messed up values in TranslatedDisk::onFdatime(BYTE *cmd), either the date/time conversion from Atari to time_t is incorrect or the date/time is not correctly passed from the Atari side. All date/time operations during copy will work as expected if uTimBuf.actime and uTimBuf.modtime are correctly set to the time passed from the Atari side. No other changes would be needed.

If you have the time to look at it I think you would be faster in fixing it. If not, just let me know. I wouldn't mind trying to set things up to be able to compile the code and fix the bug myself. Is there a lot of work involved in this? Any instructions anywhere?

**Comment by miniupnp** [comment]
TranslatedDisk::onFdatime() calls linux utime() which changes last access and modification times, it should be ok
I'm looking why uTimBuf.actime and uTimBuf.modtime are set to messed up values.

**Comment by miniupnp** [comment]
it looks like the conversion from struct tm to time_t is failing (returning -1)

**Comment by miniupnp** [comment]
I found the problem.  Utils::fileDateTimeToHostTime() needs fixing, doing now :)

**Comment by atarijookie** [comment]
Wow, thank you, Thomas :) Merged, not tested yet.
