### ISSUE TITLE
Keyboard as joystick definitions should be based on scan codes

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#73]
So I've had finally some time to play with the CE, explore its features etc. I was really pleasantly surprised to find the feature to map keyboard keys onto joystick 0/1, esp. that it works from the atari keyboard!

However, I'm missing two things here:
- ability to use keys like UP/DOWN/LEFT/RIGHT and then of course CONTROL/numlock etc. I think I know why the directional keys are disabled (it messes up with the config tool navigation) which brings us to the next feature:
- ability to dynamically switch the mapping on and off (using a configurable hotkey like "CTRL+both SHIFTS")

I might by able to code this but first I need some tutorial how to make the dev build working. I 'dd' it onto the SD card and then what? Jookie's web says it's not usable "as is" so what do I need?

**Comment by atarijookie** [comment]
I missed one out of these two things
- either commenting out the /etc/inittab line, or
- removing 'ttyAMA0' from /boot/cmdline.txt

That does block the serial port of Raspberry and has to be done before you want to use the serial port (which handles the IKBD communication). 

See here:
http://raspberrypi.stackexchange.com/questions/10503/enabling-the-uart-port-on-a-raspberry-pi
http://www.hobbytronics.co.uk/raspberry-pi-serial-port

**Comment by atarijookie** [comment]
...and if you want to use the dev image as full image, then you should also:
- create the symlink in the /etc/rc...something from /ce/ce_start.sh to start the main app after boot 
- so if you start the device normally, the main app would start
- and if you will do the development, you first execute /ce/ce_stop.sh to stop the app
- if you want also wifi on that image, you will also have to copy all the wifi firmware files from the 'run' image, from dir /lib/firmware (or something similar) to the 'dev' image, and also make symlink to /ce/wifisuper.sh in the /etc/rcsomething

**Comment by mikrosk** [comment]
OK, just for the sake of completeness:
- remove "console=ttyAMA0,115200 kgdboc=ttyAMA0,115200" from cmdline.txt (located in the root of raspberrypi partition)
- cd /etc/init.d && ln -s /ce/ce_start.sh && update-rc.d ce_start.sh defaults
- reboot

I can understand for more intensive development it doesn't make sense to start the app all the time after a reboot but it's a good start. :)

**Comment by mikrosk** [comment]
Notes for myself.

This requires:
- [x] having a global flag for entering CE_CONF -- so we wont block out arrows, enter and other important keys for navigation
- [ ] another kind of input field, which will read directly scan code of Atari/PC keyboard and transforms it into a human string afterwards (i.e. not reading text, ignoring navigation, enter, F keys etc)
- [x] making sure that the flag/lock wont be set if app crashes / user restart the device etc

**Comment by mikrosk** [comment]
Just an update to this one -- it seems that Atari keyboard (as many others...) has a limit how many keys can be pressed at the same time. From my tests it seems you can have two arbitrary keys plus CONTROL and/or ALT and/or SHIFT1 and/or SHIFT2. That's it. So I'm not sure whether it makes sense to create mappings for both joysticks -- imagine the pain when two cars are accelerating and you can't turn left. ;-) On the other hand, if mapped wisely (accelerate1 = RSHIFT, accelerate2 = CONTROL or LSHIFT) maybe it still makes sense, hmm... But for games like International Karate or Double Dragon there's no rescue -- both players usually want to jump forward + kick the enemy in the same time.

Perhaps the config screen could do some checking, as it does now for same keys and tell the user that he has mapped too many 'regular' keys, for instance if fire == regular key && directions as well for both players and educate him about side effects and fix (map at least fire to SHIFT/CONTROL/ALT).

**Comment by atarijookie** [comment]
> So I'm not sure whether it makes sense to create mappings for both joysticks

Maybe not if 2 want to play on the keyboard, but in case when:
- in one game you play on keyb_joy1 (and the possible other on real joy)
- in other game you play on keyb_joy2 (and the possible other on real joy)

That way you don't need to have a radio box for selecting as which (0/1) the current keyb_joy act... So it's not as good as being able to have 2 keyb joys, but at least it's something...

**Comment by mikrosk** [comment]
OK but why would you want that?

I was thinking about quite a similar one, you remember how some games want you to have joy0 while others joy1? And we were all so pissed of to switch between mouse and joystick? So maybe for that case we could have a hotkey -- i.e. swap joy0/joy1 mapping. Maybe like a circular option -- off (no mapping) / joy0 / joy1.

**Comment by atarijookie** [comment]
That sounds nice ;) Something like Ctrl+F10 isn't used much anywhere... Will you work on that thing later?

**Comment by mikrosk** [comment]
Yeah, this is the main feature I'd like to implement for CE at this time, incl. detection of CE_CONF which would translate into mapping = off, as we discussed on FB.

After that I plan to look at the floppy images (auto reset - #83), IKBD mouse issues, cross compiler and eventually on the super fast boot image. Not specifically in this order. :)

**Comment by atarijookie** [comment]
@mikrosk 

Could you, please, make a small documentation on what you achieved with this? E.g. the description of the RSHIFT and other user written keys, new assignment of HELP and UNDO keys, and so on? 

I will c&p it on my page, in the manuals section, so please write it here, or in some text file.

**Comment by mikrosk** [comment]
@atarijookie the "log" from #139 isn't enough? It's pretty much everything I had done.

**Comment by atarijookie** [comment]
@mikrosk Holy cow, that's enough ;) Thank you, I will use that.

**Comment by atarijookie** [comment]
OK, so I've c&p it here:
[http://joo.kie.sk/?page_id=793](http://joo.kie.sk/?page_id=793)

These features are not released yet (will be in few days). 

Btw., what's the next thing you will make us happy with? :)

**Comment by mikrosk** [comment]
Reading that reminded me... didn't you consider putting the whole manual into this project's wiki? It would be much more accessible / editable, we could cross reference issues etc...

Next things... I've been quite busy with [freemint transition to github](http://freemint.github.io) but that's more or less done. So, in order of probability / importance:
1. #83 (auto floppy reboot)
1. #85  (proper local time handling)
1. #65 (faster "read only" boot image & related things, like fully automated creation of the image)

**Comment by atarijookie** [comment]
Nice :) How about #46 ? Or do you have any tip, where can we get someone who would do the simple interface for CE_FDD.PRG?

**Comment by mikrosk** [comment]
Did you try to ask on AF? You know, that you're specifically looking for someone to write this exact tool with this and that features (i.e. an opposite to "guys, we're looking for GEM programmers, please help us").

It's not that hard, I could even do it but I don't want to waste my time on GEM stuff if there are still active GEM developers, certainly there's more people able to hack an app like that than people willing to hack the ultra fast boot image.
