### ISSUE TITLE
SCSI gets stuck on Falcon after a while of running HD test

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#74]
SCSI gets stuck on Falcon after a while of running HD test - it transfered 200 MB just fine on TT, but got stuck after 100 MB on Falcon - I wonder if it's a problem of a single piece device, or something that might happen on every device.

**Comment by tin-nl** [comment]
I can confirm this with one F030/CE combination.

First run (after cycling both systems): 66.7 MB zransferrred, failed at read with "w4stat failed on reading status byte". Continuing does, well - continue. I'll let it run for a while w/o cycling, let's see what happens...

btw: I could check with another F030, if it's needed.

**Comment by tin-nl** [comment]
The aforementioned test run that choked at 66MB did continue happily until well over 1GB, no further issues.

**Comment by tin-nl** [comment]
Two subsequent tests with 300MB each (both devices powercycled) show no problems, however.

**Comment by atarijookie** [comment]
Thank you for the testing :) I will have to look into that, it's weird...

**Comment by atarijookie** [comment]
Made a release today with the SCSI Xilinx fix, runned fine on my 2 devices - stress test and data validity check test were running for an hour each (so 2 devices * 2 tests = 4 hours) without an issue. Waiting for user feedback if it solves their issue, and if it will, then this will be closed.

**Comment by atarijookie** [comment]
Freezing on problematic device stopped, test runs fine now.
