### ISSUE TITLE
Turn off key click at boot

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#75]
AdamK on atari-forum:
Could we have an option in CosmosEx to kill keyclick at boot? (ie. setable in config, happens at boot)

http://www.atari-forum.com/viewtopic.php?f=103&t=30679

**Comment by miniupnp** [comment]
it is only about clearing the right bit at $484

**Comment by atarijookie** [comment]
plus configuration UI plus saving to config

**Comment by miniupnp** [comment]
yes, that's the hard parts ;)

**Comment by tin-nl** [comment]
Just a thought: does anyone know the motivation behind this request?
 If it's to get rid of the annoying keyclick rampage while the CE's still booting, I'm afraid that we can't do anything about it.

**Comment by mikrosk** [comment]
I also don't follow why this is necessary. I'd close as "wont fix". ;)

**Comment by tin-nl** [comment]
I just contacted Adam to shed light on his requests background.

**Comment by AdamKlob** [comment]
My problem is that keyclick sound is sooo 1985 ;) CosmosEx takes Ataris into XXI century, so, plesae add possibility to kill this annoying 1985 behavior :)

**Comment by mikrosk** [comment]
Even if there's like zillions of ACCs which do exactly that, incl. the official one from Atari?

**Comment by AdamKlob** [comment]
Even so. It is annoying. It has to die :)

Rationale: all that ACCs take valuable memory. One move.w in CosmosEx boot-up code is way better IMO

**Comment by miniupnp** [comment]
but CE_DD will take more memory.. and then someone will ask for CE_DD setting a custom color palette, etc.
just add a .PRG to your auto-folder that turn off keyclick

**Comment by mikrosk** [comment]
Try to look at it this way: if you asked Uwe Seimet to implement it in HD Driver, what would be his answer? ;-) I remember asking him to store NVRAM state for broken Falcons and he said to me that even he would be pleased with that feature (as he has a broken NVRAM in his Falcon) but it doesn't belong to a hd driver, so his answer was no. :-P

**Comment by AdamKlob** [comment]
Well, I asked Didier to do the same (NVRAM fix) for CT60 TOS, and he did it. You can draw your inspiration from there :D

**Comment by ggnkua** [comment]
Please don't turn it off - I loves the ST keyclick!

And I'm willing to be that lots of people will say that too. So then it has to be a configuration option, which means more code than just a move.b. Where's your logic now? :P

**Comment by AdamKlob** [comment]
I don't ask to turn it ofr for everybody - just add an option for the people that want is - mr, myself and I :).

Configuration option only in UI, CE_DD could be generated with or without it. Modular bootsector :)

**Comment by ggnkua** [comment]
So why don't you grab the source and compile a custom version then?

**Comment by AdamKlob** [comment]
I'd prefer to have it mainlined so I do not have to compile my own binaries every time an update comes out. Also, I have a feeling, some other users may benefit.

**Comment by ggnkua** [comment]
And I also have a feeling others will moan that it's bloat, like other people suggested before me...

**Comment by AdamKlob** [comment]
You can have some bloat from time to time. For me CosmosEx is all about features, power wihtout price and bloat :P

**Comment by ggnkua** [comment]
Yeah, so let's stick the mint kernel in there, since it's all about powa!!!111oneoneone

**Comment by miniupnp** [comment]
@AdamKlob I'm not absolutely opposed to this kind of feature, but we have so much more important to do before. So just fork the github repository, do it the right way, (you're right, the ce main app can patch the boot sector before sending it to the ST) and we'll be happy to merge (or squash ;)

**Comment by tin-nl** [comment]
Wow, turned my back for only five minutes and now I seem to have missed a whole party :)
@AdamKlob: I also think this isn't well suited for ce_dd or it's bootloader. **But** implementing an extensible third (or 1.5th) bootsector that loads and runs special PRGs the user could add, well _that_ would be nice. That way no patching is needed, and other features can be added w/o adding bloat to ce_dd (e.g. aforementioned TOS ROM loader). Anyone up for this? (and yes, I heard of that folder named "auto" ;-) )

**Comment by mikrosk** [comment]
> Anyone up for this? (and yes, I heard of that folder named "auto" ;-) )

IMO, this is an overkill, esp. because we have AUTO. I can imagine then a more robust solution, let's allow the user to _write_ to boot drive, with his own AUTO, DESKTOP.INF, default ACCs etc. Again, I look at it from my perspective, I don't use any raw disk, only shared drive and rarely usb stick.

**Comment by atarijookie** [comment]
OK, closing this as it's a wontfix now... If anyone (nudge nudge, wink wink) does this later, we can merge it as suggested.
