### ISSUE TITLE
Allow HDD images to be used on ACSI

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#77]
User request from atari-forum.com:

> I have a quick feature suggestion (I know how small the development team is, and how many of these ideas there are, so I'm not getting my hopes up, just throwing another idea into the hat :) ) In the same way that we can upload and mount floppy images, I'd love to be able to upload and mount a small (say, <100Mb?) ACSI hard drive image file, such as those supported by STeem and Hatari.

[http://www.atari-forum.com/viewtopic.php?f=103&t=29901](http://www.atari-forum.com/viewtopic.php?f=103&t=29901)

**Comment by miniupnp** [comment]
I think it will be very useful : puting a few HDD .IMG on a USB stick
It can work the same way as the "raw" drives, except that the RPi would read/write in the IMG file instead of the /dev/sdX device

**Comment by miniupnp** [comment]
it looks like the necessary code is already there in native/scsi.cpp and native/imagefilemedia.cpp
I'm testing it

**Comment by miniupnp** [comment]
it works !
I now need to add some way to configure it and mount/unmount them easily

**Comment by atarijookie** [comment]
Yeah, I was using that hard drive image thing when I was doing some development back then... The configuration is the thing that worries me most :)

**Comment by miniupnp** [comment]
I've something that works pretty well I think in my hdd_images branch.
I need to modify the configuration tool :)

Also I think I should make a CE_HDIMG.TTP tool to mount .IMG files

**Comment by atarijookie** [comment]
Wow, nice :) I can try that once the whole chain (config - mounter - main app) are done, for now I'm working on other issue...

**Comment by miniupnp** [comment]
I've added the configuration in my [branch hdd_images](/miniupnp/ce-atari/tree/hdd_images)
I still have to do the CE_HDIMG.TTP tool to mount .IMG files directy from the ST.

**Comment by miniupnp** [comment]
https://www.youtube.com/watch?v=m-HMKKRIvNk

**Comment by miniupnp** [comment]
@atarijookie it only needs a bit testing before merging :)

**Comment by atarijookie** [comment]
@miniupnp Unfortunately I can't do the testing now as the other stuff keeps me way to busy, so I suggest to merge it in, let the end user to try the feature, and possibly fix it later :) Soooo... should I just merge it right away, or will you do it? :)

**Comment by miniupnp** [comment]
@atarijookie you can merge right away. But nobody else here can test ? @tin-nl  ?

**Comment by tin-nl** [comment]
@miniupnp: sure, I'll give it a spin later. Any specifics to look at? Any images I should try?

**Comment by miniupnp** [comment]
@tin-nl just try any disk image you'd like :) 
I'm wondering, Is there a disk imaging tool ? I would like to backup my old megafile 44 before it dies

**Comment by atarijookie** [comment]
> I'm wondering, Is there a disk imaging tool?

I'm sure there is some, but if there isn't, it shouldn't be hard to make one, right?

> I would like to backup my old megafile 44 before it dies

Connecting CosmosEx with other devices (Megafile 44) might not work, so you might need to do it in a different way than just bare copy...

**Comment by atarijookie** [comment]
I've merged this and it closed the issue, so I've reopened it :) 

@miniupnp btw., I've also merged your media streaming some months (weeks?) ago, but I haven't tested it. Raspbian image, but I didn't merge in the Atari part (I think) - where can I find it to try it, and does it now work also on ST, or it's STE only still? :)

**Comment by miniupnp** [comment]
@atarijookie I think we should open another issue for the media streaming

**Comment by atarijookie** [comment]
Sure, write down everything you need in the other (media streaming) issue :)

**Comment by tin-nl** [comment]
Looks good so far. Successfully mounted pperas 1GB image and hddrivers demo image. 
The menu entry probably should be called "Harddisk Image" - "Disk image" might be read as floppy disk image by users.

Copied some data on there from shared drive (via TOS 1.04), that failed some files in (only 36 out of 69 copied, albeit there was enough free space). This happened after the last file (well, the file the copy stopped at) was copied:

> TranslatedDisk::onFread - only 410 bytes out of 512 bytes transfered

@jookie: this is probably unrelated to this feature, I guess?

Is there any kind of retry for the mount if it were, say, on a shared drive that comes available a bit later?
If not it would probably be a good idea to show a warning if a disk image drive is resided in /mnt/shared/.

Other than that this looks great, good work! :)

**Comment by tin-nl** [comment]
Oh, and a warning in the config if the file does not exists (aka user can't type), would be nice, too :)

**Comment by tin-nl** [comment]
Just found one bug by chance - it seems entering the "Floppy Config" and exiting with cancel clears the "Disk Image" path I entered there. 
Also the display of Floppy Config doesn't clear the screen anymore before drawing (but this might be dure to the webconfig I'm using).

**Comment by tin-nl** [comment]
Succesfully booted&run STMint.06.img as found on atari-forum.com. This was broken a while back.

**Comment by miniupnp** [comment]
thank you for the feedback.
I'm going to try to fix the few issues you've found
I'm also wondering if we should support mounting several (up to 8) RAW drives / IMG on the same ACSI/SCSI ID, but with different LUN.
At least HDDRIVER support this.

**Comment by atarijookie** [comment]
> TranslatedDisk::onFread - only 410 bytes out of 512 bytes transfered
> this is probably unrelated to this feature, I guess?

Ow crap, that's not good. I should look at that...

> I'm also wondering if we should support mounting several (up to 8) RAW drives / IMG on the same ACSI/SCSI ID, but with different LUN.
> At least HDDRIVER support this.

I wouldn't recommend that - the other drivers (ICD Pro, PPera's driver) don't support that AFAIK, so I would stick to using one image per one ACSI ID...

**Comment by miniupnp** [comment]
I think we can close this, except if someone founds more bugs. @tin-nl  ?

**Comment by atarijookie** [comment]
I got a question based on user input (through e-mail) - what happens, if you mount .ST floppy image through this feature? OK, and while I was writing this question, I realized it will not work :-D as the floppy image might have a different geometry as a hard drive, which will just confuse the TOS....

Now that I'm thinking about it, there could be some magical piece of code, which would extract all the files and directories from the floppy, create a GEM hard drive image out of it, mount it, and on eject it could do the reverse - for easier work and editing of floppy images. I know, it's a lot of work, nobody is suggesting that anybody should do it, but at least we know how it could be done :-D 

OK, just ignore me, I'll answer the user and no additional work needs to be done here regarding this feature.

**Comment by tin-nl** [comment]
@miniupnp: I didn't do more tests; we can always reopen if sth arises.

**Comment by miniupnp** [comment]
@atarijookie you can mount any file through this image... just that the ST will not boot it.
and hd drivers will not understand it :)

about the floppy I just don't understand why you don't extract the floppy to a directory (on a translated drive) with mtools. You can copy back to the .ST image with mtools too.

**Comment by atarijookie** [comment]
@miniupnp hmm, mtools - didn't know about that one - might be an easy feature then :)

**Comment by miniupnp** [comment]
@atarijookie I guess a .ST can even be mounted under linux.
`# mount /path/disk.ST /mnt/floppy -t msdos -o loop`
