### ISSUE TITLE
CE_DD isn't compatible with 040 / 060 accelerator

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#8]
CE_DD will probably fail (I've never tested that, don't have an accelerator) with 040 or 060 accelerator. This might have something to do with the caches or memory manager or something, I don't know - MiKRO and ggn had some ideas, both know those CPUs...

**Comment by mikrosk** [comment]
It seems I'm going to get a CT60e in following weeks so I might take a look at this finally.

**Comment by mikrosk** [comment]
Good news sweeties, the CT60e did arrive so I can definitely help with debugging.

**Comment by mikrosk** [comment]
A bit late to the party but I can't see one thing failing on the CT60 which works in 030 mode... so if there are any reports, I'm all ears otherwise I pronounce CE as CT60 compatible. :) (the thread on AF seems to be about AB040 issues and that card is a world of its own...)

**Comment by ggnkua** [comment]
I'll see if I can set up my ct60 this week and verify this

**Comment by ggnkua** [comment]
Okay, I just ran as many tests I could here on the ct60, everything seems to be working fine.

So unless anyone else has an objection we can close this down and open a new one for 040 accelerators.

**Comment by mikrosk** [comment]
thanks @ggnkua, one problem less to worry about!
