### ISSUE TITLE
Do we have a kernel build settings / headers for Yocto?

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#80]
Right now, if I want to build  a kernel module (I need it for my wifi dongle which is newer than the kernel itself so just copying the firmware dir wont help) I can only hope that downloading the kernel from https://github.com/raspberrypi/linux (in its appropriate branch), doing 'make prepare' and 'make modules' with all the default settings wont break anything (plus I lost symbol names and dependencies for sure).

Raspbian (and all the other distros) usually provide a package called "linux-headers" which contains all the necessary stuff for building modules, there's even a script called RPi Source (https://github.com/notro/rpi-source) which automates everything. Do we have something like that for the Yocto builds? The aforementioned script needs some python libs which aren't available...

Again, with a cross compiler I'd compile a new kernel in a few minutes but right now, I'm scared to experiment. :D

**Comment by atarijookie** [comment]
Mikro, quit experimenting with Yocto, headers and other bullshit, download and flash Raspbian:

> https://www.dropbox.com/s/sq7bwh4ps51m17v/ce_raspbian_2016-11-10.zip?dl=0

Then you can use wifi probably without problems, have headers and standard tools from Raspbian.

**Comment by mikrosk** [comment]
Sweetie, had you mentioned this before (hint: your website), I'd have done it for sure. ;)

**Comment by atarijookie** [comment]
...and if you buy a Raspberry Pi 3 and use it with that Raspbian, you will get 400% compilation speed ;) (4 cores - make -j4)

**Comment by mikrosk** [comment]
`apt-get install raspberrypi-kernel-headers` is the way to go on Raspbian (beware, do not look for the generic linux-headers-\* package, Raspbian doesn't use the Debian packaging for kernel and headers). Closing.
