### ISSUE TITLE
CE_FDD is unable to download selected disk images

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#81]
According to Jookie it's because the FTP server is down. Perhaps we could switch to http://www.exxoshost.co.uk/atari/games/index.htm ?

**Comment by atarijookie** [comment]
Updated imagelist.csv on server to point to exxoshost.co.uk
Added code to master/ce_main_app, which should extract the floppy image from downloaded ZIP file. Not tested.

**Comment by mikrosk** [comment]
I'd test it but it hasn't been pushed. :) Ideally, if you could make a separate branch for each feature -- that way I could test the separate feature/bugfix only.

**Comment by atarijookie** [comment]
I forgot to push it, sorry ;) 

It's here:
https://github.com/atarijookie/ce-atari/blob/master/ce_main_app/downloader.cpp#L178-L233
...and as mentioned, it's not tested yet. I also thought about having a similar (or even that?) code in the floppy/floppyimagefactory.cpp, which would allow to upload the ZIP file to slot, floppyImageFactory would unZIP it and then use the appropriate image loading class...

**Comment by miniupnp** [comment]
we could use https://nih.at/libzip/libzip.html to read floppy inside .zip file.

(I think such library  should also be used to improve the "mount zip as dir" feature of translated disks)

**Comment by atarijookie** [comment]
Yeah, that would be ideal, but it would be more complicated than using the unzip command... In the 'mount zip as dir' feature would be even nicer (and less work) using fuse-zip, which would work fine on Raspbian, but I'm sure about Yocto (I guess there isn't support for fuse).

**Comment by mikrosk** [comment]
> which would work fine on Raspbian, but I'm sure about Yocto (I guess there isn't support for fuse).

If there are no other issues preventing people from upgrade (except the not-yet-so-smooth upgrade process), I would forget about Yocto compatibility as whole. There so much work to be done that worrying about backward compatibility for such a huge transition isn't just worth it.

What I would do is to make a separate branch to which only critical bugfixes would go. All the candies would go to the master (raspbian). In that way you don't have to worry about breaking anything but it requires some discipline (one bugfix per branch/commit so you can easily merge/cherry pick it).

**Comment by atarijookie** [comment]
As mentioned month and half ago: Updated imagelist.csv on server to point to exxoshost.co.uk
May god repay Exxos for that ;) ('Pan boh zaplat' in Slovak language)

The ZIPed images moved from downloader to floppyImageFactory, so now ZIPed floppy images are supported through CE_FDD.PRG and also through web floppy interface :) Tested on Raspbian, closing.

**Comment by mikrosk** [comment]
Finally I was able to test it, works great!
