### ISSUE TITLE
CE_FDD.TTP shouldn't bother the user with reset and ALT

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#83]
The feature how one can double click on a MSA files and automatically mount it -- gold! But the fact we ask him to do the reset manually and press the ALT key afterwards, that's lame. Perhaps we should automate this a little.

**Comment by miniupnp** [comment]
you are thinking like storing a magical value somewhere in ram and doing a soft reset ?

**Comment by mikrosk** [comment]
Yeah, basically mount & wait for the game to load, no space bar, no reset.

**Comment by atarijookie** [comment]
@mikrosk Hey buddy, how's this task and the #73 going? ;) You have a lot of plans ahead of you few weeks ago :-D

**Comment by mikrosk** [comment]
@atarijookie I've seen this question coming. ;-) It's just I work on multiple things -- [EtherNE MiNT/MagicNet driver](https://github.com/mikrosk/etherne) for my network card, [ct60tos cleanup](https://github.com/mikrosk/ct60tos) and your project. Usually I can take a look on weekends only so you can imagine. But I haven't forgotten, not at all -- the features are actually something *I* want to use. ;)

Btw when it comes to #73, most annoying show stopper for me is the bug in your code, actually. You pass ST scancodes as PC ones which messes up special keycodes like arrows. If I fix it, it works but suddenly 'fire' emulation stops working. Without this the task would be finished weeks ago; I just haven't found time to investigate.

**Comment by atarijookie** [comment]
@mikrosk @ggnkua @tin-nl Guys, how to perform the software reset (from C / assembler on ST)? That would be the easy part...

About skipping the CE_DD boot - I'm not sure how to do that. I could send something to linux app, so the next boot attempt of CE_DD would result in CE_DD not booting from the device, so you won't have to press ALT, but I'm worried about this resulting in some situations, where the CE_DD wouldn't then boot for one reset / boot cycle when user already changed his mind. 

And that wouldn't even prevent booting from SD card, where skipping / disabling one boot cycle would be more difficult, as that is handled directly in the Franz chip. I wonder if this feature is worth the effort and possible problems?

I would add the reset part and skip the 'not pressing ALT' part...

**Comment by mikrosk** [comment]
Since CE controls everything - Floppy, CE_DD and IKBD - what about reversing the behaviour? I.e. if you press a magic key during the floppy boot (CE knows it has mounted an image), floppy boot gets ignored otherwise CE gets ignored.

That way you solve another annoying issue and that would be auto boot working only on the first boot.

There can be even two magic keys - one for not disabling CE and one for not disabling CE *and* unmounting the floppy image.

The latter suggestions reminds me - how CE handles situations when floppy image has a bootable boot sector? IIRC in case of real floppy there was no cure against that other than removing the floppy (otherwise hard disk would never get a chance to boot).

**Comment by atarijookie** [comment]
For the last question - there is no cure, just eject the floppy image / change the floppy slot. For the things before that - you will explain that to me when we meet next time, because I'm not getting it here right now ;)

**Comment by atarijookie** [comment]
btw., you still could tell me more about the only thing I'm sure will be the easiest and straightforward - how to do the software reset of ST?

**Comment by mikrosk** [comment]
To be honest, I have never done that. ;-)

**Comment by ggnkua** [comment]
```move.l $4.w,a0```
```jmp (a0)```

This basically jumps into TOS start, which part of its duties is to fully reset the CPU and peripherals

**Comment by atarijookie** [comment]
Thanks @ggnkua , will try and add that 👍 

But wait, isn't that just some variable in memory? Atari Compendium on page 724 (of pdf) says this:
0x00000004 LONG ROM Reset: Program Counter

**Comment by ggnkua** [comment]
> But wait, isn't that just some variable in memory? Atari Compendium on page 724 (of pdf) says this:
0x00000004 LONG ROM Reset: Program Counter

Yup, this actually points to TOS' startup (boot) sequence. Like I said, this fully resets the machine as if you pressed the reset button. RAM TOS loaders do the same thing btw, just load the image and jump to the start of the code :).

The equivalent code would be ```jmp $fc0000``` or ```jmp $e00000``` depending on TOS version, but this is always stored in $4.w anyway, so might as well use it

EDIT: If we want to be really anal about it, $4 holds $fc0030/$e0030, but the start of the TOS images have a jump to these addresses, so it's the same thing!

**Comment by atarijookie** [comment]
Awesome, thanks for the explanation 👍 will use it!

**Comment by atarijookie** [comment]
Reset and possible cancel added. Not sure if will do the rest (automatic skipping of drive boot). Closing for now, if someone will want to do the rest, he might reopen this, work on it in branch and create pull request for review and approval process ;)
