### ISSUE TITLE
ENTER/RETURN should be equivalent to 'Save'

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#84]
Now it's pretty awkward -- you edit a field, press enter and you see a strange character instead.

**Comment by mikrosk** [comment]
Similarly, ESC could pose as Cancel.

**Comment by atarijookie** [comment]
Esc and Enter work on the whole page as 'Save' and 'Cancel', but it seems you would like them to work in a similar way on individual items. Feel free to work on this one :)

**Comment by mikrosk** [comment]
Yes, I've noticed that ENTER changes value of boolean items but if you're in a text field, it gets accepted as another character. Btw this is related to #73, where we need the exact opposite -- if you're specifying an UP key and it happens to be ENTER (or up arrow or whatever), we _want_ to have it accepted as a key.

**Comment by atarijookie** [comment]
Done in master now. It doesn't act as SAVE, but at least it goes to next component, which feels like you just finished editing the current text...

**Comment by mikrosk** [comment]
Thanks Jookie!
