### ISSUE TITLE
RPi's local time shouldn't be UTC

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#85]
Right now it works like this: RPi's time is synchronised but into UTC. CE_CONF allows the user to specify the UTC offset so Atari gets correct time.

It should be the other way around -- the user specifies the UTC offset all right but then the device is set to that time and the CE just reads it!

This causes `make` a lot of headache plus it looks lame, esp. here in Australia where I have time shifted by 10 hours from UTC. :)

**Comment by miniupnp** [comment]
@mikrosk I don't know how to set RPi localtime easily...

**Comment by miniupnp** [comment]
ah ok, I think is is done by setting the TZ environment variable. On raspbian it may also use /etc/localtime.
@mikrosk What if you change your TZ value when you login to make ? :)

**Comment by mikrosk** [comment]
Hehe, I was just thinking about this one yesterday. I think The Cleanest Way would be to set the timezone from CE_CONF. So you type "Europe/Bratislava" or "Australia/Brisbane" and it will basically set the correct timezone on the Pi.

**Comment by mikrosk** [comment]
Right now I have offset = 0 and time set via command line so I have more or less exactly what I wanted but not everyone can do that. :)

**Comment by atarijookie** [comment]
Closing, when someone will work on this later, he can reopen it :)
