### ISSUE TITLE
Update process user notification improvement 

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#86]
The current update process is still confusing / not very clear - it's because we can't send the real progress to ST when the device is updating. So there are 2 things I would like to do:

1) let the update download screen be shown for at least 3 seconds, letting the user press Enter / Escape one more time to confirm the update after download (or something similar) - now when the download is too fast, the download screen stays in a broken state and the update might look like it just hangs...

2) let the CE_CONF know what components will be updated, and then show fake progress:
- 50 seconds for Xilinx
- 10 seconds for Hans and 10 seconds Franz
- possibly 10 seconds (didn't measure this) for app
- just show some progress bar / percents or something... 
- add another 30 seconds after that - if it didn't get back to working state, this will be something like a safe time to consider it to be failed...

**Comment by mikrosk** [comment]
IMO, 2.) can be easily solved by a simple screen which would just tell you what is the expected time of update (like the values you mention) and show a timer.

Then users can report bugs like "even though the timer says 2 minutes, update still didn't finish" or "update took unusually long, instead of the usual 30s it took one minute" instead of "I was staring at the progress bar, then it finished, then nothing and then I got a failed message". Ideally, this "timer screen" would have a RESTART / CANCEL buttons.

**Comment by atarijookie** [comment]
Made changes to CE_CONF.PRG, main app config, download showing, termination delay, ce_conf on rpi improvements. Main app not tested with improvements of CE_CONF.PRG, have to do this on real HW.

**Comment by atarijookie** [comment]
Made few fixes to issues caused by adding additional isUpdateScreen + updateComponents flags to the update screen.

**Comment by atarijookie** [comment]
Made more fixes with real CE_CONF.PRG - was totally broken, now seems to be better.
Added timeout for app restart after update.
Added heartbeat component in the upper right corner to show if the screen was just updated (stream was retrieved). 

**TODO:** Refresh doesn't seem to happen on ST using CE_CONF.PRG - this might cause that update components versions are not refreshed automatically, also that the update download progress is not updated automatically. 

@tin-nl Would it be hard to add a single javascript timer somewhere in the web/config terminal, so when no key is pressed, the refresh is called? I could handle the refresh on CE C++ code, I'm just having trouble with adding the JavaScript timer thing. If it would be less than 10 minutes of work, then a diff would be nice, I will finish the rest :) If it would take longer, then screw it (for now...).

**Comment by atarijookie** [comment]
Refresh fixed - mising of supervisor, BIOS, GEMDOS - not good. Now in supervisor only for a short needed time, calling only GEMDOS as it's not in supervisor anymore. 
Also showing the update titles before they all need to be show - let's the user know what will be updated, how long will it take. 

Seems much better now. Closing.

**Comment by mikrosk** [comment]
@atarijookie: out of curiosity, why do you need to be in SV when calling GEMDOS?

**Comment by atarijookie** [comment]
> out of curiosity, why do you need to be in SV when calling GEMDOS?

I don't need that - it was just the silly old way of doing things - switch to SV, do everything, when quiting switch back to user mode. But as mentioned, GEMDOS has issues when called from SV, and as I remade that, the issues with keyboard vs refresh disappeared :)
