### ISSUE TITLE
CE app should wait for the system

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#87]
I have a wifi dongle and the boot process is quite painful with it (if I don't have an Ethernet connection as well). 

There are several problems:
1. CE starts during the boot process, what leads to choping the CPU and CE not being able to receive / send ACSI commands ... sometimes that results into "CE boot..." and waiting for several seconds (20-30!) or just booting into empty desktop
1. CE doesn't see wlan0 interface
1. User have no idea what's happening because CE LEDs say everything is OK but it is not

I've been told that you it was your idea, @tin-nl plus I don't know a shit about the init modules so please, can you change it to start as a normal, user-space app, i.e. decrease its runlevel and/or add the dependencies for NFS & friends? Speeding up the boot process isn't an excuse, it reminds me the infamous Pentium joke "2+2=5, it's not correct but still very fast!" :)

See the log:

00010575 00000001 (2016-11-18 06:20:24.150217)  CosmosEx starting, version: 2016-11-13
00011594 00001019 (2016-11-18 16:20:25.169593)  Utils::copyFile - failed to open source file /tmp/zipdir1/CRASH/CRASH.MSA
00011595 00000001 (2016-11-18 16:20:25.170254)  ImageSilo::loadSettings - didn't load image /tmp/zipdir1/CRASH/CRASH.MSA
00011614 00000019 (2016-11-18 16:20:25.189279)  NetworkSettings::updateResolvConf -- didn't update resolv.conf - network settings are DHCP
00011926 00000312 (2016-11-18 16:20:25.501003)  Side / Track out of range, returning empty track. Franz wants: [track 0, side 0], but current image has only: [track 0, side 0, sectors/track: 0]
00014680 00002754 (2016-11-18 16:20:28.255333)  Side / Track out of range, returning empty track. Franz wants: [track 0, side 0], but current image has only: [track 0, side 0, sectors/track: 0]
00018980 00004300 (2016-11-18 16:20:32.555496)  CCoreThread received weird ATN code fe waitForATN()
00018981 00000001 (2016-11-18 16:20:32.555903)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00022184 00003203 (2016-11-18 16:20:35.758921)  CURL curl_easy_perform() failed: Couldn't resolve host name
00022900 00000716 (2016-11-18 16:20:36.475379)  Downloader - download of http://joo.kie.sk/cosmosex/update/updatelist.csv didn't finish with success, deleting incomplete file.
00022990 00000090 (2016-11-18 16:20:36.565114)  CCoreThread received weird ATN code fe waitForATN()
00023090 00000100 (2016-11-18 16:20:36.665206)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00041880 00018790 (2016-11-18 16:20:55.455297)
     LOG_ERROR occurred
     Time since beginning of ACSI command handling: 2810
     Time between this and previous ACSI command  : 60
00041880 00018790 (2016-11-18 16:20:55.455297)  waitForATN 03, but received fe! Fail!
00041880 00000000 (2016-11-18 16:20:55.455765)  CConSpi - didn't TX/RX enough data, padding with 16 zeros! Fix this!
00045570 00003690 (2016-11-18 16:20:59.145173)
     LOG_ERROR occurred
     Time since beginning of ACSI command handling: 3689
     Time between this and previous ACSI command  : 2811
00045570 00003690 (2016-11-18 16:20:59.145173)  waitForATN 03, but received fe! Fail!
00045620 00000050 (2016-11-18 16:20:59.195678)  CConSpi - didn't TX/RX enough data, padding with 16 zeros! Fix this!
00047490 00001870 (2016-11-18 16:21:01.065144)  CCoreThread received weird ATN code fe waitForATN()
00047620 00000130 (2016-11-18 16:21:01.195425)  CConSpi - didn't TX/RX enough data, padding with 16 zeros! Fix this!
00052404 00004784 (2016-11-18 16:21:05.979147)
     LOG_ERROR occurred
     Time since beginning of ACSI command handling: 4783
     Time between this and previous ACSI command  : 5740
00052404 00004784 (2016-11-18 16:21:05.979147)  waitForATN 03, but received fe! Fail!
00052404 00000000 (2016-11-18 16:21:05.979634)  CConSpi - didn't TX/RX enough data, padding with 16 zeros! Fix this!
00054480 00002076 (2016-11-18 16:21:08.055166)
     LOG_ERROR occurred
     Time since beginning of ACSI command handling: 2075
     Time between this and previous ACSI command  : 4784
00054480 00002076 (2016-11-18 16:21:08.055166)  waitForATN 03, but received 01! Fail!
00054480 00000000 (2016-11-18 16:21:08.055678)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00057940 00003460 (2016-11-18 16:21:11.515309)
     LOG_ERROR occurred
     Time since beginning of ACSI command handling: 3459
     Time between this and previous ACSI command  : 2076
00057940 00003460 (2016-11-18 16:21:11.515309)  waitForATN 03, but received fe! Fail!
00058050 00000110 (2016-11-18 16:21:11.625226)  CConSpi - didn't TX/RX enough data, padding with 16 zeros! Fix this!
00062840 00004790 (2016-11-18 16:21:16.415239)
     LOG_ERROR occurred
     Time since beginning of ACSI command handling: 2830
     Time between this and previous ACSI command  : 1440
00062840 00004790 (2016-11-18 16:21:16.415239)  waitForATN 03, but received fe! Fail!
00062920 00000080 (2016-11-18 16:21:16.495614)  CConSpi - didn't TX/RX enough data, padding with 16 zeros! Fix this!
00066240 00003320 (2016-11-18 16:21:19.815239)
     LOG_ERROR occurred
     Time since beginning of ACSI command handling: 3319
     Time between this and previous ACSI command  : 2911
00066240 00003320 (2016-11-18 16:21:19.815239)  waitForATN 03, but received fe! Fail!
00066340 00000100 (2016-11-18 16:21:19.915443)  CConSpi - didn't TX/RX enough data, padding with 16 zeros! Fix this!
00069860 00003520 (2016-11-18 16:21:23.435222)
     LOG_ERROR occurred
     Time since beginning of ACSI command handling: 3520
     Time between this and previous ACSI command  : 3419
00069860 00003520 (2016-11-18 16:21:23.435222)  waitForATN 03, but received 01! Fail!
00070020 00000160 (2016-11-18 16:21:23.595273)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00072020 00002000 (2016-11-18 16:21:25.595238)
     LOG_ERROR occurred
     Time since beginning of ACSI command handling: 2000
     Time between this and previous ACSI command  : 3680
00072020 00002000 (2016-11-18 16:21:25.595238)  waitForATN 03, but received 02! Fail!
00072070 00000050 (2016-11-18 16:21:25.645540)  CConSpi - didn't TX/RX enough data, padding with 24 zeros! Fix this!
00072720 00000650 (2016-11-18 16:21:26.295709)  Mounter::mount - mount failed. (mount dir: /mnt/shared)
00072721 00000001 (2016-11-18 16:21:26.296130)  Mounter::mount - mount error : Connection timed out
00072721 00000000 (2016-11-18 16:21:26.296432)  Mounter::mount - type=nfs source='192.168.20.5:/srv/nfs/ce-share' options='nolock,addr=192.168.20.5,nfsvers=3'
00072765 00000044 (2016-11-18 16:21:26.340205)  readHeader couldn't synchronize!
00083987 00011222 (2016-11-18 16:21:37.562085)  CURL curl_easy_perform() failed: Couldn't resolve host name
00083993 00000006 (2016-11-18 16:21:37.567955)  Downloader - download of http://joo.kie.sk/cosmosex/update/updatelist.csv didn't finish with success, deleting incomplete file.

**Comment by tin-nl** [comment]
Sure, I'll have a look.
Two questions on this, @mikrosk:
-which PI are you using?
-2 is especially worrysome (because it might hide another regression) - IIRC we implemented sth way back to handle the Wlan interface always coming up late even in the yocto boot process due to DHCP. Do you mean the CE sees no interface at all (e.g. even after a while?) or "just" at startup? Unrelated to this specific bug report CE main should recognize an interface coming up after ce_main is started.

**Comment by atarijookie** [comment]
Maybe I could add some script at the end of boot of linux, which would store something to /tmp, e.g. /tmp/linuxBootIsFinished, and until that time the CE main app wouldn't do any tasks which could cause issues, e.g.:
- not restarting eth0 and wlan0 until then
- not retrieving time, update versions, other stuff from the internet
- not mounting shared drive 

That way the CE main app could start soon(er), but it would do all these tasks after the linux has fully booted. What do you thing, @mikrosk & @tin-nl ?

**Comment by mikrosk** [comment]
@tin-nl : it's the B+, running Raspbian. wlan0 (internet) eventually comes up, it's just the boot process is lying. For instance it's totally normal to see "no wlan interfaces" and then open ce_app and fetch a web update. really confusing. another use case is that I open up the shared drive, waiting ages to open it or even see the infamous mount.err.

@atarijookie: I think this is all solvable within the init system, systemd is pretty flexible, you can surely specify even specific network interface to have online for the cosmosex unit. if you're referring to it as an option to have reasonably fast booting while not confusing the user then sure, this is the way to go. I think you can even tell systemd to to it for you, i.e. after a stage which interests you to do some action (write to a log or something similar)

**Comment by miniupnp** [comment]
That is possible to start the ce-main app before the Network interface is fully up and run specific tasks when the interface goes UP/DOWN.
It would also help when the network cable is plugged after start or so... 
See what I've done for miniupnpd : 
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/linux/ifacewatcher.c

**Comment by mikrosk** [comment]
One of the things I'm not sure about is the shared drive -- if we start the desktop before [wlan] network, what to do? Do a progress bar similar to ZIP depacking?

**Comment by atarijookie** [comment]
Well, I would leave that at current state - show the (empty) content when not mounted yet (or error message file), and later just show the mounted drive. There is a retry on connecting shared drive, so nothing should be needed to be added to make this mount retry to work...

**Comment by miniupnp** [comment]
we could even change the icon label with "mounting". The user would know he needs to reboot later

**Comment by mikrosk** [comment]
One more thing, somewhat related -- one of the most annoying things is that keyboard doesn't work until  CE app is active (what make sense). Would it be, somehow, possible to make an early start for the IKBD emulation (just forwarding packets) so for instance CTRL+ALT+DEL works?

**Comment by atarijookie** [comment]
> Would it be, somehow, possible to make an early start for the IKBD emulation (just forwarding packets)

This would require a simple HW change, which you might be able to do yourself, but as I didn't think of this sooner, no other device has this change yet. I don't meet this issue as I power up the device before my ST with a separate supply, so I didn't think that it needs a solution. So I might make this HW / FW patch in the future so individuals might be able to apply it.

**Comment by mikrosk** [comment]
>  So I might make this HW / FW patch in the future so individuals might be able to apply it.

Thanks a lot! Btw why not to make it default? Is there any side effect when keeping this as default?

**Comment by atarijookie** [comment]
> Btw why not to make it default? Is there any side effect when keeping this as default?

It will be a default for all the next devices, which will have (might have) this new feature :) It can't be default for older devices (and current devices), because they lack this HW patch...

**Comment by tin-nl** [comment]
@mikrosk:Just had time to follow up on 1), but with my raspbian image, not jookies. And on Pi1.
I failed to see the mentioned behaviour due to early startup and CPU overload ( which doesn't mean it isn't there). I have to check this with jookies image, but in the meantime: how exactly do you see that this is due to CPU load? Do you have any logs? Just to make sure I don't miss any obvious signs on my setup.
I think we should break down that behaviour into two things:
A) ST doesn't get answer from ACSI because CE isn't ready (the 'normal' cause of the empty desktop). This is because CE can't switch to standalone mode temporarily at boot and needs ce_main to forward ACSI commands. IIRC this is hard to solve via software,the firmware must be changed for this (have a look at the standalone rule in there, IIRC it is timeout based with no option to switch back IIRC), we discussed that in another bugreport.
B) ce_main should be ready but doesn't answer in time. Haven"t seen this yet, have to investigate.

**Comment by mikrosk** [comment]
@tin-nl: I think it's all related to that wifi dongle. I didn't experience this when Ethernet cable was attached. That's the problem here -- I think something goes wrong with the init order and while kernel is busy doing some wifi magic, ce_app blatantly pretends everything is fine and trying to start what leads to all sorts of  problems. I could live with the fact that the LEDs signalise "please wait, don't reboot yet" but the problem here is that the LEDs pretend like everything is fine while I can't use the ST at all.

**Comment by tin-nl** [comment]
@mikrosk: interrestingly, my wifi setups show no such behaviour as described in 1) - even with jookies new image, just retested several reboot cycles with and withoud ST SD card inserted. 
Again: I'm not saying it doesn't exist, just that it's probably hard to check on my end what exactly happens. It might need a RPi2 or your Wifi dongle chipset to have that behaviour. Which chipset is that, btw?

`that the LEDs pretend like everything is fine while I can't use the ST at all.`
That's of course bad. But please keep in mind that the blue LED never indicated network or mount status - so this leaves only 1) as the main issue. A rather puzzling one at that. Do you have any ce-logs showing this behaviour? Dropped ACSI packets or anything?

If we have to introduce a wait, it should be configurable (e.g. "Fast boot - warning, here be dragons"), default mode is slow boot. That also means that the wait should be introduced by ce_main itself (as it has to read its config) much like jookie proposed in comment no 2.

**Comment by mikrosk** [comment]
I'll give it a bit more testing, good to know it works for you. Too bad kernel logs use other time stamp format than we do, so it's hard so sync what's happening but I'll do my best. I can reproduce it any time -- basically what I need to do is to switch on the STE, wait for 2-3 minutes (!) and then I can be sure everything will work OK (no waiting in the boot phase, recognised wlan0, mounted NFS).

First I thought it's caused by the slow NFS mount (https://github.com/atarijookie/ce-atari/wiki/How-to-make-NFS-shares-working-(Linux), see below) but even if I add the parameter & recompile, it didn't change anything. I use rtl8192eu on totally updated system (rpi-updade, apt-get upgrade/dist-upgrade).

**Comment by tin-nl** [comment]
i've tested with rtl8188cus and the rtl8192cu driver (back then and now). it takes Wifi 90secs to get from boot to "up". So the chipset is probably close enough. But this also means that it's not the early start per se causing this, as it probably could happen anytime.

>  on totally updated system (rpi-updade, apt-get upgrade/dist-upgrade).

Now _thats_ an interresting tidbit of information you withold from us :-) All the tests back then and now were done with the kernel in jookies image. Could you possibly mail me a link to your image? I guess this is not based on jookies image (because it's /boot is too small to successfully run rpi-update)? 

Another question: you mention "ce_boot" - your ACSI ids are configured how exactly? I use SD-RAW-DD (0 to 2) and a bootable hddriver SD card is inserted. Is your C drive a raw or an sd?

**Comment by mikrosk** [comment]
>  I guess this is not based on jookies image (because it's /boot is too small to successfully run rpi-update)?

First I didn't get why would think so but then it hit me -- yes, I did enlarge the partition first (very easy procedure) so I could install all the other candies. Right now I have the CE mounted again in the STE but I didn't do anything specially, really: apt-get update && apt-get install rpi-update && apt-get upgrade; reboot; rpi-update; reboot.

This updated the kernel, made my wireless dongle non-working (custom kernel module...) so I installed `rpi-source` plus NFS started to be reaaaally slow and that's how I actually realised something fishy is going on. Now I mention it, yes, I should have write it, right. ;)

**Comment by tin-nl** [comment]
@mikrosk: Quick update: still can't reproduce 1), even with upgraded raspbian.
But found a way to reproduce your suspected root cause - the Wifi connect forces the HD test to retry one or even two times (in the same run), although without producing an error. Still have to check if this is related to every ifup (aka also happens when configuring and thus restarting wifi) or just the usb initialization.

**Comment by mikrosk** [comment]
@tin-nl: OK, I managed to image the card: http://mikro.atari.org/private/ce.img.gz

With this one I can always reproduce the CPU choking. However, there's one strange issue which puts some doubt into the logs -- for some reason, time seems to be delayed by minutes. So I power cycle the CE, get shell and I see a log from 10 minutes ago (there's no way the boot process took so long). First I thought /var/log/ce.log is just a copy of something but nope, it's really written there. I even `rm -rf`ed thole /var/log to be sure before next power cycle. Timestamp code seems right so I have no logical explanation for it. `date` returns normal time, day/month/year in the log is ok.

Anyway, the usual boot procedure is like this:
- power cycle
- ~20 seconds later I see the LED indication that CE has started
- I reboot the STE, sometimes I get straight into "CE boot..." but most likely it takes another ~15 seconds to "warm up" (in the meanwhile I see either a white screen or an empty desktop)
- ~40 seconds from the LED indication I'm finally able to see "CE boot..."
- ~35 seconds later I can see the boot header, following with (normal) desktop (without wlan0)
- it takes ~30 more seconds to get wlan0
- usually ~10 more seconds to get an IP

So all in all, usually it takes about 2.5 minutes to get a fully working setup. I could live with that (it's not CE's fault after all) but the symptoms, these really scary me. :)

If you find time to try my image and test, I'll be super grateful!

**Comment by tin-nl** [comment]
@mikrosk: K, great, thanks! I downloaded the image and will commence some test with that one. 

I can report that even _reconfiguring_ WiFi (e.g. changing APs) produces these chokes. So it's very likely that there are more problems on the horizon with WiFi - we can't tune niceness for drivers AFAIK.

Can you do me a favour and try this:
1. boot your CE "normally" with WiFi (aka untill you have an IP address)
2. start the ce_tsthd.prg on your ST in detailed report mode and let it run
3. meanwhile, enter the config of your CE either via shell or webinterface 
4. configure the network settings to another AP and save - might also work with configuring a nonexisting AP, save and reconfigure the old one and save (shell ofcourse)
5. observe if the hdtest chokes with retries (number instead of a star) and for how long

Should be interesting to see how bad it chokes in your environment.

**Comment by mikrosk** [comment]
@tin-nl: yep, your hunch was right. If I change the SSID, I get one "1" instead of "*", so choking does occur.

**Comment by tin-nl** [comment]
@mikrosk: just had a quick test with your image (on PI1B with CE v1) - now I get almost exactly the behaviour you described. Additionally I get the following:
-unusual long steady (e.g. non-flickering or very fast flickering, hard to say) HDD light, even for a few seconds
-dropouts of IKBD 
And the kicker: I seem to get this even without any network attached,
Note: I left your config as is - meaning, CE can't connect NFS and WiFi, but tries to.

I had none of this with an upgraded Raspbian (rpi-update, apt-get upgrade etc.),
Also, none of this happens with Jookies image; switching image is enough to produce/get rid of these symptoms here,
 
There is surely something in your image choking up ce_main, but it might not be WiFi. But it's a bit early to say for sure, I hope I'll find some time to look into this a little bit deeper in a few days.

**Comment by tin-nl** [comment]
@atarijookie; regarding the WiFi chokes when changing APs - is there anything on ST side (TOS, ce_dd, ce_boot) that you know of, that doesn't retry? I am not sure if we can prevent CPU usage spikes by drivers, even if ce_main were a kernel module...

**Comment by mikrosk** [comment]
@tin-nl: wow, that's a fascinating discovery. I can't think of anything which could result in some dramatic difference. That being said, maybe I *did* screw up something but I just don't remember. I'll try to `dd` Jookie's image, write down every step I do and if the problem reappears, ask you to do the same. ;)

**Comment by mikrosk** [comment]
Hmm. Now this is getting more and more interesting.

1. `dd` ce_raspbian_2016-11-10.img (md5sum: 9a499d781157b698720f4b44a775c084)
1. apt-get update && apt-get upgrade && apt-get dist-upgrade
1. reboot
1. raspi-config -> expand
1. reboot
1. apt-get install raspberrypi-kernel-headers joe mc git
1. Install the kernel module: https://github.com/atarijookie/ce-atari/wiki/How-to-compile-a-kernel-module-(Raspbian)
1. Setup wireless networking and shared drive in CE_app
1. reboot

I'm getting basically the same behavior, I even didn't have to install/run `rpi-update`.

```
ce_raspbian # cat /var/log/ce.log 
00010824 00010824 (2016-11-25 03:13:21.440701)

---------------------------------------------------
00010825 00000001 (2016-11-25 03:13:21.441606)  CosmosEx starting, version: 2016-11-09
00011893 00001068 (2016-11-25 13:13:22.509524)  NetworkSettings::updateResolvConf -- didn't update resolv.conf - network settings are DHCP
00012248 00000355 (2016-11-25 13:13:22.863908)  Side / Track out of range, returning empty track. Franz wants: [track 0, side 0], but current image has only: [track 0, side 0, sectors/track: 0]
00015040 00002792 (2016-11-25 13:13:25.656072)  Side / Track out of range, returning empty track. Franz wants: [track 0, side 0], but current image has only: [track 0, side 0, sectors/track: 0]
00020270 00005230 (2016-11-25 13:13:30.885980)  CCoreThread received weird ATN code fe waitForATN()
00020270 00000000 (2016-11-25 13:13:30.886404)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00022490 00002220 (2016-11-25 13:13:33.106201)  CURL curl_easy_perform() failed: Couldn't resolve host name
00023300 00000810 (2016-11-25 13:13:33.916339)  Downloader - download of http://joo.kie.sk/cosmosex/update/updatelist.csv didn't finish with success, deleting incomplete file.
00024560 00001260 (2016-11-25 13:13:35.175872)  CCoreThread received weird ATN code fe waitForATN()
00024670 00000110 (2016-11-25 13:13:35.285931)  CConSpi - didn't TX/RX enough data, padding with 8 zeros! Fix this!
00027600 00002930 (2016-11-25 13:13:38.215958)  CCoreThread received weird ATN code fe waitForATN()
00027780 00000180 (2016-11-25 13:13:38.395947)  CConSpi - didn't TX/RX enough data, padding with 8 zeros! Fix this!
00030740 00002960 (2016-11-25 13:13:41.356131)  CCoreThread received weird ATN code fe waitForATN()
00030740 00000000 (2016-11-25 13:13:41.356612)  CConSpi - didn't TX/RX enough data, padding with 8 zeros! Fix this!
00032991 00002251 (2016-11-25 13:13:43.606669)  CCoreThread received weird ATN code fe waitForATN()
00032991 00000000 (2016-11-25 13:13:43.607177)  CConSpi - didn't TX/RX enough data, padding with 8 zeros! Fix this!
00035890 00002899 (2016-11-25 13:13:46.505957)  CCoreThread received weird ATN code fe waitForATN()
00035910 00000020 (2016-11-25 13:13:46.526422)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00037900 00001990 (2016-11-25 13:13:48.516511)  CCoreThread received weird ATN code fe waitForATN()
00037901 00000001 (2016-11-25 13:13:48.516922)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00040230 00002329 (2016-11-25 13:13:50.846476)  CCoreThread received weird ATN code fe waitForATN()
00040231 00000001 (2016-11-25 13:13:50.846888)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00042080 00001849 (2016-11-25 13:13:52.696143)  CCoreThread received weird ATN code fe waitForATN()
00042110 00000030 (2016-11-25 13:13:52.726557)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00044170 00002060 (2016-11-25 13:13:54.786058)  CCoreThread received weird ATN code fe waitForATN()
00044170 00000000 (2016-11-25 13:13:54.786507)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00047610 00003440 (2016-11-25 13:13:58.226030)  CCoreThread received weird ATN code fe waitForATN()
00047610 00000000 (2016-11-25 13:13:58.226443)  CConSpi - didn't TX/RX enough data, padding with 16 zeros! Fix this!
00050410 00002800 (2016-11-25 13:14:01.025873)  applyTxRxLimits - TX/RX limits for HANS are probably wrong! Fix this!
00050710 00000300 (2016-11-25 13:14:01.325918)  CCoreThread received weird ATN code fe waitForATN()
00051060 00000350 (2016-11-25 13:14:01.675890)  CConSpi - didn't TX/RX enough data, padding with 2040 zeros! Fix this!
00052400 00001340 (2016-11-25 13:14:03.016049)  Side / Track out of range, returning empty track. Franz wants: [track 5, side 0], but current image has only: [track 0, side 0, sectors/track: 0]
00055050 00002650 (2016-11-25 13:14:05.665921)  CCoreThread received weird ATN code fe waitForATN()
00055120 00000070 (2016-11-25 13:14:05.736198)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00058410 00003290 (2016-11-25 13:14:09.025890)  CCoreThread received weird ATN code fe waitForATN()
00058420 00000010 (2016-11-25 13:14:09.036477)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00060630 00002210 (2016-11-25 13:14:11.245817)  CCoreThread received weird ATN code fe waitForATN()
00060700 00000070 (2016-11-25 13:14:11.316068)  CConSpi - didn't TX/RX enough data, padding with 8 zeros! Fix this!
00063230 00002530 (2016-11-25 13:14:13.846059)  CCoreThread received weird ATN code fe waitForATN()
00063440 00000210 (2016-11-25 13:14:14.056063)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00065520 00002080 (2016-11-25 13:14:16.136157)  CCoreThread received weird ATN code fe waitForATN()
00065520 00000000 (2016-11-25 13:14:16.136560)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00070120 00004600 (2016-11-25 13:14:20.735894)  Side / Track out of range, returning empty track. Franz wants: [track 5, side 0], but current image has only: [track 0, side 0, sectors/track: 0]
00070189 00000069 (2016-11-25 13:14:20.804748)  Side / Track out of range, returning empty track. Franz wants: [track 0, side 0], but current image has only: [track 0, side 0, sectors/track: 0]
00072969 00002780 (2016-11-25 13:14:23.585445)  CCoreThread received weird ATN code fe waitForATN()
00072970 00000001 (2016-11-25 13:14:23.586298)  Mounter::mount - mount failed. (mount dir: /mnt/shared)
00072986 00000016 (2016-11-25 13:14:23.602021)  Mounter::mount - mount error : Connection timed out
00072986 00000000 (2016-11-25 13:14:23.602364)  Mounter::mount - type=nfs source='192.168.20.2:/srv/nfs/ce-share' options='nolock,addr=192.168.20.2'
00072987 00000001 (2016-11-25 13:14:23.603186)  CConSpi - didn't TX/RX enough data, padding with 12 zeros! Fix this!
00073067 00000080 (2016-11-25 13:14:23.683545)  readHeader couldn't synchronize!
00084087 00011020 (2016-11-25 13:14:34.702833)  CURL curl_easy_perform() failed: Couldn't resolve host name
00084093 00000006 (2016-11-25 13:14:34.708744)  Downloader - download of http://joo.kie.sk/cosmosex/update/updatelist.csv didn't finish with success, deleting incomplete file.
```

**Comment by tin-nl** [comment]
@mikrosk: the only difference I can see now between my (upgraded) image and yours is the NFS mount. I'm using CIFS. So my guess is that sth in there doesn't behave if network isn't up. I'll have a look into that. 
Meanwhile: what happens in the testcase above in ce_tsthd if you disable nfs, disable WIFi, reeneable NFS?

**Comment by mikrosk** [comment]
I think it's safe to conclude it's the NFS -- as soon as I disable shared drive, it boots as one would expect -- no network interfaces found but it continues to desktop and everything is fine. So this issue is actually about two separate things:
1. Wait for wlan0 or signalise the user that wlan0 and therefore shared drive is not available (yet)
1. Investigate why enabling NFS and not having network makes CE unusable for couple of minutes.

As for your test case, it's hard for me to re-enable NFS for me when wifi is down ;), esp. if Ethernet makes this problem disappear (I guess I'd need access to HDMI output and real shell).

**Comment by atarijookie** [comment]
> regarding the WiFi chokes when changing APs - is there anything on ST side (TOS, ce_dd, ce_boot) that you know of, that doesn't retry? I am not sure if we can prevent CPU usage spikes by drivers, even if ce_main were a kernel module...

@tin-nl 
The retry is used by CE_DD.PRG, CE_CONF, CE_TSTHD.PRG, so hopefully the translated disks shouldn't end up with damaged data.

The retry is not used by CE bootsector, and TOS + any other driver - HDDRIVER, ICD Pro, PPera's disk driver, so using USB in RAW mode (and in future RAW disk image file) could get corrupted when the RPi chokes. 

RPi choking shouldn't affect SD card access as that is completely done in Hans, but Hans feels the need to communicate with RPi (and the ce_main_app requires that as a proof that Hans is alive and doesn't need a reset), and when the RPi chokes, this communication of Hans vs. ce_main_app might end up in blocking the ACSI/SCSI/SD access (although I thought it shouldn't, as it should be done in the background using DMA of Hans), and thus choking the SD card access, too. 

There could be an investigation (and hopefully fix) of the SD card vs. RPi choking thing (TODO), translated disk is safe(r) with retries, so I guess only USB RAW access isn't safe from choking. 

Ideally the RPi shouldn't choke once it booted :( ...and on Yocto, when booted and not doing stuff with wifi, I think it doesn't choke.

**Comment by tin-nl** [comment]
@mikrosk: I confirmed it's NFS - just enabling it without _any_ network attached lets a kworker go haywire with 97% cpu usage and above. And it's unrelated to the boot process - it's enough to enable the NFS share at any point in time.

As soon as I'm able to think a bit (damn flu), I'll add that network check to the mounter. We need it there anyways, regardless how we communicate that the user still has to wait.

**Comment by tin-nl** [comment]
@atarijookie: unfortunately the Wifi and NFS kernel module run with a -20 niceness - so ce_main doesn't stand a chance :) It's safe to say that the NFS thing will be solved by adding the network check. The WiFi choke is not nearly as bad (one single retry on AP change and several 9s on NFS) - I have no idea how to prevent that.

**Comment by mikrosk** [comment]
Wouldn't something as timeout = 0 help? I.e. isn't that caused by NFS trying again and again to mount?

**Comment by tin-nl** [comment]
I'm not sure. timeo is set to two minutes and describes the amount of time NFS keeps retrying - but it's not the timeout itself, that's around 60s if I read correctly. Yes, I'll try timeo=0 and soft etc., but I'm not too convinced that this won't open another can of worms. There is even _netdrv (don't connect if no iface is up), but that's only supported via commandline, not via c binding. We'll see.
Do you have any experience with those parameters?

**Comment by mikrosk** [comment]
I have actually zero experience with NFS in general. ;-) I was just guessing -- if we set it to, ok, not zero but say 5s, and it wont be able to mount after that time, we can safely assume the mount point is unavailable (either because network is down or still connecting). 

Because with your approach -- checking for eth0/wlan0 -- maybe there still will be problems like eth0/wlan0 available but NFS server not leading to the same behaviour (just guessing).

**Comment by tin-nl** [comment]
> but say 5, and it won't be able to mount after that time

According to the docs, that's exactly something that timeo does /not/ do :) The main timeouts are set for traffic in general, timeo only sets the repeat timeframe. So it is 60s of timeout even with timeo=5.
I surely will try that (and setting the traffic timouts lower), but we should consider that these values were chosen for a reason (aka flaky wifi etc.). Sure it's better to have NFS handle that for itself, but it seems to be very bad at it. Even a 5s choke of ce_main will be very problematic.

> but NFS server not

That's exactly the point: The behaviour seems to be tied explicitly to the IF not being up, not to having an IP or being able to connect to the NFS server. There seems to be no cpu hog if NFS isn't available. Tested with NFS server that's there and tested with NFS not there.

**Comment by tin-nl** [comment]
Did a quick test regarding the IF-up check, @mikrosk's image boots now without choking, same as if using CIFS. Have to do the NFS options (timeo,soft etc) tests.

I can confirm that NFS is not taking a choking amount of CPU time on yocto. With yocto it's possible to provoke retries in ce_tsthd via WiFi the same way as with raspbian - but it happens much less (raspbian has this every time).

**Comment by mikrosk** [comment]
@tin-nl: Isn't that an issue of the 4.4 kernel? For instance, if I do `rpi-update`, it takes ages to mount the nfs without adding `-overs=3` to the command line. So maybe NFS has been evolving since the Yocto kernel version.

**Comment by tin-nl** [comment]
@atarijookie I think this is a kernel module issue, yes - it happens with your released image and an upgraded one, but not with yocto. 
The nfs3/4 connection time issue seems to be a known one. AFAIR I also tested the IF-down issue with protocol version 3 w/o positive effect. Have to retest.

**Comment by atarijookie** [comment]
Thank you guys for examining it a lot, but crap - what we will do with it now? :) Recommend not using NFS with Raspbian?

**Comment by tin-nl** [comment]
My 2cents (well, 3 actually):
1. checking for an IF that is up should work around it pretty well, it should be pretty hard to produce this issue with that fix (at least in my implementation I couldn't produce it anymore). I'll check it in as soon as I rechecked it, so thers can test.
2. then we should check the timeout options mikro suggested - unfortunately this might break other working connections, and none uf us has real NFS experience, so at least I have to tread carefully
3. Check the NFS cliebt source, maybe it really is a bug. I had a look at the nfs-util sourcecode, just to see how _netdev option is implemented - also have to recheck this with a clearer head.

I have the feeling that there are more people using CIFS than using NFS (even I used it w/o thinking although my NAS is linux and supports NFS *facepalm*). 
With 1 we should patch up the symptom (which is _always_ a good idea, is there anything that can go wrobg with that? ;) ). Then we'll see what 2 and 3 show us. 
Unfortunatel I don't know anyone being an NFS expert...

**Comment by mikrosk** [comment]
@tin-nl: I agree. I'll happily test your workaround (1.) and let's then experiment with NFS timeouts and options.

**Comment by tin-nl** [comment]
Added the not-mounting-nfs-if-no-iface-is-up thing. Unfortunately I forgot to mention this issue in this commit. Ah, the joy of guthub not letting one reference that manually :/

Anyway, please see [here](/atarijookie/ce-atari/tree/nfs_workaround/). 
@mikrosk could you give this a spin?

Edit: recommitted with reference.
Reedit: dang, ignore the reference below, points to old (deleted) branch, use link above.

**Comment by atarijookie** [comment]
OK, I've merged the nfs_workaround branch... thank you for the fix :)

**Comment by mikrosk** [comment]
Jookie, you should have waited for me first. :-) I'll try to test in following days.

**Comment by atarijookie** [comment]
OK, let us know how it went then ;)

**Comment by mikrosk** [comment]
@tin-nl: thank you so much, your solution is very elegant and most importantly -- working! ;) Time needed for if up'ing wlan0 and mounting the shared drive respectively is much lower now.
