### ISSUE TITLE
Making floppy access faster

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#88]
Same as Hatari (and others) offers, sometimes (most of the time...) you don't really need exact motor emulation for floppies, just reading sectors as fast as possible is sufficient. I was genuinely surprised how slow the loading is, first I thought it actually froze.

**Comment by atarijookie** [comment]
Not possible.

WD1772 disk controller has fixed baud / bit rate, which needs to be met -
slower of faster won't work. Emularors achieve higher speed by avoiding low
level hardware emulation, whereas real floppy emulators (CE, HxC) need to
meet the exact bit stream speed.

**Comment by mikrosk** [comment]
Heartbroken. :-/
