### ISSUE TITLE
high bit of byte 3 of command is cleared.

### ISSUE THREAD

**Issue by miniupnp** [atarijookie/ce-atari#93]
look here : 
https://github.com/atarijookie/ce-atari/blob/master/ce_main_app/ccorethread.cpp#L492
the high bit is cleared, what ever the command.
We should check that it is a 'C' 'E' command before doing anything, right ?

@atarijookie : are CE commands only detected by tag ? also "command" should be 0, right ?

**Comment by miniupnp** [comment]
yes my doc is usefull : https://github.com/atarijookie/ce-atari/wiki/ACSI-SCSI-CosmosEx-Commands
;)

fix is coming soon.

**Comment by miniupnp** [comment]
@atarijookie : if it looks ok to you, you can merge my fix_93 branch

**Comment by atarijookie** [comment]
> We should check that it is a 'C' 'E' command before doing anything, right ?

Yes, you are right, it's wrong. It's OK for SD card (which is handled completely in Hans), it's OK for CE_DD, config, network, but it's very wrong for RAW USB drives and for your upcoming RAW images - I guess that that's how you noticed it, right?

Anyway, great detective work, thanks!

**Comment by miniupnp** [comment]
yes I spent hours wondering why ICD wont find the C: partition

is someone using RAW USB drives ? ;)

**Comment by atarijookie** [comment]
Well, I don't know, possibly yes, but there's one worse thing related to RAW USB drives and RAW images - RPi choking mentioned in #87 - I don't know how to solve that, and that might screw the RAW drives a lot...

**Comment by miniupnp** [comment]
Well I'll try to fix choking then ;)
but I think I've never had the problem.

**Comment by atarijookie** [comment]
> Well I'll try to fix choking then ;)
> but I think I've never had the problem.

As mentioned in #87 - when Raspberry is under heavy load, it might screw up the CE handling things, as there are timeouts everywhere - in HDDRIVER, ICD Pro, in Hans, in ce_main_app, and those RAW Atari drivers don't do retries. You might have not experienced this choking, as you maybe don't use wifi (connecting chokes the Raspberry) or NFS mounting chokes it a lot when there's some problem... 

In any way - helping with anything is greatly appreciated :+1:

**Comment by atarijookie** [comment]
Your branch fix_93 merged, thanks and closing :)

**Comment by miniupnp** [comment]
note : github is supposed to close the issue automatically when you merge into master : https://help.github.com/articles/closing-issues-via-commit-messages/
