### ISSUE TITLE
On Rapsbian network doesn't work when not using DHCP

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#96]
The user complains through fb messages:

> Pokud u Ethernetu vypnu DHCP, tak nejenže zadanou IP nebere v úvahu, ale úplně vypadne Wi-Fi adaptér! Prostě je mrtvý a neozývá se. Pokud u Ethernetu DHCP znovu zapnu, rozjede se i Wi-Fi.

Which translates to:
- if DHCP is off, it doesn't use the entered IP address, also wifi adapter is off / unusable
- if DHCP is on for eth0, everything is fine, even wifi

Have to check this out on Raspbian, which I don't have currently around... Maybe something wrong in configuration?

**Comment by mikrosk** [comment]
Well, I have noticed that with DHCP only IP address is filled out in CE_CONF. Maybe it's related?

**Comment by atarijookie** [comment]
> Well, I have noticed that with DHCP only IP address is filled out in CE_CONF. Maybe it's related?

No, that's a feature, so you could see your current IP in config if you have DHCP on.

**Comment by mikrosk** [comment]
That's fine, it's just I kind of expected to see my network mask and gateway as well. ;-)

**Comment by atarijookie** [comment]
This issue is due to the static network settings being in /etc/dhcpcd.conf in Raspbian. Write done in master, read is not done (currently just c&p from yocto, to be altered later).

**Comment by atarijookie** [comment]
Reading of settings has been added, but now the device ended up with some unknown settings and I can't connect to it through network :)

**Comment by atarijookie** [comment]
Fixed some issues there with loading and saving, there are still few things there:
- DNS value is wrong when using static IP
- DNS edit line is stretched to two lines and behaves odd!
- WPA PSK is stretched to two lines - done

**Comment by mikrosk** [comment]
> WPA PSK is stretched to two lines

That's perhaps my fault, setting it to the allowed maximum (63 octets). Any idea how to solve this?

**Comment by atarijookie** [comment]
> That's perhaps my fault, setting it to the allowed maximum (63 octets). Any idea how to solve this?

@mikrosk 
Yeah :) It's a nice C exercise - extend the config component, that you can set its screen size in characters, and then the full string size in characters, with inner text scrolling when moving to left or right ;)

**Comment by mikrosk** [comment]
On the other hand, two line fields are also not totally bad, maybe they just need some visual improvement. Will look into this.

**Comment by atarijookie** [comment]
@mikrosk I've just pushed the scrollable editline feature, now it looks better, and I guess we can consider this little thing as resolved (the long SSID / PSK lines).

**Comment by mikrosk** [comment]
@atarijookie damn man you're so productive, thanks!

**Comment by atarijookie** [comment]
Added code for restarting only eth0 when needed, or wlan0 when needed - not always even if the settings didn't change like before, and not both if settings changed only for one. 
Added also config setting for turning on/off wlan0 completely, e.g. when you don't need it and you want to save power. 

The DHCP / static thing still needs more testing, with real Atari, where you can see the network status through CE_CONF.PRG, because if I loose network without this Atari side access, I don't know what's wrong and can't fix it. But I guess I saw a static IP turned on a couple of times, it just takes lot of time.

**Comment by atarijookie** [comment]
Seems to be better after the last few improvements, and by forcing user to fill in DNS and gateway...

**Comment by mikrosk** [comment]
> and by forcing user to fill in DNS and gateway...

I'm a little bit confused -- so should I expect the gateway value to be set or not? Right now, I have DHCP and I see IP and Mask but not Gateway.

**Comment by atarijookie** [comment]
If you're using DHCP, it won't force you to fill those on save - no confusion.
If you're using static settings, it will force you to fill those on save - still no confusion.
If you're using DHCP, IP address is there shown for info purpose, so don't be confused here either ;)

**Comment by mikrosk** [comment]
;) If it already shows the IP and Mask, what prevents us to show the gateway as well? I know it's only for information purpose, I just feel sorry for the empty field ;) and sometimes it may come in handy.
