### ISSUE TITLE
NFS vs IP address change chokes the system hard

### ISSUE THREAD

**Issue by atarijookie** [atarijookie/ce-atari#98]
I got manually attached NFS share on Raspbian (the CE sources from my pc), I set the new static IP adress through CE config, I get disconnected (this is OK, as the IP changed).

Then I connect again to new IP, I try to change to directory where the NFS share was mounted, and it gets stuck for a very long time (or forever?). This is not something that is in CE app, but if I would have that NFS share used as shared drive, it would be the same. What's wrong with this NFS client / mount on Raspbian? Is there a less retarder version? :-D Or are there some default settings which would cause it to time-out sooner?

**Comment by tin-nl** [comment]
See #87 - there are some settings I'm currently checking, but it's not guaranteed to help. Also, those might have a negative effect on slower NFS servers/connections.

Until then it might help to unmount before changing IP - NFS unfortunately is very sensitive regarding an interface not being up (not to confuse with not being able to connect o the NFS server). 

I simply didn't test this specific case.

**Comment by atarijookie** [comment]
@tin-nl - thank you, you did there good examination on the issue :+1: 

OK, so I'll probably add some code, which will look at current mounts (even the manual ones, which might cause such trouble) and unmount everything before ifdown... 
Also having a checkbox for disabling (enabling) wifi would be nice - on RPi 3 you always have the wifi, but you might not want it... Will work on that later.

**Comment by tin-nl** [comment]
Before you add that: let me confirm wether or not timeout and retry options change anything. Would be nice to avoid ce_main having to take care of manual mounts, too....

**Comment by tin-nl** [comment]
It's enough to just try to use tab-completion on such a mountpoint to get the bash into a long wait. Fortunately CPU behaves as normal, so it's not related to #87 as much as I thought (fortunately).

Using smaller timeout values (e.g. "nolock,addr=192.168.0.4,intr,lookupcache=none,noac,timeo=50,retrans=1,fg") does result in, well, a shorter timeout - but the mount intself doesn't "heal".

NFS seems to have a nack on failing miserably when not unmounted properly. Tips to recover from this range from "reboot" to "close all file handles and kill all user processes, restart services xyz, pray" - so you're right, it's probably best to unmount/remount everything. Also a warning in config when using NFS mount might be a good idea. I get the feeling that NFS isn't very enduser friendly and that it wouldn't hurt to encourage Average Joe to use CIFS.

**Comment by miniupnp** [comment]
@tin-nl : are not «average joe»'s already using CIFS ? NFS is only used by geeks ;)

**Comment by mikrosk** [comment]
I definitely not consider myself as a linux pro but my reasoning was "CIFS is for Windows, NFS is for Linux". Perhaps it wasn't that smart. ;)

**Comment by atarijookie** [comment]
My choice for NFS at work is that my PC here is configured that the Windows sharing is disabled and I've managed to download and run a small NFS server service ;) (for sharing from Windows). At home where I do not suffer from such restrictions I always use CIFS. So maybe a warning in the config would be enough...

**Comment by mikrosk** [comment]
Btw guys, did you try to force version 3, as [mentioned](https://github.com/atarijookie/ce-atari/wiki/How-to-make-NFS-shares-working-(Linux)) in the wiki? I hope to get some spare time this weekend for CE so I'll do some tests as well.

> Using smaller timeout values (e.g. "nolock,addr=192.168.0.4,intr,lookupcache=none,noac,timeo=50,retrans=1,fg") does result in, well, a shorter timeout - but the mount intself doesn't "heal".

I guess you know about these, but I'm not sure whether it's any help:

**hard** or **soft** — Specifies whether the program using a file via an NFS connection should stop and wait (hard) for the server to come back online, if the host serving the exported file system is unavailable, or if it should report an error (soft).

If **hard** is specified, the user cannot terminate the process waiting for the NFS communication to resume unless the **intr** option is also specified.

If **soft** is specified, the user can set an additional **timeo**=<value> option, where <value> specifies the number of seconds to pass before the error is reported.

_Using soft mounts is not recommended as they can generate I/O errors in very congested networks or when using a very busy server._

**intr** — Allows NFS requests to be interrupted if the server goes down or cannot be reached.

This seems worth trying, too:

1. Assign Old IP of NFS server to an alias. ifconfig eth0:fakenfs Old_IP netmask xxx.xxx.xxx.xxx
1. umount -l /mount
1. bring down the alias: ifconfig eth0:fakenfs down
1. Mount the NFS share again: mount -a

**Comment by tin-nl** [comment]
@mikrosk: Yeah, exactly what I tried/meant (see option line). Do have to try nfs version 3 explicitly, tried it somewhere along the line with the CPU choking thing, but this doesn't seem to be tied to that.

**Comment by tin-nl** [comment]
Oh and didn't try the alias, as a) it is a workaround in case the server IP changes and b) this doesn't seem to help with having to unmount (even those not managed by CE) all nfs mounts before changing IP anyway. Seems to be a rats nest :)

**Comment by tin-nl** [comment]
@miniupnp: ex-act-ly ;) But we probably want to warn the incautious without NFS experience, that there will be dragons :)

**Comment by atarijookie** [comment]
Added a warning there, won't solve this for now, closing.
